import type { AgentIdentity,WorkerProfile } from './identity.ts';
export interface AuthorityGeneration { authority_domain_id:string; principal_id:string; capability_id:string; operation_scope:string; privacy_scope_digest:string; current_generation:number; authority_policy_id:string; authority_policy_version:number; privacy_policy_id:string; privacy_policy_version:number; version:number; }
export interface AuthorityLease { lease_id:string; principal_id:string; iris_identity_id:string; worker_identity_id:string; work_episode_id:string; causal_episode_id:string; authority_domain_id:string; capability_id:string; tool_id:string; operation_scope:string; privacy_scope:string[]; authority_policy_id:string; authority_policy_version:number; privacy_policy_id:string; privacy_policy_version:number; authority_generation:number; issued_at:string; expires_at?:string; state:'ACTIVE'|'REVOKED'|'EXPIRED'|'SUPERSEDED'; basis_refs:string[]; }
export interface LeaseContext { principal_id:string; iris_identity_id:string; worker:AgentIdentity; worker_profile:WorkerProfile; work_episode_id:string; causal_episode_id:string; capability_id:string; tool_id:string; operation_scope:string; privacy_scope:string[]; generation:AuthorityGeneration|null; unresolved_effect:boolean; unknown:boolean; now:string; }
// V0 shapes lack mandatory dimensions and cannot be a release/issuance proof.
export function validateLease(_lease:AuthorityLease,ctx:LeaseContext):{valid:false;reason:string}{return {valid:false,reason:ctx.unresolved_effect?'EFFECT_RECONCILIATION_REQUIRED':'CANONICAL_AUTHORITY_SNAPSHOT_REQUIRED'};}
export function revokeAuthorityDomain(g:AuthorityGeneration):AuthorityGeneration{return {...g,current_generation:g.current_generation+1,version:g.version+1};}
export function reauthorizeAuthorityDomain(g:AuthorityGeneration):AuthorityGeneration{return {...g,current_generation:g.current_generation+1,version:g.version+1};}
export function issueLease(_lease:AuthorityLease,ctx:LeaseContext):never {if(ctx.worker.retired_at||ctx.worker_profile.status!=='ACTIVE')throw new Error('WORKER_NOT_ELIGIBLE');throw new Error('CANONICAL_AUTHORITY_SNAPSHOT_REQUIRED');}
export {validateAuthority as validateCanonicalAuthority} from '../enforcement/contracts.ts';
import {EnforcementRepository,type ReleaseRequest} from '../enforcement/repository.ts';
export function issueCanonicalLease(repository:EnforcementRepository,request:ReleaseRequest){return repository.command({kind:'ISSUE_LEASE',value:{intent:request.intent,attempt:request.attempt,fence:request.fence}});}
// Legacy generation copies above are advisory only; durable revocation shares the release lock.
export function revokeCanonicalAuthority(repository:EnforcementRepository,principal:import('../semantic-kernel/identity.ts').Identity,domain:string,expectedGeneration:number,evidenceRefs:string[]){return repository.command({kind:'REVOKE',value:{principal,domain,expected_generation:expectedGeneration,evidence_refs:evidenceRefs}});}
