import crypto from 'node:crypto'; import type {ARClass,Intervention,PilotCandidate,ResolutionKind} from './pilot001-types.ts';
function anchors(c:PilotCandidate){const a:string[]=[]; if(c.objective_id)a.push('objective:'+c.objective_id);if(c.obligation_id)a.push('obligation:'+c.obligation_id);if(c.decision_requirement_id)a.push('decision_requirement:'+c.decision_requirement_id);if(c.intent_id)a.push('intent:'+c.intent_id);if(c.conflict_id)a.push('conflict:'+c.conflict_id);return a.sort();}
function missingMaterialARDimension(c:PilotCandidate){
  if(c.decision_requirement_id&&c.decision_status==='OPEN'&&(!c.decision_maker_identity_id||c.decision_maker_identity_id==='UNKNOWN'))return true;
  if(c.reserved_authority_class){
    if(!c.authority_holder_identity_id||c.authority_holder_identity_id==='UNKNOWN')return true;
    if(c.authority_holder_identity_id!=='AARON'&&typeof c.valid_delegation!=='boolean')return true;
  }
  return false;
}
export function classifyAaron(c:PilotCandidate):{classes:ARClass[];unknown:boolean;omittable:boolean}{ if(c.principal_id!=='AARON')return {classes:[],unknown:false,omittable:true}; const unknown=c.applicability==='UNKNOWN'||c.freshness==='UNKNOWN'||c.source_identity==='UNKNOWN'||c.source_identity==='CONFLICT'||missingMaterialARDimension(c); if(unknown)return {classes:[],unknown:true,omittable:false}; if(c.applicability!=='APPLICABLE')return {classes:[],unknown:false,omittable:true}; const classes:ARClass[]=[]; if(c.decision_requirement_id&&c.decision_status==='OPEN'&&c.decision_maker_identity_id==='AARON')classes.push('AR-1'); if(c.obligation_id&&['OPEN','IN_PROGRESS','WAITING','HOLD'].includes(c.obligation_status??'')&&c.obligation_owner==='AARON'&&c.concrete_action_remaining&&!c.informational_only)classes.push('AR-2'); if((c.reserved_authority_class&&c.authority_holder_identity_id==='AARON')||(c.reserved_authority_class&&c.authority_holder_identity_id!=='AARON'&&c.valid_delegation===false))classes.push('AR-3'); if(c.escalation_required||c.unresolved_effect||c.material_conflict)classes.push('AR-4'); return {classes,unknown:false,omittable:classes.length===0}; }
export function interventionFor(c:PilotCandidate,classes:ARClass[]):Intervention { const resolution_kind:ResolutionKind=classes.includes('AR-4')?'RESOLVE_CONFLICT':classes.includes('AR-3')?'AUTHORIZE':classes.includes('AR-1')?'DECIDE':'ACT'; const ar=anchors(c); const h=crypto.createHash('sha256').update(['pilot001-intervention-v1','AARON',resolution_kind,...ar].join('|')).digest('hex'); return {intervention_id:'arq_'+h,ar_classes:[...classes],resolution_kind,anchor_refs:ar,why_aaron_required:c.why??classes.join(','),provenance:[...c.provenance_refs],freshness:c.freshness??'UNKNOWN',uncertainty:[],possible_duplicate_refs:[...(c.possible_duplicate_refs??[])]}; }
export function sameCanonicalIntervention(a:Intervention,b:Intervention){return a.resolution_kind===b.resolution_kind&&JSON.stringify(a.anchor_refs)===JSON.stringify(b.anchor_refs);}
