import test from 'node:test';import assert from 'node:assert/strict';
import {setup as canonicalSetup,install,config,request,principal,worker,qid,put,T1,T2,T3} from './fixtures.ts';
import {setup as enforcementSetup,intent,receipt,deferred} from '../enforcement/fixtures.ts';
import {CapabilityService} from '../../src/capability/service.ts';
import {bindQualifiedRelease,QualifiedProviderAdapter} from '../../src/capability/adapters.ts';
import {digest} from '../../src/enforcement/contracts.ts';
import {MemoryCanonicalRepository} from '../../src/state/repository.ts';
import {PostgresCanonicalRepository} from '../../src/state/postgres-repository.ts';
import {engine} from '../canonical-repository/sql-fixture.ts';
import {withCapabilityContext} from '../../src/capability/context.ts';
import {evaluatePopulation} from '../../src/capability/service.ts';
import {identity} from '../../src/semantic-kernel/identity.ts';
async function bound(mode:'MEMORY'|'SQL'='MEMORY',override:any={}){const conf=config(),s=await enforcementSetup(mode,{i:intent({configuration_digest:digest(conf)})});await install(s.repo.canonical);let calls=0;const capabilities=new CapabilityService(s.repo.canonical,principal,()=>T1),binding={provider_id:conf.provider_id,tool_id:s.i.tool_id,operation:s.i.operation,configuration_digest:s.i.configuration_digest,capability_id:s.i.capability_id,qualification_id:s.i.qualification_id,credential_boundary:conf.tools[0].credential_boundary},adapter=new QualifiedProviderAdapter(override.binding??binding,{preflight:async()=>({ready:true}),submit:async(i,a,dispatch)=>{assert.ok(dispatch.length>0);calls++;return receipt(i,a);},...override}),release=bindQualifiedRelease(s.repo,capabilities,worker,request(),adapter);return {...s,conf,adapter,capabilities,release,calls:()=>calls,request:{intent:s.i,attempt:s.a,fence:s.c,retry:false}};}
for(const mode of ['MEMORY','SQL'] as const){
 test(mode+' trusted actual adapter + A3 + one-time durable ReleaseAttempt owns one release',async()=>{const s=await bound(mode);try{const results=await Promise.all([s.release.release(s.request),s.release.release(s.request)]);assert.equal(s.calls(),1);assert.ok(results.some(r=>r.state==='RELEASED_SUBMITTED'));await s.release.release({...s.request,retry:true});assert.equal(s.calls(),1);}finally{await s.close();}});
 test(mode+' canonical revocation wins before bound adapter dispatch',async()=>{const s=await bound(mode);try{await s.repo.command({kind:'REVOKE',value:{principal,domain:s.i.authority_domain,expected_generation:1,evidence_refs:['source:revoke']}});await assert.rejects(s.release.release(s.request));assert.equal(s.calls(),0);}finally{await s.close();}});
}
for(const name of ['provider_id','tool_id','operation','configuration_digest','capability_id','qualification_id','credential_boundary'])test('trusted adapter mismatch '+name+' cannot cause effect',async()=>{const s=await bound();const adapter=new QualifiedProviderAdapter({...s.adapter.binding,[name]:'wrong'},{preflight:async()=>({ready:true}),submit:async()=>{throw new Error('forbidden');}}),release=bindQualifiedRelease(s.repo,s.capabilities,worker,request(),adapter);try{const result=await release.release(s.request);assert.equal(result.state,'NO_SUBMISSION_PROVEN');}catch(error){assert.match((error as Error).message,/TRANSPORT_BINDING_MISMATCH/);}assert.equal(s.calls(),0);});
test('qualification change across preflight denies dispatch without blind retry',async()=>{const wait=deferred<{ready:true}>(),entered=deferred<void>(),s=await bound('MEMORY',{preflight:async()=>{entered.resolve();return wait.promise;}}),running=s.release.release(s.request);await entered.promise;await put(s.repo.canonical,worker,'CONFIGURATION',config(worker,{revision:2}));wait.resolve({ready:true});const r=await running;assert.equal(r.state,'AMBIGUOUS_SUBMISSION');assert.equal(s.calls(),0);await s.release.release({...s.request,retry:true});assert.equal(s.calls(),0);});
test('wrong principal/foreign capability repository cannot wire release service',async()=>{const s=await bound(),c=await canonicalSetup();assert.throws(()=>bindQualifiedRelease(s.repo,c.svc,worker,request(),s.adapter),/SAME_CANONICAL_OWNER/);});
test('mutable request cannot change candidate across first await',async()=>{const s=await canonicalSetup(),wire=await s.repo.exportSnapshot(),gate=deferred<void>(),entered=deferred<void>(),original=s.repo.exportSnapshot.bind(s.repo);let once=true;s.repo.exportSnapshot=async()=>{if(once){once=false;entered.resolve();await gate.promise;return wire;}return original();};const req=request(),running=s.svc.qualify(worker,qid,req);await entered.promise;req.capability_id='other';req.tools.length=0;gate.resolve();const q=await running;assert.equal(q.capability_id,'capability:one');});
test('Current drift during interpretation holds rather than returned mixed state',async()=>{const s=await canonicalSetup(),wire=await s.repo.exportSnapshot(),gate=deferred<void>(),entered=deferred<void>(),original=s.repo.exportSnapshot.bind(s.repo);let once=true;s.repo.exportSnapshot=async()=>{if(once){once=false;entered.resolve();await gate.promise;return wire;}return original();};const running=s.svc.qualify(worker,qid,request());await entered.promise;await put(s.repo,worker,'CONFIGURATION',config(worker,{revision:2}));gate.resolve();await assert.rejects(running,/CURRENT_CHANGED/);});
test('evaluator configuration drift after await invalidates outputs',async()=>{const s=await canonicalSetup(),binding={subject:worker,configuration_digest:digest(s.conf)};await assert.rejects(withCapabilityContext(s.repo,principal,T1,c=>evaluatePopulation(c,worker,'capability:one',{binding,evaluate:async()=>{binding.configuration_digest=digest('changed');return {accepted:true};}})),/CONFIGURATION_CHANGED/);});
for(const from of ['MEMORY','SQL'] as const)for(const to of ['MEMORY','SQL'] as const)test(from+' → fresh '+to+' exact B5 reconstruction, historical cuts, then continued writes',async()=>{const s=await canonicalSetup(from),e=to==='SQL'?await engine():null,repo=e?new PostgresCanonicalRepository(e.executor):new MemoryCanonicalRepository();try{const wire=await s.repo.exportSnapshot();await repo.importSnapshot(wire);assert.equal(await repo.exportSnapshot(),wire);const service=new CapabilityService(repo,principal,()=>T1),q=await service.qualify(worker,qid,request());assert.equal(q.configuration_digest,digest(s.conf));await put(repo,worker,'CONFIGURATION',config(worker,{revision:2}),{at:T2});assert.equal((await service.qualify(worker,qid,request())).configuration.revision,1);const late=new CapabilityService(repo,principal,()=>T3);await assert.rejects(late.qualify(worker,qid,request()));const fresh=new MemoryCanonicalRepository();await fresh.importSnapshot(await repo.exportSnapshot());assert.equal((await new CapabilityService(fresh,principal,()=>T1).qualify(worker,qid,request())).configuration.revision,1);}finally{await s.close();await e?.db.close();}});
test('direct provider adapter submission cannot forge or reuse a dispatch permit',async()=>{const s=await bound();assert.throws(()=>s.adapter.submit(s.i,s.a,{dispatch_id:'forged'}),/DURABLE_SUBMISSION_PERMIT_REQUIRED/);assert.equal(s.calls(),0);assert.throws(()=>bindQualifiedRelease(s.repo,s.capabilities,worker,request(),{...s.adapter} as any),/GUARDED_PROVIDER/);});
test('provider identity and permitted disclosure recipient must agree after A3 PASS',async()=>{const conf=config(),i=intent({configuration_digest:digest(conf)}),changed=intent({configuration_digest:digest(conf),privacy:{...i.privacy,recipient:principal}}),s=await enforcementSetup('MEMORY',{i:changed});await install(s.repo.canonical);let calls=0;const capabilities=new CapabilityService(s.repo.canonical,principal,()=>T1),adapter=new QualifiedProviderAdapter({provider_id:conf.provider_id,tool_id:s.i.tool_id,operation:s.i.operation,configuration_digest:s.i.configuration_digest,capability_id:s.i.capability_id,qualification_id:s.i.qualification_id,credential_boundary:conf.tools[0].credential_boundary},{preflight:async()=>({ready:true}),submit:async()=>{calls++;return receipt(s.i,s.a);}}),release=bindQualifiedRelease(s.repo,capabilities,worker,request(),adapter),r=await release.release({intent:s.i,attempt:s.a,fence:s.c,retry:false});assert.equal(r.state,'NO_SUBMISSION_PROVEN');assert.equal(calls,0);});
