import {MemoryCanonicalRepository,type CanonicalRepository} from '../../src/state/repository.ts';
import {PostgresCanonicalRepository} from '../../src/state/postgres-repository.ts';
import {CapabilityService} from '../../src/capability/service.ts';
import {B5,predicate} from '../../src/capability/context.ts';
import {decodeConfiguration,type Configuration,type CapabilityRequest} from '../../src/capability/qualification.ts';
import {IccpService,PROFILE,type Message,type ReceiverProfile,FIELDS,occurrenceMeaning} from '../../src/interop/iccp.ts';
import {digest} from '../../src/enforcement/contracts.ts';
import {identity,type Identity} from '../../src/semantic-kernel/identity.ts';
import {command,value,identityRow,principal,T0,T1,T2,T3} from '../canonical-repository/fixtures.ts';
import {time,worker,recipient} from '../enforcement/fixtures.ts';
import {engine} from '../canonical-repository/sql-fixture.ts';
export {principal,T0,T1,T2,T3,worker,recipient,time};
export const qid='qualification:one',cap='capability:one',procedure='procedure:one';
export const ref=(row:any)=>({record_id:row.record_id,object:row.object,version:row.version});
export function config(subject=worker,overrides:Partial<Configuration>={}):Configuration{return decodeConfiguration({schema_version:B5,subject,provider_id:'provider:a',provider_principal:recipient,model_id:'model',model_version:'v1',context_digest:digest('bounded-context'),harness_version:'qualified-harness:v1',revision:1,successor_of:null,role:'bounded-fixture',runtime_placement:'LOCAL',worker_class:'RESEARCH',status:'ACTIVE',availability:'READY',tools:[{tool_id:'fixture.action',operation:'set-fixture',credential_boundary:'LOCAL_FIXTURE_NO_CREDENTIAL'}],permissions:['bounded'],modalities:['text'],privacy_classes:['FIXTURE_NON_SENSITIVE'],risk_classes:['BOUNDED'],reasoning_class:'MEDIUM',cost_minor:10,latency_ms:5,resource_units:1,attention_units:1,reliability_ppm:990000,evidence_refs:['source:configuration'],...overrides}) as Configuration;}
export function request(overrides:Partial<CapabilityRequest>={}):CapabilityRequest{return {role:'bounded-fixture',capability_id:cap,procedure_id:procedure,procedure_version:1,dimensions:['text'],tools:[{tool_id:'fixture.action',operation:'set-fixture'}],permissions:['bounded'],modalities:['text'],privacy_classes:['FIXTURE_NON_SENSITIVE'],risk_classes:['BOUNDED'],context_digest:digest('bounded-context'),runtime_placements:['LOCAL'],providers_denied:[],min_reasoning_class:'LOW',max_reasoning_class:'HIGH',max_cost_minor:100,max_latency_ms:100,max_resource_units:10,max_attention_units:10,min_reliability_ppm:900000,...overrides};}
export function known(at=T0){return {knowledge_state:'KNOWN',applicability_state:'APPLICABLE',freshness_state:'CURRENT_AS_OF',coverage_state:'COMPLETE_FOR_DECLARED_SCOPE',as_of:at,evidence_refs:['source:qualified'],invalidators:[]};}
export async function register(repo:CanonicalRepository,refs:Identity[]){const history=await repo.history({schema_version:'IRIS_B2_V1',principal,as_of:T3});for(const r of refs)if(!history.some(row=>row.object_type==='IDENTITY'&&JSON.stringify(row.object)===JSON.stringify(r))){const row=identityRow(r);row.temporal=time();await repo.append(command(row));}}
export async function put(repo:CanonicalRepository,subject:Identity,name:string,data:unknown,opts:{at?:string;temporal?:any;epistemic?:any}={}){const at=opts.at??T0,id='b5:'+subject.id+':'+name;const h=await repo.history({schema_version:'IRIS_B2_V1',principal,as_of:T3}),revision=h.filter(row=>row.record_id===id).length+1,row=value('CURRENT',{subject,predicate:predicate(name),value:data,epistemic:opts.epistemic??known(at)},subject,id);row.version=revision;row.temporal=opts.temporal??time(at);return repo.append(command(row));}
export function policy(id:string,payload:unknown,source_refs:any[],overrides:any={}){return {schema_version:B5,policy_id:id,purpose:'CAPABILITY_ELIGIBILITY',recipient:principal,classification:'QUALIFICATION_EVIDENCE',payload_digest:digest(payload),source_refs,retain:'ALLOW',use:'ALLOW',disclose:'ALLOW',minimum_necessary:'ALLOW',allowed_fields:Object.keys(payload as object),retention_until:'2027-01-01T00:00:00.000Z',reuse:'THIS_PURPOSE_ONLY',transfer:'NO_TRANSFER',evidence_refs:['source:privacy-permission'],...overrides};}
export async function install(repo:CanonicalRepository,subject=worker,overrides:Partial<Configuration>={}){
 await register(repo,[principal,subject,recipient]);const conf=config(subject,overrides),confRow=await put(repo,subject,'CONFIGURATION',conf);
 const capIdentity={kind:'CAPABILITY' as const,id:cap};let capability:any;const history=await repo.history({schema_version:'IRIS_B2_V1',principal,as_of:T3});capability=history.find(v=>v.object_type==='ENTITY'&&v.object.id===cap);if(!capability){const ident=identityRow(capIdentity);ident.temporal=time();await repo.append(command(ident));const fields={capability_id:cap,name:'bounded capability',version:1,capability_class:'TEXT',procedure_ref:procedure,tool_requirements:['fixture.action'],authority_envelope:['bounded'],privacy_envelope:['FIXTURE_NON_SENSITIVE'],qualification_state:'QUALIFIED',evidence_refs:['source:capability'],failure_conditions:['missing evidence'],recovery_contract:'B4'};const row=value('ENTITY',{entity_version:'IRIS_B2_ENTITY_V1',source:{representation_version:'CAPABILITYPROCEDURE_V0',source:fields},epistemic:known()},capIdentity,'capability:canonical');row.temporal=time();capability=await repo.append(command(row));}
 let pop:any;try{const c=await repo.current({schema_version:'IRIS_B2_V1',principal,subject:principal,predicate:predicate('POPULATION:'+cap),as_of:T1});pop=c.record;}catch{}
 if(!pop)pop=await put(repo,principal,'POPULATION:'+cap,{schema_version:B5,population_id:'population:bounded',capability_id:cap,procedure_id:procedure,procedure_version:1,role:conf.role,cases:[{case_id:'task:one',dimension:'text',kind:'TASK',input:{text:'yes'},expected_output:{accepted:true}},{case_id:'negative:one',dimension:'text',kind:'NEGATIVE_CONTROL',input:{text:''},expected_output:{accepted:false}}],evidence_refs:['source:independent-population']});
 const p=(pop.payload as any).value,observations=[];for(const c of p.cases){observations.push(await put(repo,subject,'OBSERVATION:'+qid+':'+c.case_id,{schema_version:B5,case_id:c.case_id,qualification_id:qid,subject,configuration_digest:digest(conf),population_digest:digest(p),case_digest:digest(c),output:{accepted:typeof c.input.text==='string'&&c.input.text.length>0},evidence_refs:['actual:fixture-execution:'+c.case_id],source_class:'QUALIFICATION_FIXTURE'}));}
 const q={schema_version:B5,qualification_id:qid,subject,configuration_digest:digest(conf),role:conf.role,capability_id:cap,capability_ref:ref(capability),procedure_id:procedure,procedure_version:1,population_ref:ref(pop),observations:observations.map(ref),limitations:[],status:'ADMITTED',privacy_policy_id:'eligibility:'+subject.id,evidence_refs:['source:qualification']};const qRow=await put(repo,subject,'QUALIFICATION:'+qid,q),deps=[ref(confRow),ref(qRow),ref(capability),ref(pop),...observations.map(ref)],payload={qualification_id:qid,configuration_digest:digest(conf),dimensions:['text']};const privacy=policy(q.privacy_policy_id,payload,deps);await put(repo,principal,'PRIVACY:'+q.privacy_policy_id,privacy);
 await put(repo,subject,'SUBSTRATE',{schema_version:B5,subject,configuration_digest:digest(conf),sponsor:principal,purpose:'bounded research',return_destination:principal,work_refs:[],obligation_refs:[],authority_refs:[],privacy_refs:[],recovery_refs:[],evidence_refs:['source:substrate-profile']});return {conf,confRow,pop,observations,q,qRow,privacy,deps};
}
export async function setup(mode:'MEMORY'|'SQL'='MEMORY'){const e=mode==='SQL'?await engine():null,repo:CanonicalRepository=e?new PostgresCanonicalRepository(e.executor):new MemoryCanonicalRepository();const installed=await install(repo),svc=new CapabilityService(repo,principal,()=>T1),iccp=new IccpService(repo,principal,()=>T1);return {repo,e,...installed,svc,iccp,close:async()=>e?.db.close()};}
export function routeInput(subjects=[worker],req=request()){return {request_id:'route:one',request:req,candidates:subjects.map(subject=>({subject,qualification_id:qid})),mode:'RESEARCH'};}
export async function perceptionInput(s:Awaited<ReturnType<typeof setup>>,overrides:any={}){const observation_ref=ref(s.observations[0]),payload={output:{accepted:true}},privacy={policy_id:'perception',purpose:'PERCEPTION',recipient:principal,classification:'FIXTURE_NON_SENSITIVE',payload,source_refs:[observation_ref],retain:true,disclose:false,...overrides};await put(s.repo,principal,'PRIVACY:perception',policy('perception',payload,[observation_ref],{purpose:'PERCEPTION',classification:'FIXTURE_NON_SENSITIVE'}));return {subject:worker,qualification_id:qid,request:request(),observation_ref,perception_class:'EVIDENCE_CANDIDATE',privacy};}
export const messageId=identity('COMMUNICATION_EVENT','message:one'),occurrence=identity('CAUSAL_OCCURRENCE','communication:one');
export const receiver:ReceiverProfile={profile:PROFILE,vocabulary:'IRIS_A1_A5_V1',extensions:[],max_representation:'DENSE',recipient:principal};
export async function communicationInput(s:Awaited<ReturnType<typeof setup>>,overrides:Partial<Message>={}){await register(s.repo,[messageId,occurrence]);const message:Message={schema_version:B5,profile:PROFILE,vocabulary:'IRIS_A1_A5_V1',message:messageId,occurrence,actor:worker,principal,sponsor:principal,object_refs:[ref(s.confRow),{record_id:'causal:communication',object:occurrence,version:1}],base_refs:[],transition:'NO_DELTA',epistemic:known() as any,evidence_refs:['source:communication'],provenance_refs:['source:provenance'],privacy_refs:[],authority_refs:[],relations:[],temporal:time(),consequence:'OBSERVATION_ONLY',unresolved_debt:[],return_destination:principal,assurance:{required:['EXACT_REF'],achieved:['EXACT_REF']},loss:[],required_extensions:[],optional_extensions:{},...overrides};const cause=value('CAUSAL_OCCURRENCE',{occurrence,originating_ref:message.actor,first_occurred_at:T0,operation_digest:occurrenceMeaning(message),evidence_refs:['source:canonical-communication-occurrence']},occurrence,'causal:communication');cause.temporal=time();cause.references=[{record_id:'identity:WORKER:worker',object:worker,version:1}];await s.repo.append(command(cause));const refs=[...message.object_refs,...message.base_refs,...message.privacy_refs,...message.authority_refs],privacy={policy_id:'communication',purpose:'ICCP_COMMUNICATION',recipient:principal,classification:'FIXTURE_NON_SENSITIVE',payload:message,source_refs:refs,retain:false,disclose:true};await put(s.repo,principal,'PRIVACY:communication',policy('communication',message,refs,{purpose:privacy.purpose,classification:privacy.classification,allowed_fields:[...FIELDS]}));return {message,receiver,privacy,delivery:{event_id:'wire:one',attempt:1,trace_id:'trace:one',parent_event:null,recorded_at:T0,queue_latency_ms:0,failure_debt:[]}};}
