import test from 'node:test';import assert from 'node:assert/strict';
import {setup,perceptionInput,put,policy,principal,worker,qid,request,T1,T3} from './fixtures.ts';
import {digest} from '../../src/enforcement/contracts.ts';
for(const mode of ['MEMORY','SQL'] as const)test(mode+' qualified functional evidence and separate retention; no Current/authority',async()=>{const s=await setup(mode);try{const i=await perceptionInput(s),before=await s.repo.exportSnapshot(),p=await s.svc.perceive(i);assert.equal(p.persist,true);assert.equal(p.evidence,true);assert.equal(p.current,false);assert.equal(p.functional_state.claim,'DEMONSTRATED_CAPABILITY');assert.equal(p.functional_state.derived,true);assert.equal(p.functional_state.authority_effect,'NONE');assert.equal(await s.repo.exportSnapshot(),before);}finally{await s.close();}});
for(const flag of ['retain','use','minimum_necessary'])for(const v of ['DENY','UNKNOWN'])test('qualified evidence cannot override '+flag+':'+v,async()=>{const s=await setup(),i=await perceptionInput(s);await put(s.repo,principal,'PRIVACY:perception',policy('perception',i.privacy.payload,i.privacy.source_refs,{purpose:'PERCEPTION',classification:'FIXTURE_NON_SENSITIVE',[flag]:v}));await assert.rejects(s.svc.perceive(i));});
for(const [k,v] of Object.entries({recipient:{kind:'PRINCIPAL',id:'foreign'},purpose:'other',classification:'SECRET',payload_digest:digest('wrong'),allowed_fields:[],retention_until:T1,reuse:'ANY',transfer:'ANY',source_refs:[]}))test('perception total privacy binding '+k,async()=>{const s=await setup(),i=await perceptionInput(s);await put(s.repo,principal,'PRIVACY:perception',policy('perception',i.privacy.payload,i.privacy.source_refs,{purpose:'PERCEPTION',classification:'FIXTURE_NON_SENSITIVE',[k]:v}));await assert.rejects(s.svc.perceive(i));});
test('EPHEMERAL_WORKING cannot persist despite ALLOW retention',async()=>{const s=await setup(),i=await perceptionInput(s);await assert.rejects(s.svc.perceive({...i,perception_class:'EPHEMERAL_WORKING'}));const p=await s.svc.perceive({...i,perception_class:'EPHEMERAL_WORKING',privacy:{...i.privacy,retain:false}});assert.equal(p.persist,false);assert.equal(p.evidence,false);});
test('wrong/stale observation cannot borrow another qualified claim',async()=>{const s=await setup(),i=await perceptionInput(s);await assert.rejects(s.svc.perceive({...i,observation_ref:{...i.observation_ref,version:2}}));});
test('worker result is evidence candidate, never inferred true or canonical',async()=>{const s=await setup(),i=await perceptionInput(s),result={text:'bounded result'};await put(s.repo,principal,'PRIVACY:worker-result',policy('worker-result',result,[],{purpose:'RESEARCH',classification:'FIXTURE_NON_SENSITIVE'}));const r=await s.svc.qualifyWorkerResult({subject:worker,qualification_id:qid,request:request(),result,privacy:{policy_id:'worker-result',purpose:'RESEARCH',recipient:principal,classification:'FIXTURE_NON_SENSITIVE',payload:result,source_refs:[],retain:false,disclose:false}});assert.equal(r.result_truth,'NOT_ADJUDICATED');assert.equal(r.external_effect_count,0);assert.equal(r.canonical_current_mutation,false);});
