import test from 'node:test';import assert from 'node:assert/strict';
import {setup,request,put,routeInput,principal,worker,config,install,qid,T0,T1,T2,T3,ref} from './fixtures.ts';
import {B5,withCapabilityContext} from '../../src/capability/context.ts';
import {evaluatePopulation} from '../../src/capability/service.ts';
import {digest} from '../../src/enforcement/contracts.ts';
import {identity} from '../../src/semantic-kernel/identity.ts';
import {CognitionRouter} from '../../src/runtime/cognition-router.ts';
for(const mode of ['MEMORY','SQL'] as const){
 test(mode+' actual population/config qualification and routing is zero authority',async()=>{const s=await setup(mode);try{const before=await s.repo.exportSnapshot(),q=await s.svc.qualify(worker,qid,request()),r=await s.svc.route(routeInput());assert.equal(q.experience_class,'SOURCE_QUALIFICATION_ONLY');assert.equal(q.authority_effect,'NONE');assert.equal(r.state,'ROUTED');assert.equal(r.continuity_ON,false);assert.equal(await s.repo.exportSnapshot(),before);}finally{await s.close();}});
 test(mode+' actual executor compares positive/negative outputs against canonical population',async()=>{const s=await setup(mode);try{let calls=0;const result=await withCapabilityContext(s.repo,principal,T1,c=>evaluatePopulation(c,worker,'capability:one',{binding:{subject:worker,configuration_digest:digest(s.conf)},evaluate:async(input:any)=>{calls++;return {accepted:input.text.length>0};}}));assert.equal(calls,2);assert.ok(result.outputs.every(o=>o.pass));assert.equal(result.admission,'NOT_ADJUDICATED');}finally{await s.close();}});
}
const qMutations:any[]=[['foreign subject',{subject:identity('WORKER','foreign')}],['foreign config',{configuration_digest:digest('other')}],['role',{role:'other'}],['capability',{capability_id:'other'}],['procedure',{procedure_id:'other'}],['procedure version',{procedure_version:2}],['demoted',{status:'DEMOTED'}],['unknown',{status:'UNKNOWN'}],['limitation',{limitations:['text']}],['missing roster',{observations:[]}],['duplicate roster',(s:any)=>({observations:[ref(s.observations[0]),ref(s.observations[0])]})],['future population',(s:any)=>({population_ref:{...ref(s.pop),version:2}})],['extra coord',{authority:true}]];
for(const [label,mutation] of qMutations)test('qualification rejects '+label,async()=>{const s=await setup();await put(s.repo,worker,'QUALIFICATION:'+qid,{...s.q,...(typeof mutation==='function'?mutation(s):mutation)});await assert.rejects(s.svc.qualify(worker,qid,request()));});
for(const [label,change] of Object.entries({model_version:'v2',context_digest:digest('changed'),harness_version:'v2',revision:2,provider_id:'provider:b',role:'other',tools:[],permissions:[],status:'REPLACED',availability:'UNKNOWN',successor_of:identity('WORKER','old')}))test('material configuration invalidates prior claims '+label,async()=>{const s=await setup();await put(s.repo,worker,'CONFIGURATION',{...s.conf,[label]:change});await assert.rejects(s.svc.qualify(worker,qid,request()));});
for(const [label,change] of Object.entries({subject:identity('WORKER','other'),configuration_digest:digest('wrong'),population_digest:digest('wrong'),case_digest:digest('wrong'),output:{accepted:false},case_id:'unknown',qualification_id:'other',evidence_refs:[],source_class:'MODEL_SELF_REPORT'}))test('actual observation rejects '+label,async()=>{const s=await setup();const row=s.observations[0];await put(s.repo,worker,'OBSERVATION:'+qid+':task:one',{...(row.payload as any).value,[label]:change});await assert.rejects(s.svc.qualify(worker,qid,request()));});
for(const [label,change] of Object.entries({tools:[{tool_id:'other',operation:'set-fixture'}],permissions:['admin'],modalities:['audio'],privacy_classes:['SECRET'],risk_classes:['UNBOUNDED'],context_digest:digest('other'),runtime_placements:['CLOUD'],providers_denied:['provider:a'],min_reasoning_class:'HIGH',max_reasoning_class:'LOW',max_cost_minor:0,max_latency_ms:0,max_resource_units:0,max_attention_units:0,min_reliability_ppm:1000000,dimensions:['uncovered']}))test('eligibility rejects unmet '+label,async()=>{const s=await setup();await assert.rejects(s.svc.qualify(worker,qid,request({[label]:change})));});
for(const status of ['DENY','UNKNOWN'])test('qualification privacy use '+status+' blocks ranking',async()=>{const s=await setup();await put(s.repo,principal,'PRIVACY:'+s.q.privacy_policy_id,{...s.privacy,use:status});const r=await s.svc.route(routeInput());assert.equal(r.state,'ROUTE_UNAVAILABLE');});
test('benchmarks alone cannot satisfy actual task + negative coverage',async()=>{const s=await setup(),p=(s.pop.payload as any).value;await put(s.repo,principal,'POPULATION:capability:one',{...p,cases:p.cases.map((c:any)=>({...c,kind:'BENCHMARK'}))});await assert.rejects(s.svc.qualify(worker,qid,request()));});
test('canonical tail preserves qualification; later Current invalidates and historical cut remains exact',async()=>{const s=await setup();await put(s.repo,worker,'CONFIGURATION',{...s.conf,revision:2},{at:T2});assert.equal((await s.svc.qualify(worker,qid,request())).configuration.revision,1);await assert.rejects(withCapabilityContext(s.repo,principal,T3,c=>import('../../src/capability/qualification.ts').then(m=>m.qualifyCapability(c,worker,qid,request()))));});
test('cheapest sufficient precedes latency; incapable cheap candidate never ranked; deterministic ties',async()=>{const s=await setup(),other=identity('WORKER','other');await install(s.repo,other,{cost_minor:1,latency_ms:90});let r=await s.svc.route(routeInput([worker,other]));assert.equal(r.selected?.subject.id,'other');await put(s.repo,other,'CONFIGURATION',config(other,{cost_minor:0,reasoning_class:'LOW'}));r=await s.svc.route(routeInput([other,worker],request({min_reasoning_class:'MEDIUM'})));assert.equal(r.selected?.subject.id,worker.id);assert.equal(r.holds.length,1);});
test('cognition modes/provider substitution preserve principal, personality and authority',async()=>{const s=await setup(),other=identity('WORKER','other');await install(s.repo,other,{provider_id:'provider:b'});const router=new CognitionRouter(s.svc,[{subject:worker,qualification_id:qid},{subject:other,qualification_id:qid}]);const before=await s.repo.exportSnapshot(),r=await router.route({request_id:'cog',phase:'THINK',task_type:'bounded',mode:'DEEP_ANALYSIS',capability:request({providers_denied:['provider:a']}),trace_context:'trace'});assert.equal(r.selected?.configuration.provider_id,'provider:b');assert.equal(r.principal.id,principal.id);assert.equal(r.personality_effect,'NONE');assert.equal(r.authority_effect,'NONE');assert.equal(r.usage,'UNKNOWN_UNTIL_ACTUAL_CALL');assert.equal(await s.repo.exportSnapshot(),before);});
test('NaN, fractional, negative and infinite metabolism is rejected',async()=>{const s=await setup();for(const value of [NaN,Infinity,-1,0.5])assert.throws(()=>config(worker,{cost_minor:value}));});
for(const [label,temporal] of Object.entries({expired:{valid_until:T1},future_observation:{observed_at:T2},revoked:{revoked_at:T1},review_due:{requalification_at:T1}}))test('qualification time '+label,async()=>{const s=await setup();await put(s.repo,worker,'QUALIFICATION:'+qid,s.q,{temporal:{recorded_at:T0,effective_from:T0,observed_at:T0,valid_until:T3,...temporal}});await assert.rejects(s.svc.qualify(worker,qid,request()));});
test('common procedure loading binds canonical version + provider; grants no tools',async()=>{const s=await setup(),input={subject:worker,qualification_id:qid,request:request(),provider_id:'provider:a'},p=await s.svc.loadProcedure(input);assert.equal(p.loaded,true);assert.deepEqual(p.tool_authority,[]);assert.equal(p.authority_effect,'NONE');await assert.rejects(s.svc.loadProcedure({...input,provider_id:'provider:b'}));await assert.rejects(s.svc.loadProcedure({...input,request:request({procedure_version:2})}));});
test('canonical capability cannot be omitted, swapped, or reduced to a qualification badge',async()=>{const s=await setup();for(const capability_ref of [{...s.q.capability_ref,version:2},{...s.q.capability_ref,object:{kind:'CAPABILITY',id:'other'}}]){await put(s.repo,worker,'QUALIFICATION:'+qid,{...s.q,capability_ref});await assert.rejects(s.svc.qualify(worker,qid,request()));}});
test('canonical tool/privacy/permission requirements cannot be narrowed by route request',async()=>{const s=await setup();for(const field of ['tools','privacy_classes','permissions'])await assert.rejects(s.svc.qualify(worker,qid,request({[field]:[]})));});
test('UNKNOWN/conflicted/stale qualification Current cannot create functional truth',async()=>{const s=await setup();for(const epistemic of [{knowledge_state:'UNKNOWN'},{freshness_state:'STALE'},{coverage_state:'UNKNOWN'},{invalidators:['contradiction:source']}]){const original=(s.qRow.payload as any).epistemic;try{await put(s.repo,worker,'QUALIFICATION:'+qid,s.q,{epistemic:{...original,...epistemic}});}catch{continue;}await assert.rejects(s.svc.qualify(worker,qid,request()));}});
test('actual evaluator failure is evidence/UNKNOWN, never automatic admission',async()=>{const s=await setup();const result=await withCapabilityContext(s.repo,principal,T1,c=>evaluatePopulation(c,worker,'capability:one',{binding:{subject:worker,configuration_digest:digest(s.conf)},evaluate:async()=>({accepted:true})}));assert.equal(result.outputs[1].pass,false);assert.equal(result.admission,'NOT_ADJUDICATED');await assert.rejects(withCapabilityContext(s.repo,principal,T1,c=>evaluatePopulation(c,worker,'capability:one',{binding:{subject:worker,configuration_digest:digest(s.conf)},evaluate:async()=>{throw new Error('source unavailable');}})));});
