import test from 'node:test';
import assert from 'node:assert/strict';
import { seededRepo, fixtureIntent, NOW } from '../helpers.ts';
import { ActionFixtureAdapter } from '../../src/tools/action-fixture-adapter.ts';
import { runBoundedCircuit } from '../../src/runtime/iris-workflow.ts';

const contract={tool_id:'fixture.action',authority_scope:'fixture.write',privacy_scope:'fixture.non_sensitive',retry_classification:'IDEMPOTENT_BY_KEY' as const,external:true};

test('C3 positive circuit closes only after verified effect and records restrained learning',async()=>{const r=seededRepo(); const f=new ActionFixtureAdapter({status:'READY'},true); const out=await runBoundedCircuit({repo:r,principalId:'aaron',objectiveId:'obj-parent',obligationId:'obl-1',episodeId:'episode-1',subjectRef:'fixture:source',predicate:'status',actionScope:'fixture.write',privacyScope:'fixture.non_sensitive',intent:fixtureIntent(),contract,executor:f,fixtureRead:()=>f.read(),expectedEffect:{status:'COMPLETE'},now:NOW}); assert.equal(out.status,'EPISODE_CLOSED'); assert.equal(r.obligations.get('obl-1')!.status,'CLOSED'); assert.equal(r.objectives.get('obj-parent')!.status,'SATISFIED'); assert.equal(r.learning.get('learning:episode-1')!.qualification_state,'CANDIDATE'); assert.ok(r.instrumentation.some(e=>e.event_type==='PERSONAL_BIRE')); assert.ok(r.instrumentation.some(e=>e.event_type==='CANDIDATE_LESSON_PROPOSED'));});
test('C3 negative control tool receipt success without effect cannot close objective',async()=>{const r=seededRepo(); const f=new ActionFixtureAdapter({status:'READY'},false); const out=await runBoundedCircuit({repo:r,principalId:'aaron',objectiveId:'obj-parent',obligationId:'obl-1',episodeId:'episode-1',subjectRef:'fixture:source',predicate:'status',actionScope:'fixture.write',privacyScope:'fixture.non_sensitive',intent:fixtureIntent(),contract,executor:f,fixtureRead:()=>f.read(),expectedEffect:{status:'COMPLETE'},now:NOW}); assert.equal(out.status,'OBJECTIVE_REMAINS_OPEN'); assert.equal(r.obligations.get('obl-1')!.status,'HOLD'); assert.equal(r.objectives.get('obj-parent')!.status,'OPEN'); assert.equal(out.verification.disposition,'VERIFIED_NO_EFFECT');});
