import {B5,CapabilityContext,same} from './context.ts';
import {decodeReference,type Reference} from '../domain/canonical.ts';
import {decodeIdentity,type Identity} from '../semantic-kernel/identity.ts';
import {demand,record,text,version,member,evidence,strings,freeze} from '../semantic-kernel/validation.ts';
import {denseArray,jsonValue} from '../domain/json.ts';
import {digest,sha,nonnegative} from '../enforcement/contracts.ts';
import {filterPrivacy} from './privacy.ts';
export interface Configuration {
 schema_version:typeof B5; subject:Identity;provider_id:string;provider_principal:Identity;model_id:string;model_version:string;context_digest:string;harness_version:string;
 revision:number;successor_of:Identity|null;role:string;runtime_placement:string;worker_class:string;status:'ACTIVE'|'REPLACED'|'RETIRED'|'UNKNOWN';availability:'READY'|'UNAVAILABLE'|'UNKNOWN';
 tools:{tool_id:string;operation:string;credential_boundary:string}[];permissions:string[];modalities:string[];privacy_classes:string[];risk_classes:string[];reasoning_class:'LOW'|'MEDIUM'|'HIGH';
 cost_minor:number;latency_ms:number;resource_units:number;attention_units:number;reliability_ppm:number;evidence_refs:string[];
}
export function decodeConfiguration(input:unknown):Readonly<Configuration>{
 const r=record(input,['schema_version','subject','provider_id','provider_principal','model_id','model_version','context_digest','harness_version','revision','successor_of','role','runtime_placement','worker_class','status','availability','tools','permissions','modalities','privacy_classes','risk_classes','reasoning_class','cost_minor','latency_ms','resource_units','attention_units','reliability_ppm','evidence_refs']);demand(r.schema_version===B5,'B5_SCHEMA');
 const subject=decodeIdentity(r.subject);demand(['WORKER','SUBSTRATE'].includes(subject.kind),'B5_CONFIGURATION_SUBJECT');
 const tools=denseArray(r.tools).map(v=>{const t=record(v,['tool_id','operation','credential_boundary']);return {tool_id:text(t.tool_id),operation:text(t.operation),credential_boundary:text(t.credential_boundary)};});demand(new Set(tools.map(t=>JSON.stringify([t.tool_id,t.operation]))).size===tools.length,'B5_DUPLICATE_TOOL');
 const successor=r.successor_of===null?null:decodeIdentity(r.successor_of);demand(successor===null||['WORKER','SUBSTRATE'].includes(successor.kind)&&!same(successor,subject),'B5_SUCCESSOR_SUBJECT');
 const reliability=nonnegative(r.reliability_ppm);demand(reliability<=1_000_000,'B5_RELIABILITY_RANGE');
 const provider=decodeIdentity(r.provider_principal);demand(provider.kind==='PRINCIPAL','B5_PROVIDER_PRINCIPAL');return freeze({schema_version:B5,subject,provider_id:text(r.provider_id),provider_principal:provider,model_id:text(r.model_id),model_version:text(r.model_version),context_digest:sha(r.context_digest),harness_version:text(r.harness_version),revision:version(r.revision),successor_of:successor,role:text(r.role),runtime_placement:text(r.runtime_placement),worker_class:text(r.worker_class),status:member(r.status,['ACTIVE','REPLACED','RETIRED','UNKNOWN']),availability:member(r.availability,['READY','UNAVAILABLE','UNKNOWN']),tools,permissions:strings(denseArray(r.permissions)),modalities:strings(denseArray(r.modalities)),privacy_classes:strings(denseArray(r.privacy_classes)),risk_classes:strings(denseArray(r.risk_classes)),reasoning_class:member(r.reasoning_class,['LOW','MEDIUM','HIGH']),cost_minor:nonnegative(r.cost_minor),latency_ms:nonnegative(r.latency_ms),resource_units:nonnegative(r.resource_units),attention_units:nonnegative(r.attention_units),reliability_ppm:reliability,evidence_refs:evidence(denseArray(r.evidence_refs))});
}
export interface CapabilityRequest {
 role:string;capability_id:string;procedure_id:string;procedure_version:number;dimensions:string[];tools:{tool_id:string;operation:string}[];permissions:string[];modalities:string[];privacy_classes:string[];risk_classes:string[];context_digest:string;runtime_placements:string[];providers_denied:string[];
 min_reasoning_class:'LOW'|'MEDIUM'|'HIGH';max_reasoning_class:'LOW'|'MEDIUM'|'HIGH';max_cost_minor:number;max_latency_ms:number;max_resource_units:number;max_attention_units:number;min_reliability_ppm:number;
}
export const depth={LOW:0,MEDIUM:1,HIGH:2};
export function decodeRequest(input:unknown):Readonly<CapabilityRequest>{
 const r=record(input,['role','capability_id','procedure_id','procedure_version','dimensions','tools','permissions','modalities','privacy_classes','risk_classes','context_digest','runtime_placements','providers_denied','min_reasoning_class','max_reasoning_class','max_cost_minor','max_latency_ms','max_resource_units','max_attention_units','min_reliability_ppm']);
 const min=member(r.min_reasoning_class,['LOW','MEDIUM','HIGH']),max=member(r.max_reasoning_class,['LOW','MEDIUM','HIGH']);demand(depth[min]<=depth[max],'B5_REASONING_FLOOR_EXCEEDS_CEILING');
 const dimensions=evidence(denseArray(r.dimensions)),placements=evidence(denseArray(r.runtime_placements));demand(new Set(dimensions).size===dimensions.length,'B5_DUPLICATE_DIMENSION');
 return freeze({role:text(r.role),capability_id:text(r.capability_id),procedure_id:text(r.procedure_id),procedure_version:version(r.procedure_version),dimensions,tools:denseArray(r.tools).map(v=>{const t=record(v,['tool_id','operation']);return {tool_id:text(t.tool_id),operation:text(t.operation)};}),permissions:strings(denseArray(r.permissions)),modalities:strings(denseArray(r.modalities)),privacy_classes:strings(denseArray(r.privacy_classes)),risk_classes:strings(denseArray(r.risk_classes)),context_digest:sha(r.context_digest),runtime_placements:placements,providers_denied:strings(denseArray(r.providers_denied)),min_reasoning_class:min,max_reasoning_class:max,max_cost_minor:nonnegative(r.max_cost_minor),max_latency_ms:nonnegative(r.max_latency_ms),max_resource_units:nonnegative(r.max_resource_units),max_attention_units:nonnegative(r.max_attention_units),min_reliability_ppm:nonnegative(r.min_reliability_ppm)});
}
export interface QualifiedCapability {schema_version:typeof B5;subject:Identity;configuration:Readonly<Configuration>;configuration_digest:string;qualification_id:string;capability_id:string;procedure_id:string;procedure_version:number;dimensions:string[];dependencies:Reference[];evidence_refs:string[];authority_effect:'NONE';continuity_ON:false;experience_class:'SOURCE_QUALIFICATION_ONLY'}
// There is no caller-authored ADMITTED badge. Reconstruct the current population,
// complete actual observation roster, exact outputs, and configuration each time.
export async function qualifyCapability(c:CapabilityContext,subjectInput:Identity,qualificationIdInput:string,req:CapabilityRequest):Promise<Readonly<QualifiedCapability>>{
 const subject=freeze(decodeIdentity(subjectInput)),qid=text(qualificationIdInput);await c.registered(subject);
 const configSource=await c.current(subject,'CONFIGURATION'),config=decodeConfiguration(configSource.value),configDigest=digest(config);
 demand(same(config.subject,subject)&&config.status==='ACTIVE'&&config.availability==='READY','B5_CONFIGURATION_NOT_USABLE');
 await c.registered(config.provider_principal);
 const source=await c.current(subject,'QUALIFICATION:'+qid),q=record(source.value,['schema_version','qualification_id','subject','configuration_digest','role','capability_id','capability_ref','procedure_id','procedure_version','population_ref','observations','limitations','status','privacy_policy_id','evidence_refs']);demand(q.schema_version===B5&&q.status==='ADMITTED','B5_QUALIFICATION_NOT_ADMITTED');evidence(denseArray(q.evidence_refs));
 demand(q.qualification_id===qid&&same(q.subject,subject)&&q.configuration_digest===configDigest&&q.role===config.role&&config.role===req.role&&q.capability_id===req.capability_id&&q.procedure_id===req.procedure_id&&q.procedure_version===req.procedure_version,'B5_QUALIFICATION_TOTAL_BINDING');
 const limitations=strings(denseArray(q.limitations));demand(!req.dimensions.some(d=>limitations.includes(d)),'B5_CAPABILITY_LIMITATION');
 const capabilityRef=decodeReference(q.capability_ref),capability=await c.reference(capabilityRef);demand(capability.object_type==='ENTITY'&&capability.object.kind==='CAPABILITY'&&capability.object.id===req.capability_id,'B5_CANONICAL_CAPABILITY_REQUIRED');
 const cp=capability.payload as {source:{representation_version:string;source:Record<string,unknown>};epistemic:Record<string,unknown>};demand(cp.source.representation_version==='CAPABILITYPROCEDURE_V0'&&cp.source.source.procedure_ref===req.procedure_id&&cp.source.source.version===req.procedure_version&&cp.epistemic.knowledge_state==='KNOWN'&&cp.epistemic.applicability_state==='APPLICABLE'&&cp.epistemic.freshness_state==='CURRENT_AS_OF'&&cp.epistemic.coverage_state==='COMPLETE_FOR_DECLARED_SCOPE'&&denseArray(cp.epistemic.invalidators).length===0,'B5_CAPABILITY_PROCEDURE_BINDING');
 demand(strings(cp.source.source.tool_requirements).every(t=>req.tools.some(x=>x.tool_id===t)),'B5_CANONICAL_TOOL_FLOOR');
 demand(strings(cp.source.source.authority_envelope).every(t=>req.permissions.includes(t))&&strings(cp.source.source.privacy_envelope).every(t=>req.privacy_classes.includes(t)),'B5_CANONICAL_ENVELOPE_FLOOR');
 const popRef=decodeReference(q.population_ref),popSource=await c.reference(popRef);demand(popSource.object_type==='CURRENT','B5_POPULATION_CURRENT_REQUIRED');const pp=record(popSource.payload,['subject','predicate','value','epistemic']);
 const pop=record((await c.boundReference(popRef,c.principal,'POPULATION:'+req.capability_id)).value,['schema_version','population_id','capability_id','procedure_id','procedure_version','role','cases','evidence_refs']);
 demand(pop.schema_version===B5&&pop.capability_id===req.capability_id&&pop.procedure_id===req.procedure_id&&pop.procedure_version===req.procedure_version&&pop.role===req.role&&same(pp.subject,c.principal),'B5_POPULATION_BINDING');text(pop.population_id);evidence(denseArray(pop.evidence_refs));
 const cases=denseArray(pop.cases).map(v=>{const r=record(v,['case_id','dimension','kind','input','expected_output']);return {case_id:text(r.case_id),dimension:text(r.dimension),kind:member(r.kind,['TASK','NEGATIVE_CONTROL','BENCHMARK']),input:jsonValue(r.input),expected_output:jsonValue(r.expected_output)};});
 demand(cases.length>0&&cases.length<=256&&new Set(cases.map(v=>v.case_id)).size===cases.length,'B5_POPULATION_CASE_ID');
 for(const dimension of req.dimensions)for(const kind of ['TASK','NEGATIVE_CONTROL'])demand(cases.some(v=>v.dimension===dimension&&v.kind===kind),'B5_POPULATION_COVERAGE');
 const observations=denseArray(q.observations).map(decodeReference);demand(observations.length===cases.length&&new Set(observations.map(v=>v.record_id)).size===observations.length,'B5_OBSERVATION_ROSTER');
 const deps=[c.ref(configSource.row),c.ref(source.row),capabilityRef,popRef],seen=new Set<string>(),refs=evidence(denseArray(q.evidence_refs));
 for(const ref of observations){const row=await c.reference(ref);demand(row.object_type==='CURRENT','B5_OBSERVATION_CURRENT_REQUIRED');const payload=record(row.payload,['subject','predicate','value','epistemic']),raw=record(payload.value,['schema_version','case_id','qualification_id','subject','configuration_digest','population_digest','case_digest','output','evidence_refs','source_class']);
  const obs=(await c.boundReference(ref,subject,'OBSERVATION:'+qid+':'+text(raw.case_id))).value;demand(same(obs,raw),'B5_OBSERVATION_DRIFT');
  const actual=cases.find(v=>v.case_id===raw.case_id);demand(actual&&!seen.has(actual.case_id),'B5_OBSERVATION_CASE');seen.add(actual.case_id);
  demand(raw.schema_version===B5&&raw.qualification_id===qid&&same(raw.subject,subject)&&raw.configuration_digest===configDigest&&raw.population_digest===digest(pop)&&raw.case_digest===digest(actual),'B5_OBSERVATION_BINDING');member(raw.source_class,['QUALIFICATION_FIXTURE','LIVE_SOURCE']);
  demand(same(jsonValue(raw.output),actual.expected_output),'B5_DEMONSTRATED_OUTPUT_MISMATCH');refs.push(...evidence(denseArray(raw.evidence_refs)));deps.push(ref);
 }
 const subset=(required:readonly string[],actual:readonly string[])=>required.every(x=>actual.includes(x));
 demand(req.tools.every(t=>config.tools.some(x=>x.tool_id===t.tool_id&&x.operation===t.operation))&&subset(req.permissions,config.permissions)&&subset(req.modalities,config.modalities)&&subset(req.privacy_classes,config.privacy_classes)&&subset(req.risk_classes,config.risk_classes),'B5_REQUIRED_ENVELOPE_UNAVAILABLE');
 demand(config.context_digest===req.context_digest&&req.runtime_placements.includes(config.runtime_placement)&&!req.providers_denied.includes(config.provider_id),'B5_CONTEXT_PROVIDER_PLACEMENT');
 demand(depth[config.reasoning_class]>=depth[req.min_reasoning_class]&&depth[config.reasoning_class]<=depth[req.max_reasoning_class]&&config.cost_minor<=req.max_cost_minor&&config.latency_ms<=req.max_latency_ms&&config.resource_units<=req.max_resource_units&&config.attention_units<=req.max_attention_units&&config.reliability_ppm>=req.min_reliability_ppm,'B5_REQUIRED_RESOURCE_FLOOR');
 await filterPrivacy(c,{policy_id:text(q.privacy_policy_id),purpose:'CAPABILITY_ELIGIBILITY',recipient:c.principal,classification:'QUALIFICATION_EVIDENCE',payload:{qualification_id:qid,configuration_digest:configDigest,dimensions:[...req.dimensions]},source_refs:deps,retain:false,disclose:false});
 return freeze({schema_version:B5,subject,configuration:config,configuration_digest:configDigest,qualification_id:qid,capability_id:req.capability_id,procedure_id:req.procedure_id,procedure_version:req.procedure_version,dimensions:[...req.dimensions],dependencies:[...deps,c.ref((await c.current(c.principal,'PRIVACY:'+text(q.privacy_policy_id))).row)],evidence_refs:[...new Set(refs)],authority_effect:'NONE',continuity_ON:false,experience_class:'SOURCE_QUALIFICATION_ONLY'});
}
