import {prepared,principal,T0,T2,T3} from '../recovery/fixtures.ts';
import {time} from '../enforcement/fixtures.ts';
import {put,register,ref,known,policy} from '../capability-integration/fixtures.ts';
import {command,value,reference,identityRow} from '../canonical-repository/fixtures.ts';
import {METADATA_KINDS} from '../../src/domain/canonical.ts';
import {MemoryEnforcementRepository,PostgresEnforcementRepository} from '../../src/enforcement/backends.ts';
import {CanonicalPilotService} from '../../src/personal-office/pilot.ts';
import {B6,REQUIRED_SOURCES} from '../../src/personal-office/contracts.ts';
import {ROOT_DISPOSITION_VERSION,type RootDispositionV2} from '../../src/domain/root-disposition.ts';
import {identity,type Identity} from '../../src/semantic-kernel/identity.ts';
import {engine} from '../canonical-repository/sql-fixture.ts';
export {principal,T0,T2,T3,time,put,ref,register,known};
export function compound(root=identity('WORK_EPISODE','opaque:root'),overrides:Partial<RootDispositionV2>={}):RootDispositionV2{
 const q:RootDispositionV2={schema_version:ROOT_DISPOSITION_VERSION,root_ref:root,principal_ref:principal,version:1,as_of:T2,boundary_id:'attention:principal',consumer_class:'PERSONAL_OFFICE',epistemic:known(T2) as any,lifecycle:null,requirement:'REQUIRED',holder_knowledge_state:'KNOWN',holder_ref:principal,privacy:{recipient_ref:principal,purpose_ref:'PERSONAL_ATTENTION',disclosure_result:'PERMITTED',evidence_refs:['source:qualified']},primary_visible_disposition:'RELEVANCE_UNKNOWN',reason_set:[],visible_reason_projection:[],reactivation_refs:[],invalidator_refs:[],provenance_refs:['source:qualified'],projection_qualification:'NOT_ADJUDICATED',...overrides};
 const coordinates:any={KNOWLEDGE:q.epistemic.knowledge_state,APPLICABILITY:q.epistemic.applicability_state,FRESHNESS:q.epistemic.freshness_state,COVERAGE:q.epistemic.coverage_state,REQUIREMENT:q.requirement,HOLDER:q.holder_knowledge_state,DISCLOSURE:q.privacy.disclosure_result};if(q.lifecycle)coordinates.LIFECYCLE=q.lifecycle.state;
 q.reason_set=Object.entries(coordinates).map(([reason_type,canonical_code])=>({reason_id:'reason:'+reason_type,reason_type,canonical_code,evidence_refs:['source:qualified']})) as any;if(q.reactivation_refs.length)q.reason_set.push({reason_id:'reason:REACTIVATION',reason_type:'REACTIVATION',canonical_code:'REACTIVATION_RECORDED',evidence_refs:['source:qualified']});
 q.visible_reason_projection=q.privacy.disclosure_result==='PROHIBITED'?['reason:DISCLOSURE']:q.reason_set.map(r=>r.reason_id);if(q.privacy.disclosure_result==='PROHIBITED')q.primary_visible_disposition='PRIVACY_EXCLUDED';return q;
}
async function disposition(repo:import('../../src/enforcement/repository.ts').EnforcementRepository,root:Identity,life:any=null){await register(repo.canonical,[root]);const q=compound(root,{lifecycle:life,...(life&&['SATISFIED','SUPERSEDED','ABANDONED','RESOLVED'].includes(life.state)?{epistemic:{...known(T2),applicability_state:life.state==='RESOLVED'?'SATISFIED':life.state} as any,requirement:'NOT_REQUIRED_PROVEN' as const}: {})}),row=value('ROOT_DISPOSITION',q,root,'q:'+root.id);row.temporal=time(T2);row.evidence_refs=['source:qualified'];row.provenance_refs=['source:qualified'];row.references=[reference(principal),...(life?[{record_id:(await repo.canonical.history({schema_version:'IRIS_B2_V1',principal,as_of:T3})).filter(r=>r.object_type==='LIFECYCLE'&&r.object.id===root.id).at(-1)!.record_id,object:root,version:life.version}]:[])];const saved=await repo.canonical.append(command(row));await put(repo.canonical,principal,'PRIVACY:pilot:'+row.record_id,policy('pilot:'+row.record_id,q,[ref(saved)],{purpose:q.privacy.purpose_ref,classification:'PILOT_COMPOUND'}),{at:T2});return saved;}
let seed:Promise<{wire:string;roots:any[];sources:any[];scope:any;scopeRow:any;request:any}>|undefined;
export async function installPilot(s:Awaited<ReturnType<typeof prepared>>){
 const repo=s.repo,history=await repo.canonical.history({schema_version:'IRIS_B2_V1',principal,as_of:T3}),roots=[];
 for(const root of [s.i.objective,s.i.obligation])roots.push(await disposition(repo,root,history.filter(row=>row.object_type==='LIFECYCLE'&&row.object.id===root.id).at(-1)!.payload));
 roots.push(await disposition(repo,s.i.intent));
 const sources=[];for(const [n,source_id] of REQUIRED_SOURCES.entries())sources.push({source_id,reference:ref(await disposition(repo,identity('WORK_EPISODE','opaque:source:'+n)))});
 const resolutions=[];for(const [n,root] of roots.entries()){const resolution=identity('RESOLUTION','opaque:resolution:'+n);await register(repo.canonical,[resolution]);const row=value('CURRENT',{subject:resolution,predicate:JSON.stringify(['IRIS_B5_V1','PILOT_RESOLUTION']),value:{schema_version:B6,resolution,resolution_kind:root.object.kind==='INTENT'?'RECONCILE_EFFECT':'ACT',roots:[ref(root)],evidence_refs:['source:qualified']},epistemic:known(T2)},resolution,'resolution:current:'+n);row.references=[ref(root)];row.temporal=time(T2);resolutions.push(ref(await repo.canonical.append(command(row))));}
 const scope={schema_version:B6,principal,recipient:principal,purpose:'PERSONAL_ATTENTION',boundary_id:'attention:principal',consumer_class:'PERSONAL_OFFICE',roots:roots.map(ref),sources,resolutions,equivalences:[],evidence_refs:['source:qualified']},scopeRow=await put(repo.canonical,principal,'PILOT_SCOPE',scope,{at:T2}),request={schema_version:B6,principal,run:identity('PROJECTION_RUN','run:one'),as_of:T2,scope_ref:ref(scopeRow),recovery_scope_version:1,recipient:principal,purpose:scope.purpose,boundary_id:scope.boundary_id,consumer_class:scope.consumer_class};
 const wire=await repo.exportSnapshot();return {wire,roots,sources,scope,scopeRow,request};
}
async function makeSeed(){const s=await prepared('MEMORY','AMBIGUOUS_SUBMISSION');try{for(const kind of METADATA_KINDS){const row=identityRow({kind,id:s.i.objective.id});row.temporal=time();await s.repo.canonical.append(command(row));}return await installPilot(s);}finally{await s.close();}}
export async function fixture(mode:'MEMORY'|'SQL'='MEMORY'){
 seed??=makeSeed();const data=structuredClone(await seed),e=mode==='SQL'?await engine():null,repo=e?new PostgresEnforcementRepository(e.executor,()=>T2):new MemoryEnforcementRepository(()=>T2);await repo.importSnapshot(data.wire);
 return {...data,repo,svc:new CanonicalPilotService(repo),e,close:async()=>e?.db.close()};
}
export async function updateScope(s:Awaited<ReturnType<typeof fixture>>,patch:any){s.scope={...s.scope,...patch};s.scopeRow=await put(s.repo.canonical,principal,'PILOT_SCOPE',s.scope,{at:T2});s.request.scope_ref=ref(s.scopeRow);}
export async function updateRoot(s:Awaited<ReturnType<typeof fixture>>,index:number,change:(q:RootDispositionV2)=>RootDispositionV2,source=false){const refInput=source?s.sources[index].reference:ref(s.roots[index]),h=await s.repo.canonical.history({schema_version:'IRIS_B2_V1',principal,as_of:T3}),old=h.filter(r=>r.record_id===refInput.record_id).at(-1)!,q=change(structuredClone(old.payload as RootDispositionV2));q.version=old.version+1;const row={...old,version:q.version,event_ref:'event:'+old.record_id+':'+q.version,payload:q};const saved=await s.repo.canonical.append(command(row));await put(s.repo.canonical,principal,'PRIVACY:pilot:'+row.record_id,policy('pilot:'+row.record_id,q,[ref(saved)],{purpose:q.privacy.purpose_ref,classification:'PILOT_COMPOUND',disclose:q.privacy.disclosure_result==='PROHIBITED'?'DENY':q.privacy.disclosure_result==='UNKNOWN'?'UNKNOWN':'ALLOW'}),{at:T2});if(source){s.sources[index].reference=ref(saved);await updateScope(s,{sources:s.sources});}else{ s.roots[index]=saved;const resolutions=[];for(const rr of s.scope.resolutions){const resolution=h.find(r=>r.record_id===rr.record_id&&r.version===rr.version)!;const doc=(resolution.payload as any).value;const changed={...doc,roots:doc.roots.map((r:any)=>r.record_id===saved.record_id?ref(saved):r)};const next={...resolution,version:resolution.version+1,payload:{...(resolution.payload as any),value:changed},references:resolution.references.map(r=>r.record_id===saved.record_id?ref(saved):r)};resolutions.push(ref(await s.repo.canonical.append(command(next))));}await updateScope(s,{roots:s.roots.map(ref),resolutions});}return saved;}
