import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,updateRoot,updateScope,compound,principal,T2,T3,put,ref} from './fixtures.ts';
import {CanonicalPilotService} from '../../src/personal-office/pilot.ts';
import {PersonalOffice,candidateInterface} from '../../src/personal-office/office.ts';
import {get_objectives,get_open_obligations,get_aaron_required_items} from '../../src/agent-transition/capabilities.ts';
import {identity} from '../../src/semantic-kernel/identity.ts';
import {digest} from '../../src/enforcement/contracts.ts';
import {command,value} from '../canonical-repository/fixtures.ts';
import {deferred} from '../enforcement/fixtures.ts';
import {CanonicalPilotService as Service} from '../../src/personal-office/pilot.ts';
const change=(patch:any)=>(q:any)=>compound(q.root_ref,{...q,...patch,epistemic:{...q.epistemic,...patch.epistemic}});
test('source-qualified Pilot conserves exact roots and B1 coverage with durable unique run identity',async()=>{const s=await fixture();try{const p=await s.svc.project(s.request);assert.equal(p.projection.completeness_state,'COMPLETE_FOR_DECLARED_SCOPE');assert.equal(p.projection.roots.length,s.roots.length);assert.equal(p.projection.source_coverage.length,8);assert.equal(p.projection.interventions.length,s.roots.length);assert.equal(p.continuity_ON,false);assert.equal(p.authority_effect,'NONE');assert.equal(p.admission,'NOT_ADJUDICATED');assert.equal(p.current_at_delivery,false);assert.equal(p.projection.recovery_completeness,'INCOMPLETE');assert.equal(p.projection.work_routing[0]!.next_safe_action,'RECONCILE_FIRST');assert.deepEqual(await s.svc.read(s.request),p);assert.deepEqual(await s.svc.project(s.request),p);}finally{await s.close();}});
for(const [name,patch,primary,coverage] of [
 ['unknown holder',{holder_knowledge_state:'UNKNOWN',holder_ref:null},'RELEVANCE_UNKNOWN','UNKNOWN'],
 ['unknown knowledge',{epistemic:{knowledge_state:'UNKNOWN'},requirement:'UNKNOWN'},'RELEVANCE_UNKNOWN','UNKNOWN'],
 ['conflict plus unknown',{epistemic:{knowledge_state:'UNKNOWN',coverage_state:'CONFLICTED'},requirement:'UNKNOWN'},'CONFLICT_HOLD','CONFLICTED'],
 ['missing',{epistemic:{knowledge_state:'MISSING'},requirement:'UNKNOWN'},'RELEVANCE_UNKNOWN','INCOMPLETE'],
 ['unavailable',{epistemic:{knowledge_state:'UNAVAILABLE'},requirement:'UNKNOWN'},'RELEVANCE_UNKNOWN','INCOMPLETE'],
 ['stale',{epistemic:{freshness_state:'STALE'}},'RELEVANCE_UNKNOWN','INCOMPLETE'],
 ['required plus valid deferral',{reactivation_refs:['source:qualified']},'DEFERRED_SUPPRESSED_WITH_REACTIVATION','COMPLETE_FOR_DECLARED_SCOPE'],
 ['proven not applicable',{epistemic:{applicability_state:'NOT_APPLICABLE_PROVEN'},requirement:'NOT_REQUIRED_PROVEN',holder_knowledge_state:'UNKNOWN',holder_ref:null},'JUSTIFIED_NOT_APPLICABLE','COMPLETE_FOR_DECLARED_SCOPE']
] as const)test('canonical Pilot '+name,async()=>{const s=await fixture();try{await updateRoot(s,0,change(patch));const p=await s.svc.project(s.request);assert.equal(p.projection.roots[0]!.primary_visible_disposition,primary);assert.equal(p.projection.completeness_state,coverage);assert.equal(p.projection.roots.length,s.roots.length);}finally{await s.close();}});
test('prohibited conflict retains internal audit but reveals only privacy disposition and safe aggregate',async()=>{const s=await fixture();try{await updateRoot(s,0,q=>compound(q.root_ref,{...q,epistemic:{...q.epistemic,coverage_state:'CONFLICTED'},privacy:{...q.privacy,disclosure_result:'PROHIBITED'}}));const p=await s.svc.project(s.request),hidden=p.projection.roots[0]!;assert.equal(hidden.primary_visible_disposition,'PRIVACY_EXCLUDED');assert(hidden.reason_set.every(r=>r.reason_type==='DISCLOSURE'));assert.equal(p.projection.completeness_state,'UNKNOWN');assert(!JSON.stringify(p).includes('CONFLICTED'));const wire=JSON.parse(await s.repo.exportSnapshot()),audit=wire.canonical.records.findLast((r:any)=>(r.payload?.value?.state==='COMPLETE')).payload.value.data;assert.equal(audit.coverage,'CONFLICTED');assert(audit.compound_audit[0].canonical.reason_set.some((r:any)=>r.canonical_code==='CONFLICTED'));assert.equal(audit.compound_audit[0].canonical.lifecycle.state,'NONTERMINAL');}finally{await s.close();}});
for(const [name,patch] of [['unknown privacy',{privacy:{recipient_ref:principal,purpose_ref:'PERSONAL_ATTENTION',disclosure_result:'UNKNOWN',evidence_refs:['source:qualified']}}],['incomplete reason set',null],['unqualified basis',false]] as const)test('preflight HOLD '+name+' before run or proof mutation',async()=>{const s=await fixture();try{await updateRoot(s,0,q=>{if(patch===null)return {...q,reason_set:q.reason_set.filter(r=>r.reason_type!=='HOLDER'),visible_reason_projection:q.visible_reason_projection.filter(r=>r!=='reason:HOLDER')};if(patch===false)return {...q,provenance_refs:['invented:source']};return compound(q.root_ref,{...q,...patch});});const before=await s.repo.exportSnapshot();await assert.rejects(s.svc.project(s.request),/B6_DISCLOSURE_UNKNOWN_HOLD|B6_INCOMPLETE_COMPOUND_REASONS|B6_UNQUALIFIED_REASON_BASIS/);assert.equal(await s.repo.exportSnapshot(),before);}finally{await s.close();}});
for(const [field,changed] of [['purpose','OTHER'],['boundary_id','OTHER'],['consumer_class','OTHER'],['principal',identity('PRINCIPAL','other')],['recipient',identity('PRINCIPAL','other')]] as const)test('exact boundary fails closed on '+field,async()=>{const s=await fixture();try{const before=await s.repo.exportSnapshot();await assert.rejects(s.svc.project({...s.request,[field]:changed}),/B6_SCOPE_BOUNDARY_MISMATCH|B5_CURRENT_REQUIRED|B5_SELECTED_REFERENCE_MISMATCH|B4_CURRENT_REQUIRED/);assert.equal(await s.repo.exportSnapshot(),before);}finally{await s.close();}});
test('missing immutable source slot and duplicate source slot are rejected',async()=>{const s=await fixture();try{await updateScope(s,{sources:s.scope.sources.slice(1)});const before=await s.repo.exportSnapshot();await assert.rejects(s.svc.project(s.request),/B6_BOUNDED_REQUIRED_SCOPE/);assert.equal(await s.repo.exportSnapshot(),before);await updateScope(s,{sources:[s.sources[0],s.sources[0],...s.sources.slice(2)]});await assert.rejects(s.svc.project(s.request),/B6_REQUIRED_SOURCE_ROSTER/);}finally{await s.close();}});
test('mandatory source uncertainty drives the same B1 coverage fact list',async()=>{const s=await fixture();try{await updateRoot(s,7,change({epistemic:{knowledge_state:'UNKNOWN'},requirement:'UNKNOWN'}),true);const p=await s.svc.project(s.request);assert.equal(p.projection.completeness_state,'UNKNOWN');assert.equal(p.projection.source_coverage[7]!.primary_visible_disposition,'RELEVANCE_UNKNOWN');assert.equal(p.projection.roots[0]!.primary_visible_disposition,'KNOWN_REQUIRED');assert.deepEqual(p.projection.coverage_gaps,['DECLARED_SCOPE_NOT_COMPLETE']);}finally{await s.close();}});
test('duplicate roots cannot disappear through consolidation',async()=>{const s=await fixture();try{await updateScope(s,{roots:[s.scope.roots[0],s.scope.roots[0]]});await assert.rejects(s.svc.project(s.request),/B6_DUPLICATE_SCOPE_ROOT/);}finally{await s.close();}});
test('required root without explicit resolution stays HOLD',async()=>{const s=await fixture();try{await updateScope(s,{resolutions:[]});await assert.rejects(s.svc.project(s.request),/B6_EXACT_RESOLUTION_REQUIRED/);}finally{await s.close();}});
test('context alone never absorbs a conflict into an authority intervention',async()=>{const s=await fixture();try{await updateRoot(s,1,change({epistemic:{coverage_state:'CONFLICTED'}}));const p=await s.svc.project(s.request);assert.equal(p.projection.interventions.length,s.roots.length);assert.equal(p.projection.roots[1]!.primary_visible_disposition,'CONFLICT_HOLD');assert.deepEqual(p.projection.interventions.map(x=>x.root_refs.length),s.roots.map(()=>1));}finally{await s.close();}});
test('distinct run IDs preserve occurrences while identical projection content shares its content hash',async()=>{const s=await fixture();try{const a=await s.svc.project(s.request),b=await s.svc.project({...s.request,run:identity('PROJECTION_RUN','run:two')});assert.notDeepEqual(a.run,b.run);assert.equal(a.content_hash,b.content_hash);assert.notEqual(a.proof.canonical_digest,b.proof.canonical_digest);}finally{await s.close();}});
test('parallel duplicate invocation reconciles to one durable proof and one completion',async()=>{const s=await fixture();try{const results=await Promise.all([s.svc.project(s.request),s.svc.project(s.request)]);assert.deepEqual(results[0],results[1]);const snap=JSON.parse(await s.repo.exportSnapshot());assert.equal(snap.events.filter((e:any)=>e.command.kind==='VERIFY_PROJECTION').length,1);assert.equal(snap.canonical.records.filter((r:any)=>r.payload?.value?.state==='COMPLETE').length,1);}finally{await s.close();}});
test('mutable invocation cannot cross the first awaited boundary',async()=>{const s=await fixture();try{const started=deferred<void>(),resume=deferred<void>(),original=s.repo.canonical.current.bind(s.repo.canonical);let first=true;s.repo.canonical.current=async q=>{if(first){first=false;started.resolve();await resume.promise;}return original(q);};const req=structuredClone(s.request),pending=s.svc.project(req);await started.promise;req.recipient.id='changed';req.scope_ref.record_id='changed';req.run.id='changed';resume.resolve();const p=await pending;assert.deepEqual(p.run,s.request.run);assert.equal(p.projection.recipient.id,principal.id);}finally{await s.close();}});
test('a changed invocation cannot reuse a completed durable run',async()=>{const s=await fixture();try{await s.svc.project(s.request);await assert.rejects(s.svc.project({...s.request,purpose:'OTHER'}),/B6_RUN_INVOCATION_DRIFT/);}finally{await s.close();}});
for(const after of [false,true])test('crash '+(after?'after':'before')+' B4 proof resumes from the captured invocation without another occurrence',async()=>{const s=await fixture();try{const original=s.repo.command.bind(s.repo);let crash=true;s.repo.command=async c=>{if(crash&&(c as any).kind==='VERIFY_PROJECTION'){crash=false;if(after)await original(c);throw new Error('SIMULATED_PROCESS_LOSS');}return original(c);};if(after){const p=await s.svc.project(s.request);assert.equal(p.qualification,'SOURCE_QUALIFIED_PINNED_AS_OF');}else{await assert.rejects(s.svc.project(s.request),/SIMULATED_PROCESS_LOSS/);await s.svc.project(s.request);}const snapshot=JSON.parse(await s.repo.exportSnapshot());assert.equal(snapshot.events.filter((e:any)=>e.command.kind==='VERIFY_PROJECTION').length,1);}finally{await s.close();}});
test('crash before completed audit resumes from original pinned canonical prefix',async()=>{const s=await fixture();try{const original=s.repo.canonical.append.bind(s.repo.canonical);let crash=true;s.repo.canonical.append=async c=>{if(crash&&(c as any).value.payload?.value?.state==='COMPLETE'){crash=false;throw new Error('SIMULATED_AUDIT_CRASH');}return original(c);};await assert.rejects(s.svc.project(s.request),/SIMULATED_AUDIT_CRASH/);await put(s.repo.canonical,principal,'PILOT_SCOPE',{...s.scope,purpose:'LATER_CURRENT'},{at:T3});const p=await s.svc.project(s.request);assert.equal(p.projection.purpose,'PERSONAL_ATTENTION');assert.equal(p.current_at_delivery,false);const snap=JSON.parse(await s.repo.exportSnapshot());assert.equal(snap.events.filter((e:any)=>e.command.kind==='VERIFY_PROJECTION').length,1);}finally{await s.close();}});
test('pre-existing unrelated B4 run cannot be relabelled as a B6 capture',async()=>{const s=await fixture();try{await s.repo.command({kind:'VERIFY_PROJECTION',value:{schema_version:'IRIS_B4_V1',principal,run:s.request.run,scope_version:1}});await assert.rejects(s.svc.project(s.request),/B6_CAPTURE_NOT_IN_PROOF_PREFIX/);}finally{await s.close();}});
test('source change between capture and proof prevents a complete artifact',async()=>{const s=await fixture();try{const original=s.repo.command.bind(s.repo);s.repo.command=async c=>{if((c as any).kind==='VERIFY_PROJECTION')await put(s.repo.canonical,principal,'PILOT_SCOPE',{...s.scope,purpose:'DIFFERENT_BOUNDARY'},{at:T2});return original(c);};await assert.rejects(s.svc.project(s.request),/B5_SELECTED_REFERENCE_MISMATCH/);const snap=JSON.parse(await s.repo.exportSnapshot());assert.equal(snap.canonical.records.filter((r:any)=>r.payload?.value?.state==='COMPLETE').length,0);}finally{await s.close();}});
test('readback recomputes output from proof prefix and rejects repaired candidate outputs',async()=>{const s=await fixture();try{await s.svc.project(s.request);const snap=JSON.parse(await s.repo.exportSnapshot()),old=snap.canonical.records.findLast((r:any)=>r.payload?.value?.state==='COMPLETE'),payload=structuredClone(old.payload);payload.value.data.public_output.completeness_state='UNKNOWN';payload.value.data.content_hash=digest(payload.value.data.public_output);const row={...old,version:old.version+1,payload};await s.repo.canonical.append(command(row));await assert.rejects(s.svc.read(s.request),/B6_DURABLE_OUTPUT_DRIFT/);}finally{await s.close();}});
test('Personal Office, migrated queries, and candidate interface share one canonical Pilot owner',async()=>{const s=await fixture();try{const office=new PersonalOffice(s.repo,principal,()=>T2),p=await candidateInterface(office,{interface_version:'IRIS_CANONICAL_PILOT_B6_V1',operation:'GET_PERSONAL_ATTENTION',request:s.request});assert.deepEqual(await get_aaron_required_items(new Service(s.repo),s.request),p);assert.equal((await get_objectives(office,s.request)).items[0]!.root_ref.kind,'OBJECTIVE');assert.equal((await get_open_obligations(office,s.request)).items[0]!.root_ref.kind,'OBLIGATION');const recovery=await office.reconstruct(T2);assert.equal(recovery.recovery.continuity_ON,false);assert.equal(recovery.recovery.authority_effect,'NONE');assert.throws(()=>candidateInterface(office,{interface_version:'E1_UNQUALIFIED',operation:'SCORE',request:s.request}),/B6_CANDIDATE_INTERFACE_HOLD/);}finally{await s.close();}});
test('Personal Office cannot substitute another principal or legacy repository',async()=>{const s=await fixture();try{const office=new PersonalOffice(s.repo,principal,()=>T2);assert.throws(()=>office.attention({...s.request,principal:identity('PRINCIPAL','other')}),/B6_OFFICE_PRINCIPAL_MISMATCH/);assert.throws(()=>new PersonalOffice({} as any,principal,()=>T2),/B6_CANONICAL_REPOSITORY_REQUIRED/);assert.throws(()=>new CanonicalPilotService({} as any),/B6_CANONICAL_REPOSITORY_REQUIRED/);}finally{await s.close();}});
