import test from 'node:test';import assert from 'node:assert/strict';import {classifyAaron,interventionFor,sameCanonicalIntervention} from '../../src/agent-transition/pilot001-classifier.ts';import type {PilotCandidate} from '../../src/agent-transition/pilot001-types.ts';
const base: PilotCandidate={id:'x',principal_id:'AARON',applicability:'APPLICABLE',freshness:'CURRENT',source_identity:'VERIFIED',provenance_refs:['s']};
test('T29-T32 exact AR predicates',()=>{assert.deepEqual(classifyAaron({...base,decision_requirement_id:'d',decision_status:'OPEN',decision_maker_identity_id:'AARON'}).classes,['AR-1']);assert.deepEqual(classifyAaron({...base,obligation_id:'o',obligation_status:'OPEN',obligation_owner:'AARON',concrete_action_remaining:true}).classes,['AR-2']);assert.deepEqual(classifyAaron({...base,obligation_id:'o',reserved_authority_class:'X',authority_holder_identity_id:'AARON'}).classes,['AR-3']);assert.deepEqual(classifyAaron({...base,conflict_id:'c',material_conflict:true}).classes,['AR-4']);});
test('T33 overlap retains multiple predicates',()=>{const x=classifyAaron({...base,obligation_id:'o',obligation_status:'OPEN',obligation_owner:'AARON',concrete_action_remaining:true,decision_requirement_id:'d',decision_status:'OPEN',decision_maker_identity_id:'AARON',reserved_authority_class:'X',authority_holder_identity_id:'AARON',material_conflict:true});assert.deepEqual(new Set(x.classes),new Set(['AR-1','AR-2','AR-3','AR-4']));});
test('T34/T35/T36 informational/principal-only/satisfied negatives',()=>{assert.equal(classifyAaron({...base,informational_only:true}).classes.length,0);assert.equal(classifyAaron(base).classes.length,0);assert.equal(classifyAaron({...base,obligation_id:'o',obligation_status:'CLOSED',obligation_owner:'AARON',concrete_action_remaining:false,applicability:'SATISFIED'}).classes.length,0);});
test('T37 IRIS-owned + Aaron authority positive; T38 external-owned escalation positive',()=>{assert.deepEqual(classifyAaron({...base,obligation_id:'o',obligation_owner:'IRIS',reserved_authority_class:'X',authority_holder_identity_id:'AARON'}).classes,['AR-3']);assert.deepEqual(classifyAaron({...base,obligation_id:'o',obligation_owner:'EXTERNAL',escalation_required:true}).classes,['AR-4']);});
test('T39 exact canonical identity matches; T40 semantic similarity without anchor does not; T41 possible duplicate retained',()=>{const a=interventionFor({...base,obligation_id:'o'},['AR-2']),b=interventionFor({...base,id:'y',obligation_id:'o'},['AR-2']),c=interventionFor({...base,id:'z',obligation_id:'o2',possible_duplicate_refs:['o']},['AR-2']);assert.equal(sameCanonicalIntervention(a,b),true);assert.equal(sameCanonicalIntervention(a,c),false);assert.deepEqual(c.possible_duplicate_refs,['o']);});
test('open decision with missing decision-maker is UNKNOWN and not omittable',()=>{const r=classifyAaron({...base,decision_requirement_id:'d',decision_status:'OPEN'});assert.equal(r.unknown,true);assert.equal(r.omittable,false);});
test('reserved authority with unresolved holder/delegation is UNKNOWN',()=>{for(const c of [{...base,reserved_authority_class:'X'},{...base,reserved_authority_class:'X',authority_holder_identity_id:'IRIS'}]){const r=classifyAaron(c);assert.equal(r.unknown,true);assert.equal(r.omittable,false);}});
