import test from 'node:test';
import assert from 'node:assert/strict';
import {classifyAaron,interventionFor,interventionForResolution,sameCanonicalIntervention} from '../../src/agent-transition/pilot001-classifier.ts';
const base:any={id:'opaque:obligation:misleading',principal_id:'AARON',applicability:'APPLICABLE',freshness:'CURRENT',source_identity:'VERIFIED',provenance_refs:['claimed']};
// These historical DTO controls now require a named canonical-interface HOLD.
// Their positive semantic replacements are in tests/personal-office.
for(const [name,patch] of Object.entries({decision:{decision_requirement_id:'d',decision_status:'OPEN',decision_maker_identity_id:'AARON'},obligation:{obligation_id:'o',obligation_status:'OPEN',obligation_owner:'AARON',concrete_action_remaining:true},authorization:{reserved_authority_class:'X',authority_holder_identity_id:'AARON'},conflict:{material_conflict:true},unknownHolder:{reserved_authority_class:'X'},otherPrincipal:{principal_id:'OTHER'},terminal:{applicability:'SATISFIED'},informational:{informational_only:true},unknownDecision:{decision_requirement_id:'d',decision_status:'OPEN'}}))test('legacy classifier rejects unqualified '+name,()=>assert.throws(()=>classifyAaron({...base,...patch}),/^Error: B6_CANONICAL_PILOT_REQUIRED$/));
for(const name of ['DECIDE','ACT','AUTHORIZE','RECONCILE_EFFECT','RESOLVE_CONFLICT'] as const)test('legacy intervention rejects unqualified '+name,()=>assert.throws(()=>interventionForResolution(base,['AR-1'],name),/^Error: B6_CANONICAL_PILOT_REQUIRED$/));
test('legacy identity matching and intervention factory cannot self-qualify',()=>{assert.throws(()=>interventionFor(base,['AR-2']),/B6_CANONICAL_PILOT_REQUIRED/);assert.throws(()=>sameCanonicalIntervention({} as any,{} as any),/B6_CANONICAL_PILOT_REQUIRED/);});
