import test from 'node:test';import assert from 'node:assert/strict';
import {prepared,readback,verifyInput,retryPolicy,appendProof,principal,T0,T2,service,sourceId} from './fixtures.ts';
import {redigest,authorityDoc,receipt,time} from '../enforcement/fixtures.ts';
import {identity} from '../../src/semantic-kernel/identity.ts';
import {identityRow,command,value} from '../canonical-repository/fixtures.ts';
import {B4} from '../../src/recovery/contracts.ts';
import {authorityPredicate,digest} from '../../src/enforcement/contracts.ts';
import {VerificationService} from '../../src/recovery/service.ts';
for(const mode of ['MEMORY','SQL'] as const){
 test(`${mode} partial landed state needs verified compensation and subsequent positive absence before one retry`,async()=>{const s=await prepared(mode,'AMBIGUOUS_SUBMISSION');try{s.setObservation(readback(s,[{value:'partial:wrong'}]));const partial=await s.verifier.verify(verifyInput(s));assert.equal(partial.disposition,'AMBIGUOUS_EFFECT');await retryPolicy(s);await assert.rejects(async()=>s.recovery.authorizeRetry({schema_version:B4,attempt:s.a,expected_attempt_version:(await s.repo.getAttempt(s.a)).version,verification:partial.verification,policy_version:1,compensation_attempt:null}),/POSITIVE_ABSENCE/);
 const i=redigest({...s.i,intent:identity('INTENT','compensation:intent'),occurrence:identity('CAUSAL_OCCURRENCE','compensation:occurrence'),authority_domain:'domain:compensation',lease_id:'lease:compensation',idempotency_key:'key:compensation',arguments:{compensate:s.i.intent},privacy:{...s.i.privacy,minimum_necessary_digest:digest({compensate:s.i.intent})},expected_effect:{restored:true}}),a=identity('RELEASE_ATTEMPT','attempt:compensation');for(const ref of [i.intent,i.occurrence])await s.repo.canonical.append(command(identityRow(ref)));const d=authorityDoc(i,a),row=value('CURRENT',{subject:principal,predicate:authorityPredicate(i.authority_domain),value:d,epistemic:{knowledge_state:'KNOWN',applicability_state:'APPLICABLE',freshness_state:'CURRENT_AS_OF',coverage_state:'COMPLETE_FOR_DECLARED_SCOPE',as_of:T0,evidence_refs:['source:compensation-authority'],invalidators:[]}},principal,'current:compensation');row.temporal=time();await s.repo.canonical.append(command(row));await s.repo.command({kind:'ISSUE_LEASE',value:{intent:i,attempt:a,fence:s.c}});let compensationCalls=0;const f=service({...s,i,a},{submit:async()=>{compensationCalls++;return {...receipt(i,a),receipt:identity('RECEIPT','receipt:compensation'),provider_call_id:'fixture-call:compensation'};}});await f.service.release(f.request);
 const observation=readback({...s,i} as any);observation.entries[0].provider_call_id='fixture-call:compensation';const verifier=new VerificationService(s.repo,{binding:s.source.binding,scan:async()=>observation},()=>T2);await verifier.verify({attempt:a,verification:identity('VERIFICATION','verification:compensation'),prediction_ref:null});
 s.setObservation(readback(s,[],T2,2));const absent=await s.verifier.verify(verifyInput(s,'verification:restored-original'));const wire=JSON.parse(await s.repo.exportSnapshot()),policy=wire.canonical.commands.find((c:any)=>c.value.payload?.predicate===JSON.stringify([B4,'RETRY'])).value.payload.value;policy.compensation_attempt=a;await appendProof(s,s.i.intent,'RETRY',policy,2,T2);await s.recovery.authorizeRetry({schema_version:B4,attempt:s.a,expected_attempt_version:(await s.repo.getAttempt(s.a)).version,verification:absent.verification,policy_version:2,compensation_attempt:a});const retry=service(s);retry.request.retry=true;await retry.service.release(retry.request);await retry.service.release(retry.request);assert.equal(retry.calls(),1);assert.equal(compensationCalls,1);assert.equal((await s.repo.inspect()).effects.length,3);
 }finally{await s.close();}});
 test(`${mode} genuine prospective prediction binds to preparation prefix; backdated later append is rejected`,async()=>{const prediction=(s:any)=>({schema_version:B4,intent:s.i.intent,operation_digest:s.i.operation_digest,prediction_digest:digest('predict:match'),evidence_refs:['source:prediction']}),s=await prepared(mode,'RELEASED_SUBMITTED',{},async s=>{await appendProof(s,s.i.intent,'PREDICTION',prediction(s));});try{const ref={record_id:JSON.stringify([B4,'PREDICTION',s.i.intent]),object:s.i.intent,version:1},proof=await s.verifier.verify({...verifyInput(s),prediction_ref:ref});assert.deepEqual(proof.prediction_ref,ref);assert.equal(proof.experience_class,'SYNTHETIC_QUALIFICATION');await appendProof(s,s.i.intent,'PREDICTION_LATE',prediction(s),1,T0);s.setObservation(readback(s,[s.i.expected_effect],T2,2));await assert.rejects(()=>s.verifier.verify({...verifyInput(s,'verification:late'),prediction_ref:{record_id:JSON.stringify([B4,'PREDICTION_LATE',s.i.intent]),object:s.i.intent,version:1}}),/PROSPECTIVE_PREDICTION/);}finally{await s.close();}});
}
