import test from 'node:test';import assert from 'node:assert/strict';
import {prepared,readback,verifyInput,principal,T1,T2,appendProof,sourceDoc,sourceId,closeInput,retryPolicy,service,authorityDoc} from './fixtures.ts';
import {currentDoc,deferred,intent} from '../enforcement/fixtures.ts';
import {identity} from '../../src/semantic-kernel/identity.ts';
import {VerificationService} from '../../src/recovery/service.ts';
import {digest} from '../../src/enforcement/contracts.ts';
for(const mode of ['MEMORY','SQL'] as const){
 for(const phase of ['RELEASED_SUBMITTED','SUBMITTING','AMBIGUOUS_SUBMISSION'] as const)for(const disposition of ['EFFECT_VERIFIED','NO_EFFECT_VERIFIED','PARTIAL_EFFECT','AMBIGUOUS_EFFECT','CONFLICTED_EFFECT','UNAVAILABLE_READBACK','UNKNOWN'] as const)test(`${mode} ${phase} source verification ${disposition}`,async()=>{const s=await prepared(mode,phase,disposition==='PARTIAL_EFFECT'?{i:intent({expected_effect:{value:'requested',secondary:'expected'}})}:{});try{const o=readback(s);if(disposition==='NO_EFFECT_VERIFIED')o.entries=[];if(disposition==='PARTIAL_EFFECT')o.entries[0]!.value={value:'requested',secondary:'wrong'};
 if(disposition==='AMBIGUOUS_EFFECT')o.entries[0]!.value={value:'wrong'};if(disposition==='CONFLICTED_EFFECT')o.conflict_refs=['actual:source-conflict'];if(disposition==='UNAVAILABLE_READBACK')o.unavailable_refs=['actual:readback-unavailable'];if(disposition==='UNKNOWN')o.settled_through=null;s.setObservation(o);const proof=await s.verifier.verify(verifyInput(s));assert.equal(proof.disposition,disposition);assert.equal(proof.authority,'NONE');assert.deepEqual(proof.attempt,s.a);assert.equal(proof.operation_digest,s.i.operation_digest);const m=await s.repo.canonical.reconstruct({schema_version:'IRIS_B2_V1',principal,as_of:T2});assert.equal((m.views.find(v=>v.selected?.object_type==='EFFECT')!.selected!.payload as any).disposition,proof.disposition);assert.equal((await s.repo.getAttempt(s.a)).state,phase);assert.equal(s.scans(),1);assert.equal(s.release.calls(),phase==='RELEASED_SUBMITTED'?1:0);if(disposition==='EFFECT_VERIFIED'){const closed=await s.recovery.reconcileClosure(closeInput(s)) as any;assert.equal(closed.materialized.length,2);}else await assert.rejects(()=>s.recovery.reconcileClosure(closeInput(s)),/UNRESOLVED_EFFECT/);}finally{await s.close();}});
 for(const mutate of [(o:any)=>{o.operation_digest=digest('foreign');},(o:any)=>{o.intent.id='foreign';},(o:any)=>{o.principal.id='foreign';},(o:any)=>{o.occurrence.id='foreign';},(o:any)=>{o.configuration_digest=digest('foreign');},(o:any)=>{o.scope_refs=['foreign'];},(o:any)=>{o.observed_at=T1;},(o:any)=>{o.settled_through='2028-01-01T00:00:00.000Z';},(o:any)=>{o.entries[0].provider_call_id='foreign';},(o:any)=>{o.entries[0].occurrence.id='foreign';},(o:any)=>{o.entries.push(o.entries[0]);},(o:any)=>{o.exhaustive=null;},(o:any)=>{o.extra=true;},(o:any)=>{Object.defineProperty(o,'exhaustive',{enumerable:true,get(){throw Error('DO_NOT_READ_GETTER');}});}])test(`${mode} readback boundary rejects ${mutate.toString()}`,async()=>{const s=await prepared(mode);try{const o=structuredClone(readback(s));mutate(o);s.source.scan=async()=>o;const before=await s.repo.exportSnapshot();await assert.rejects(()=>s.verifier.verify(verifyInput(s)),e=>(e as Error).message!=='DO_NOT_READ_GETTER');assert.equal(await s.repo.exportSnapshot(),before);}finally{await s.close();}});
 test(`${mode} mismatch is not absence; qualified correction is explicit and preserved`,async()=>{const s=await prepared(mode);try{s.setObservation(readback(s,[{value:'wrong'}]));assert.equal((await s.verifier.verify(verifyInput(s))).disposition,'AMBIGUOUS_EFFECT');s.setObservation(readback(s,[],T2,2));assert.equal((await s.verifier.verify(verifyInput(s,'verification:two'))).disposition,'NO_EFFECT_VERIFIED');s.setObservation(readback(s,[s.i.expected_effect],T2,3));assert.equal((await s.verifier.verify(verifyInput(s,'verification:three'))).disposition,'EFFECT_VERIFIED');const wire=JSON.parse(await s.repo.exportSnapshot());assert.deepEqual(wire.events.filter((e:any)=>e.command.kind==='VERIFY_EFFECT').map((e:any)=>e.result.proof.disposition),['AMBIGUOUS_EFFECT','NO_EFFECT_VERIFIED','EFFECT_VERIFIED']);assert.equal(wire.canonical.commands.filter((c:any)=>c.value.object_type==='EFFECT').at(-1).transition.kind,'CORRECTION');}finally{await s.close();}});
 test(`${mode} invocation capture and source/Current mutation during await fail closed`,async()=>{const s=await prepared(mode);try{const gate=deferred<void>(),entered=deferred<void>(),input=structuredClone(verifyInput(s));s.source.scan=async()=>{entered.resolve();await gate.promise;return readback(s);};const pending=s.verifier.verify(input);await entered.promise;input.attempt.id='foreign';input.verification.id='foreign';gate.resolve();const proof=await pending;assert.deepEqual(proof.attempt,s.a);assert.equal(proof.verification.id,'verification:one');const gate2=deferred<void>(),entered2=deferred<void>();s.source.scan=async()=>{entered2.resolve();await gate2.promise;return readback(s,[],T2,2);};const p=s.verifier.verify(verifyInput(s,'verification:two'));await entered2.promise;await appendProof(s,principal,'SOURCE:'+sourceId,sourceDoc(s),2,T2);const before=await s.repo.exportSnapshot();gate2.resolve();await assert.rejects(()=>p,/SOURCE_VERSION_DRIFT/);assert.equal(await s.repo.exportSnapshot(),before);}finally{await s.close();}});
 test(`${mode} private/unknown/unqualified source cannot probe or verify`,async()=>{const s=await prepared(mode);try{const doc=sourceDoc(s);doc.privacy.retain='DENY' as any;await appendProof(s,principal,'SOURCE:'+sourceId,doc,2,T2);await assert.rejects(()=>s.verifier.verify(verifyInput(s)),/PRIVACY_DENIED/);assert.equal(s.scans(),0);await appendProof(s,principal,'SOURCE:'+sourceId,sourceDoc(s),3,T2);const auth=authorityDoc();auth.privacy_permission.use='DENY';await s.repo.canonical.append(currentDoc(auth,2,T2));await assert.rejects(()=>s.verifier.verify(verifyInput(s)),/PRIVACY_CURRENT_DENIED/);assert.equal(s.scans(),0);}finally{await s.close();}});
 test(`${mode} positive absence + explicit policy + full B3 revalidation permits exactly one retry`,async()=>{const s=await prepared(mode,'AMBIGUOUS_SUBMISSION');try{s.setObservation(readback(s,[]));const proof=await s.verifier.verify(verifyInput(s));await retryPolicy(s);const request={schema_version:'IRIS_B4_V1',attempt:s.a,expected_attempt_version:(await s.repo.getAttempt(s.a)).version,verification:proof.verification,policy_version:1,compensation_attempt:null};await s.recovery.authorizeRetry(request);await assert.rejects(()=>s.recovery.authorizeRetry(request),/POSITIVE_ABSENCE/);const f=service(s);f.request.retry=true;assert.equal((await f.service.release(f.request)).state,'RELEASED_SUBMITTED');await f.service.release(f.request);assert.equal(f.calls(),1);assert.equal((await s.recovery.reconstruct(principal,T2)).recovery.admission,'HOLD_RECONCILIATION_REQUIRED');}finally{await s.close();}});
}
