import {setup,service,principal,T0,T1,T2,T3,time,authorityDoc} from '../enforcement/fixtures.ts';
import {VerificationService,RecoveryService,type QualifiedReadbackSource} from '../../src/recovery/service.ts';
import {B4,predicate,type Readback} from '../../src/recovery/contracts.ts';
import {identity} from '../../src/semantic-kernel/identity.ts';
import {command,value} from '../canonical-repository/fixtures.ts';
import {digest} from '../../src/enforcement/contracts.ts';
export {principal,T0,T1,T2,T3,service,authorityDoc};
export const sourceId='fixture-readback',config=digest('readback-config');
export async function appendProof(s:Awaited<ReturnType<typeof setup>>,subject:any,kind:string,doc:any,revision=1,at=T0){const row=value('CURRENT',{subject,predicate:predicate(kind),value:doc,epistemic:{knowledge_state:'KNOWN',applicability_state:'APPLICABLE',freshness_state:'CURRENT_AS_OF',coverage_state:'COMPLETE_FOR_DECLARED_SCOPE',as_of:at,evidence_refs:['source:B4-qualified'],invalidators:[]}},subject,JSON.stringify([B4,kind,subject]));row.version=revision;row.temporal=time(at);return s.repo.canonical.append(command(row));}
export function sourceDoc(s:Awaited<ReturnType<typeof setup>>){return {schema_version:B4,source_id:sourceId,configuration_digest:config,source_class:'QUALIFICATION_FIXTURE',verification_contract:'OCCURRENCE_VALUE_SCAN_V1',principal,tool_id:s.i.tool_id,operation:s.i.operation,effect_class:s.i.effect_class,scope_refs:s.i.object_refs,status:'QUALIFIED',privacy:{recipient:s.i.privacy.recipient,purpose:s.i.privacy.purpose,retain:'ALLOW',use:'ALLOW',disclose:'ALLOW',egress:s.i.privacy.egress},temporal:time(),evidence_refs:['qualified:readback-source']};}
export function readback(s:Awaited<ReturnType<typeof setup>>,entries:unknown[]=[s.i.expected_effect],at=T2,revision=1):Readback{return {schema_version:B4,source_id:sourceId,configuration_digest:config,principal,intent:s.i.intent,occurrence:s.i.occurrence,operation_digest:s.i.operation_digest,observed_at:at,readback_version:revision,scope_refs:s.i.object_refs,settled_through:at,submission_finality:'SETTLED',exhaustive:true,entries:entries.map((v,n)=>({entry_id:'landed:'+n,provider_call_id:'fixture-call:1',operation_digest:s.i.operation_digest,occurrence:s.i.occurrence,value:v})),unavailable_refs:[],conflict_refs:[],evidence_refs:['actual:fixture-source-scan']};}
export async function prepared(mode:'MEMORY'|'SQL'='MEMORY',phase:'RELEASED_SUBMITTED'|'SUBMITTING'|'AMBIGUOUS_SUBMISSION'='RELEASED_SUBMITTED',opts:Parameters<typeof setup>[1]={},beforeRelease?:(s:Awaited<ReturnType<typeof setup>>)=>Promise<void>){
 const s=await setup(mode,opts);await appendProof(s,principal,'SOURCE:'+sourceId,sourceDoc(s));
 for(const object of [s.i.objective,s.i.obligation]){const payload={object,principal,version:1,state:'NONTERMINAL',last_event_ref:'life:'+object.id,evidence_refs:['source:life'],basis_ref:'source:life'};const row=value('LIFECYCLE',payload,object,'life:'+object.id);row.event_ref=payload.last_event_ref;row.temporal=time();await s.repo.canonical.append(command(row));}
 if(beforeRelease)await beforeRelease(s);const release=service(s);if(phase==='RELEASED_SUBMITTED')await release.service.release(release.request);else{await s.repo.command({kind:'PREPARE',value:{intent:s.i,attempt:s.a,fence:s.c}});await s.repo.command({kind:'RELEASE',value:{attempt:s.a,dispatch_id:'dispatch:uncertain',retry:false}});if(phase==='AMBIGUOUS_SUBMISSION')await s.repo.command({kind:'AMBIGUOUS',value:{attempt:s.a,dispatch_id:'dispatch:uncertain',evidence_refs:['source:transport-timeout']}});}
 s.setNow(T2);let scans=0,observation=readback(s);const source:QualifiedReadbackSource={binding:{source_id:sourceId,configuration_digest:config},scan:async()=>{scans++;return structuredClone(observation);}},verifier=new VerificationService(s.repo,source,()=>T2),recovery=new RecoveryService(s.repo);
 const sourceRow=JSON.parse(await s.repo.exportSnapshot()).canonical.commands.find((c:any)=>c.value.payload?.predicate===predicate('SOURCE:'+sourceId)).value;
 const scope={schema_version:B4,principal,required_roots:[s.i.objective,s.i.obligation],required_current:[{record_id:sourceRow.record_id,object:sourceRow.object,version:sourceRow.version}],purpose:'bounded-recovery',temporal:time(),evidence_refs:['source:scope-complete']};await appendProof(s,principal,'RECOVERY_SCOPE',scope);
 const closure={schema_version:B4,principal,objective:s.i.objective,mandatory:[{obligation:s.i.obligation,resolution:null,intent:s.i.intent}],criteria:[{criterion_id:'expected-source-effect',intent:s.i.intent}],authority_domain:s.i.authority_domain,privacy_purpose:s.i.privacy.purpose,temporal:time(),evidence_refs:['source:closure-criteria']};await appendProof(s,s.i.objective,'CLOSURE',closure);await appendProof(s,s.i.obligation,'OBLIGATION',{schema_version:B4,principal,objective:s.i.objective,obligation:s.i.obligation,mandatory:true,intent:s.i.intent,resolution:null,temporal:time(),evidence_refs:['source:mandatory-membership']});
 return {...s,release,source,verifier,recovery,scope,closure,setObservation:(o:Readback)=>{observation=o;},scans:()=>scans};
}
export const verifyInput=(s:Awaited<ReturnType<typeof prepared>>,name='verification:one')=>({attempt:s.a,verification:identity('VERIFICATION',name),prediction_ref:null});
export const closeInput=(s:Awaited<ReturnType<typeof prepared>>)=>({schema_version:B4,reconciliation:'reconciliation:one',principal,objective:s.i.objective,expected_version:1,contract_version:1});
export async function retryPolicy(s:Awaited<ReturnType<typeof prepared>>,compensation:any=null){await appendProof(s,s.i.intent,'RETRY',{schema_version:B4,intent:s.i.intent,operation_digest:s.i.operation_digest,max_retries:1,proof_valid_until:T3,compensation_attempt:compensation,temporal:time(),evidence_refs:['source:retry-policy']});}
export async function checkpointQualification(s:Awaited<ReturnType<typeof prepared>>,payload:unknown={step:'bounded-recovery'}){await appendProof(s,s.i.work_episode,'CHECKPOINT:step:one',{schema_version:B4,workflow:s.i.work_episode,step_id:'step:one',payload_digest:digest(payload),effect_class:'ZERO_EFFECT',replay_class:'ZERO_EFFECT_SAFE',temporal:time(),evidence_refs:['source:checkpoint-qualified']});return {schema_version:B4,checkpoint_id:'checkpoint:one',principal,workflow:s.i.work_episode,step_id:'step:one',payload,qualification_version:1,continuation:s.c,effect_class:'ZERO_EFFECT',replay_class:'ZERO_EFFECT_SAFE'};}
