import test from 'node:test';import assert from 'node:assert/strict';
import {prepared,verifyInput,closeInput,principal,T2,service,readback,checkpointQualification} from './fixtures.ts';
import {runVerifiedCircuit} from '../../src/runtime/iris-workflow.ts';
import {verifyFixtureEffect} from '../../src/tools/verification.ts';
import {mayBlindRetry} from '../../src/domain/effect-verification.ts';
import {fixtureIntent} from '../helpers.ts';
import {VerificationService} from '../../src/recovery/service.ts';
import {deferred} from '../enforcement/fixtures.ts';
import {identity} from '../../src/semantic-kernel/identity.ts';
import {identityRow,command} from '../canonical-repository/fixtures.ts';
for(const mode of ['MEMORY','SQL'] as const){
 test(`${mode} consequential runtime circuit shares release/verifier/closure owner and never infers closure`,async()=>{const s=await prepared(mode);try{const result=await runVerifiedCircuit(s.release.service,s.verifier,s.release.request);assert.equal(result.status,'EFFECT_VERIFIED_CLOSURE_NOT_ADJUDICATED');assert.equal((await s.recovery.reconstruct(principal,T2)).recovery.roots[0].lifecycle.state,'NONTERMINAL');assert.equal(s.release.calls(),1);}finally{await s.close();}});
 test(`${mode} canonical declared effect cannot replace qualified B4 source proof`,async()=>{const s=await prepared(mode);try{await s.verifier.verify(verifyInput(s));const wire=JSON.parse(await s.repo.exportSnapshot()),original=wire.canonical.commands.find((c:any)=>c.value.object_type==='EFFECT').value,row=structuredClone(original),event={event_id:'effect:foreign-correction',intent:s.i.intent,occurrence:s.i.occurrence,operation_digest:s.i.operation_digest,expected_version:1,next_disposition:'NO_EFFECT_VERIFIED',kind:'CORRECTION',proof:'POSITIVE_ABSENCE',evidence_refs:['source:declaration-only'],at:T2};row.version=2;row.event_ref=event.event_id;row.payload={...row.payload,version:2,disposition:'NO_EFFECT_VERIFIED',last_event_ref:event.event_id,proof:'POSITIVE_ABSENCE',evidence_refs:event.evidence_refs};await s.repo.canonical.append({schema_version:'IRIS_B2_V1',value:row,expected_version:1,transition:event});await assert.rejects(()=>s.recovery.reconstruct(principal,T2),/EFFECT_PROOF_DRIFT/);await assert.rejects(()=>s.recovery.reconcileClosure(closeInput(s)),/EFFECT_PROOF_DRIFT/);}finally{await s.close();}});
 test(`${mode} source scan throw is no absence proof and does not mutate enforcement`,async()=>{const s=await prepared(mode,'SUBMITTING');try{s.source.scan=async()=>{throw Error('READBACK_UNAVAILABLE');};const before=await s.repo.exportSnapshot();await assert.rejects(()=>s.verifier.verify(verifyInput(s)),/READBACK_UNAVAILABLE/);assert.equal(await s.repo.exportSnapshot(),before);assert.equal((await s.repo.getAttempt(s.a)).state,'SUBMITTING');assert.equal(s.release.calls(),0);}finally{await s.close();}});
 test(`${mode} scan configuration drift across await cannot produce proof`,async()=>{const s=await prepared(mode);try{const gate=deferred<void>(),entered=deferred<void>();s.source.scan=async()=>{entered.resolve();await gate.promise;return readback(s);};const pending=s.verifier.verify(verifyInput(s));await entered.promise;s.source.binding.configuration_digest='f'.repeat(64);const before=await s.repo.exportSnapshot();gate.resolve();await assert.rejects(()=>pending,/CONFIGURATION_CHANGED/);assert.equal(await s.repo.exportSnapshot(),before);}finally{await s.close();}});
 test(`${mode} checkpoint resume rechecks its whole snapshot after async Current lookup`,async()=>{const s=await prepared(mode);try{await s.verifier.verify(verifyInput(s));const input=await checkpointQualification(s);await s.recovery.qualifyCheckpoint(input);const original=s.repo.canonical.current.bind(s.repo.canonical),gate=deferred<void>(),entered=deferred<void>();s.repo.canonical.current=async(q:any)=>{const result=await original(q);if(q.predicate?.includes('CHECKPOINT:')){entered.resolve();await gate.promise;}return result;};const pending=s.recovery.resume({checkpoint_id:input.checkpoint_id,principal,workflow:input.workflow,step_id:input.step_id,payload:input.payload,continuation:s.c,as_of:T2});await entered.promise;await s.repo.canonical.append(command(identityRow(identity('INTENT','racing:Current'))));gate.resolve();await assert.rejects(()=>pending,/RESUME_STATE_CHANGED/);}finally{await s.close();}});
}
test('legacy fixture equality/inequality and retry labels cannot manufacture source verification',()=>{const i=fixtureIntent(),receipt:any={receipt_id:'receipt:legacy'};for(const actual of [{same:true},{wrong:true}])assert.equal(verifyFixtureEffect(i,receipt,actual,{same:true}).disposition,'UNKNOWN');for(const d of ['VERIFIED_EFFECT','VERIFIED_NO_EFFECT','UNKNOWN','CONFLICT','AMBIGUOUS_EFFECT'] as const)assert.equal(mayBlindRetry(d),false);});
