import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';
import {prepared,verifyInput,checkpointQualification,principal,T0,T1,T2,T3,readback,appendProof,sourceDoc,sourceId} from './fixtures.ts';
import {claim,successor,currentDoc,authorityDoc} from '../enforcement/fixtures.ts';
import {command,identityRow} from '../canonical-repository/fixtures.ts';
import {identity} from '../../src/semantic-kernel/identity.ts';
import {MemoryEnforcementRepository,PostgresEnforcementRepository} from '../../src/enforcement/backends.ts';
import {RecoveryService,VerificationService} from '../../src/recovery/service.ts';
import {engine} from '../canonical-repository/sql-fixture.ts';
for(const from of ['MEMORY','SQL'] as const)for(const to of ['MEMORY','SQL'] as const)test(`${from} -> fresh ${to}: B4 interleaving, proof materialization, historical cuts, successor, revocation and canonical tail`,async()=>{const s=await prepared(from,'AMBIGUOUS_SUBMISSION'),dir=mkdtempSync(join(tmpdir(),'iris-b4-')),path=join(dir,to==='SQL'?'db':'snapshot.json');let e:any=null;try{
 await s.verifier.verify(verifyInput(s));await s.recovery.qualifyCheckpoint(await checkpointQualification(s));const next=claim(successor,2);await s.repo.command({kind:'TRANSFER_CONTINUATION',value:{expected:s.c,successor:next}});s.setNow(T3);await s.repo.canonical.append(currentDoc({...authorityDoc(),permission:'DENY'},2,T3));await s.repo.command({kind:'REVOKE',value:{principal,domain:s.i.authority_domain,expected_generation:1,evidence_refs:['source:revoked']}});await s.repo.canonical.append(command(identityRow(identity('INTENT','canonical:tail'))));
 const wire=await s.repo.exportSnapshot(),original=JSON.parse(wire);const effect=original.events.find((e:any)=>e.command.kind==='VERIFY_EFFECT');assert.equal(original.canonical.commands[effect.canonical_count].value.object_type,'EFFECT');assert.ok(original.events.some((e:any,n:number)=>n>0&&e.canonical_count===original.events[n-1].canonical_count));assert.ok(original.events.at(-1).canonical_count<original.canonical.commands.length);
 e=to==='SQL'?await engine(undefined,path):null;const copy=e?new PostgresEnforcementRepository(e.executor,()=>T3):new MemoryEnforcementRepository(()=>T3);await copy.importSnapshot(wire);assert.equal(await copy.exportSnapshot(),wire);assert.deepEqual(await copy.inspect(),await s.repo.inspect());const cuts=[T0,T1,T2,T3];for(const at of cuts)assert.deepEqual(await copy.reconstruct(principal,at),await s.repo.reconstruct(principal,at));for(const at of [T2,T3])assert.deepEqual(await copy.recoverySnapshot(principal,at),await s.repo.recoverySnapshot(principal,at));
 const expected=await Promise.all(cuts.map(at=>s.repo.reconstruct(principal,at))),expectedRecovery=await Promise.all([T2,T3].map(at=>s.repo.recoverySnapshot(principal,at)));if(to==='MEMORY')writeFileSync(path,wire);await e?.db.close();e=null;const cutsFile=join(dir,'cuts.json');writeFileSync(cutsFile,JSON.stringify(cuts));const child=spawnSync(process.execPath,['--experimental-strip-types',new URL('./cold-reader.ts',import.meta.url).pathname,to,path,cutsFile],{encoding:'utf8',timeout:60000});assert.equal(child.status,0,child.stderr);const cold=JSON.parse(child.stdout);assert.equal(cold.wire,wire);assert.deepEqual(cold.cuts,expected);assert.deepEqual(cold.recovery,expectedRecovery);
 // A restored repository must support further canonical and enforcement writes.
 const db=to==='SQL'?await engine():null;try{const continued=db?new PostgresEnforcementRepository(db.executor,()=>T3):new MemoryEnforcementRepository(()=>T3);await continued.importSnapshot(wire);await continued.canonical.append(command(identityRow(identity('INTENT','after:restoration'))));await continued.command({kind:'TRANSFER_CONTINUATION',value:{expected:next,successor:claim(s.c.owner_incarnation,3)}});assert.equal((await continued.inspect()).claims[0].generation,3);}finally{await db?.db.close();}
 for(const mutation of ['result','capture','missing-materialization','prefix-before-materialization'] as const){const bad=JSON.parse(wire),ev=bad.events.find((e:any)=>e.command.kind==='VERIFY_EFFECT');if(mutation==='result')ev.result.proof.disposition='NO_EFFECT_VERIFIED';if(mutation==='capture')ev.canonical_count++;if(mutation==='missing-materialization'){bad.canonical.commands.splice(ev.canonical_count,1);bad.canonical.records=bad.canonical.commands.map((c:any)=>c.value);}if(mutation==='prefix-before-materialization')bad.events[bad.events.indexOf(ev)+1].canonical_count=ev.canonical_count;const empty=new MemoryEnforcementRepository(()=>T3),before=await empty.exportSnapshot();await assert.rejects(()=>empty.importSnapshot(JSON.stringify(bad)));assert.equal(await empty.exportSnapshot(),before);}
 }finally{await e?.db.close();await s.close();rmSync(dir,{recursive:true,force:true});}});
test('SQL effect proof and canonical materialization rollback together on failed insert',async()=>{const s=await prepared('SQL');try{let fail=true;const original=s.e!.executor,repo=new PostgresEnforcementRepository({query:original.query.bind(original),transaction:work=>original.transaction(tx=>work({query:async(sql,args)=>{if(fail&&sql.startsWith('insert into iris_b2_journal'))throw Error('B4_MATERIALIZATION_ROLLBACK_PROBE');return tx.query(sql,args);}}))},()=>T2),verifier=new VerificationService(repo,s.source,()=>T2),before=await repo.exportSnapshot();await assert.rejects(()=>verifier.verify(verifyInput(s)),/ROLLBACK_PROBE/);assert.equal(await repo.exportSnapshot(),before);fail=false;await verifier.verify(verifyInput(s));assert.equal((await repo.inspect()).effects.length,1);}finally{await s.close();}});
for(const mode of ['MEMORY','SQL'] as const)test(`${mode} pending or unknown dispatch finality cannot prove positive absence or authorize retry`,async()=>{const s=await prepared(mode,'SUBMITTING');try{for(const [n,finality] of ['PENDING','UNKNOWN'].entries()){const o=readback(s,[],T2,n+1);o.submission_finality=finality as any;s.setObservation(o);const proof=await s.verifier.verify(verifyInput(s,'verification:pending:'+n));assert.equal(proof.disposition,'UNKNOWN');await assert.rejects(async()=>s.recovery.authorizeRetry({schema_version:'IRIS_B4_V1',attempt:s.a,expected_attempt_version:(await s.repo.getAttempt(s.a)).version,verification:proof.verification,policy_version:1,compensation_attempt:null}),/POSITIVE_ABSENCE/);assert.equal(s.release.calls(),0);}}finally{await s.close();}});
