import test from 'node:test';import assert from 'node:assert/strict';
import {prepared,sourceDoc,sourceId,appendProof,verifyInput,principal,T2,T3,closeInput} from './fixtures.ts';
import {value,command} from '../canonical-repository/fixtures.ts';
import {authorityDoc,currentDoc,time} from '../enforcement/fixtures.ts';
import {B4,predicate} from '../../src/recovery/contracts.ts';
for(const mode of ['MEMORY','SQL'] as const){
 for(const coordinate of ['operation','effect-class','scope','privacy-purpose','no-observation','review-due','expired','unqualified','unknown-class','unknown-contract'] as const)test(`${mode} source qualification rejects ${coordinate} before any probe`,async()=>{const s=await prepared(mode);try{const q:any=sourceDoc(s);if(coordinate==='operation')q.operation='foreign';if(coordinate==='effect-class')q.effect_class='foreign';if(coordinate==='scope')q.scope_refs=['foreign'];if(coordinate==='privacy-purpose')q.privacy.purpose='foreign';if(coordinate==='no-observation')delete q.temporal.observed_at;if(coordinate==='review-due')q.temporal.requalification_at=T2;if(coordinate==='expired')q.temporal.valid_until=T2;if(coordinate==='unqualified')q.status='CANDIDATE';if(coordinate==='unknown-class')q.source_class='UNKNOWN';if(coordinate==='unknown-contract')q.verification_contract='provider-success';await appendProof(s,principal,'SOURCE:'+sourceId,q,2,T2);await assert.rejects(()=>s.verifier.verify(verifyInput(s)));assert.equal(s.scans(),0);}finally{await s.close();}});
 test(`${mode} Current relevance UNKNOWN is no private-read permission`,async()=>{const s=await prepared(mode);try{const c=currentDoc(authorityDoc(),2,T2);(c.value.payload as any).epistemic.applicability_state='UNKNOWN';await s.repo.canonical.append(c);await assert.rejects(()=>s.verifier.verify(verifyInput(s)),/PRIVACY_UNKNOWN/);assert.equal(s.scans(),0);await assert.rejects(()=>s.recovery.reconstruct(principal,T2),/AUTHORITY_UNKNOWN/);}finally{await s.close();}});
}
for(const mode of ['MEMORY','SQL'] as const)test(`${mode} unknown required-root semantics survive projection and block recovery admission`,async()=>{const s=await prepared(mode);try{await s.verifier.verify(verifyInput(s));const row=value('EPISTEMIC',{knowledge_state:'UNKNOWN',applicability_state:'UNKNOWN',freshness_state:'UNKNOWN',coverage_state:'UNKNOWN',as_of:T2,evidence_refs:['source:uncertainty'],invalidators:[]},s.i.objective,'epistemic:objective');row.temporal=time(T2);await s.repo.canonical.append(command(row));const r=await s.recovery.reconstruct(principal,T2);assert.equal(r.recovery.admission,'HOLD_CANONICAL_REQUALIFICATION_REQUIRED');assert.equal(r.recovery.dimensions.coverage,'HOLD');await assert.rejects(()=>s.recovery.reconcileClosure(closeInput(s)),/CANONICAL_REQUALIFICATION_REQUIRED/);assert.ok(r.recovery.semantic_holds.includes('CANONICAL_EPISTEMIC_HOLD:epistemic:objective'));const p=await s.recovery.project({schema_version:B4,principal,run:{kind:'PROJECTION_RUN',id:'run:unknown'},scope_version:1}) as any;assert.equal(p.proof.data.completeness,'INCOMPLETE');assert.equal(p.proof.data.output.roots[0].canonical_facts.find((f:any)=>f.object_type==='EPISTEMIC').payload.knowledge_state,'UNKNOWN');assert.equal(r.recovery.continuity_ON,false);}finally{await s.close();}});
