import test from 'node:test';import assert from 'node:assert/strict';
import {setup,authorityDoc,currentDoc,service,intent,redigest,claim,principal,T0,T1,T2,end,worker,successor} from './fixtures.ts';
import {INTENT_FIELDS,decodeIntent,digest,validateAuthority,authorityPredicate} from '../../src/enforcement/contracts.ts';
import {SCHEMA_VERSION} from '../../src/domain/canonical.ts';
const mutations:[string,(doc:any)=>void][]=[];
const base=authorityDoc();
for(const key of Object.keys(base.binding))mutations.push(['binding.'+key,d=>{const v=d.binding[key];d.binding[key]=typeof v==='string'?'foreign':typeof v==='number'?v+1:Array.isArray(v)?['foreign']:v===null?'foreign':{...v,id:'foreign',currency:'FOREIGN'};}]);
for(const key of ['permission','worker_status'])for(const v of ['DENY','UNKNOWN'])mutations.push([key+':'+v,d=>{d[key]=key==='worker_status'?(v==='DENY'?'RETIRED':'UNKNOWN'):v;}]);
for(const key of ['policy_id','privacy_policy_id'])mutations.push([key,d=>{d[key]='foreign';}]);
for(const key of ['latest_generation','policy_version','privacy_policy_version'])mutations.push([key,d=>{d[key]++;}]);
for(const key of ['qualification_id','configuration_digest','role','capability_id','tool_id','status'])mutations.push(['qualification.'+key,d=>{d.qualification[key]=key==='configuration_digest'?digest('foreign'):key==='status'?'UNKNOWN':'foreign';}]);
for(const key of ['lease_id','state','generation'])mutations.push(['lease.'+key,d=>{d.lease[key]=key==='generation'?2:key==='state'?'REVOKED':'foreign';}]);
for(const key of ['retain','use','disclose','minimum_necessary'])for(const v of ['DENY','UNKNOWN'])mutations.push(['privacy_permission.'+key+':'+v,d=>{d.privacy_permission[key]=v;}]);
for(const key of ['temporal','worker_temporal','lease.temporal','qualification.temporal','privacy_permission.temporal','delegation.0.temporal'])for(const variant of ['expired','future','future_recorded','future_observed','revoked','superseded','unbounded','unobserved','future_occurrence'])mutations.push([key+':'+variant,d=>{
 const parts=key.split('.');let t=d;for(const p of parts)t=t[p];if(variant==='expired')t.valid_until=T1;if(variant==='future')t.effective_from=T2;if(variant==='future_recorded')t.recorded_at=T2;if(variant==='future_observed')t.observed_at=T2;if(variant==='revoked')t.revoked_at=T1;if(variant==='superseded')t.superseded_at=T1;if(variant==='unbounded')delete t.valid_until;if(variant==='unobserved')delete t.observed_at;if(variant==='future_occurrence')t.occurred_at=T2;
}]);
mutations.push(['release_attempt',d=>{d.release_attempt.id='foreign';}],['delegation.missing',d=>{d.delegation=[];}],['delegation.foreign_from',d=>{d.delegation[0].from.id='foreign';}],['delegation.foreign_to',d=>{d.delegation[0].to.id='foreign';}],['delegation.deny',d=>{d.delegation[0].permission='DENY';}],['delegation.old_generation',d=>{d.delegation[0].generation=2;}],['limits.currency',d=>{d.limits.currency='FOREIGN';}],['limits.units',d=>{d.limits.max_resource_units=0;}],['qualification.review_due',d=>{d.qualification.temporal.requalification_at=T1;}],['grant.future_issuance',d=>{d.issued_at=T2;}],['lease.future_issuance',d=>{d.lease.issued_at=T2;}]);
for(const mode of ['MEMORY','SQL'] as const)test(`${mode} total A3 independent field matrix`,async t=>{
 const s=await setup(mode,{issue:false});let revision=1;
 try{
  for(const [name,mutate] of mutations)await t.test(name,async()=>{const d=structuredClone(base);mutate(d);await s.repo.canonical.append(currentDoc(d,++revision));const before=await s.repo.exportSnapshot();await assert.rejects(()=>s.repo.command({kind:'ISSUE_LEASE',value:{intent:s.i,attempt:s.a,fence:s.c}}));assert.equal(await s.repo.exportSnapshot(),before);});
  await s.repo.canonical.append(currentDoc(base,++revision));const result:any=await s.repo.command({kind:'ISSUE_LEASE',value:{intent:s.i,attempt:s.a,fence:s.c}});assert.equal(result.authority.as_of,T1);
 }finally{await s.close();}
});
for(const key of INTENT_FIELDS)test(`strict immutable intent missing/NULL/unknown: ${key}`,()=>{
 const i:any=intent();const missing={...i};delete missing[key];assert.throws(()=>decodeIntent(missing));assert.throws(()=>decodeIntent({...i,[key]:null}));assert.throws(()=>decodeIntent({...i,extra:true}));
});
test('changed semantics with same intent ID must update digest but still cannot alter persisted binding',async()=>{const s=await setup();const f=service(s);await s.repo.command({kind:'PREPARE',value:{intent:s.i,attempt:s.a,fence:s.c}});const changed=redigest({...s.i,arguments:{changed:true}});const before=await s.repo.exportSnapshot();await assert.rejects(()=>f.service.release({...f.request,intent:changed}),/IDENTITY_DRIFT/);assert.equal(await s.repo.exportSnapshot(),before);assert.equal(f.calls(),0);});
test('minimum necessary declaration cannot substitute a different argument payload',async()=>{const i=redigest({...intent(),privacy:{...intent().privacy,minimum_necessary_digest:digest('foreign')}});const s=await setup('MEMORY',{i,issue:false});await assert.rejects(()=>s.repo.command({kind:'ISSUE_LEASE',value:{intent:i,attempt:s.a,fence:s.c}}),/DISCLOSURE_PAYLOAD/);});
test('retained executor possession cannot stand for a replaced actor',async()=>{const s=await setup();const f=service(s,undefined,{principal,grantee:worker,incarnation:successor,configuration_digest:s.i.configuration_digest});await assert.rejects(()=>f.service.release(f.request),/ACTOR_BINDING/);assert.equal(f.calls(),0);});
for(const coordinate of ['knowledge_state','applicability_state','freshness_state','coverage_state'])test(`Current ${coordinate} UNKNOWN cannot become authority`,async()=>{const s=await setup('MEMORY',{issue:false});const row=currentDoc(base,2);(row.value.payload as any).epistemic[coordinate]='UNKNOWN';await s.repo.canonical.append(row);await assert.rejects(()=>s.repo.command({kind:'ISSUE_LEASE',value:{intent:s.i,attempt:s.a,fence:s.c}}),/EPISTEMIC/);});
test('public snapshot object is not a release permission',async()=>{const s=await setup();const current=await s.repo.canonical.current({schema_version:SCHEMA_VERSION,principal,subject:principal,predicate:authorityPredicate(s.i.authority_domain),as_of:T1});const snapshot=validateAuthority(current,s.i,s.a,s.c,T1,0);assert.ok(Object.isFrozen(snapshot));assert.throws(()=>{(snapshot as any).authority.permission='ALLOW';});assert.equal((await s.repo.inspect()).attempts.length,0);});
for(const mode of ['MEMORY','SQL'] as const)test(`${mode} actual bounded value denial survives matching keys`,async()=>{const i=intent({value:{currency:'USD',amount_minor:100}}),doc=authorityDoc(i);doc.limits={currency:'USD',max_value_minor:99,max_resource_units:1,max_cost_minor:0};const s=await setup(mode,{i,doc,issue:false});try{await assert.rejects(()=>s.repo.command({kind:'ISSUE_LEASE',value:{intent:i,attempt:s.a,fence:s.c}}),/VALUE_RESOURCE_DENIED/);}finally{await s.close();}});
for(const mode of ['MEMORY','SQL'] as const)test(`${mode} delegated denial cannot be authorized by matching digest`,async()=>{const doc=authorityDoc();doc.delegation[0]!.permission='DENY';const i=intent({delegation_digest:digest(doc.delegation)});doc.binding={...doc.binding,...(await import('../../src/enforcement/contracts.ts')).intentBinding(i)};const s=await setup(mode,{i,doc,issue:false});try{await assert.rejects(()=>s.repo.command({kind:'ISSUE_LEASE',value:{intent:i,attempt:s.a,fence:s.c}}),/DELEGATION_INVALID/);}finally{await s.close();}});
