import {MemoryEnforcementRepository,PostgresEnforcementRepository} from '../../src/enforcement/backends.ts';
import {ReleaseService,type ConsequentialTransport,type EnforcementRepository,type SubmissionReceipt} from '../../src/enforcement/repository.ts';
import {decodeIntent,intentBinding,digest,authorityPredicate,ENFORCEMENT_SCHEMA,type AuthorityDocument,type ReleaseIntent} from '../../src/enforcement/contracts.ts';
import {identity,type Identity} from '../../src/semantic-kernel/identity.ts';
import {command,value,identityRow,reference,principal,T0,T1,T2,T3} from '../canonical-repository/fixtures.ts';
import {engine} from '../canonical-repository/sql-fixture.ts';
export {principal,T0,T1,T2,T3};
export const end='2027-01-01T00:00:00.000Z';
export const sponsor=identity('PRINCIPAL','sponsor'),worker=identity('WORKER','worker'),successor=identity('WORKER','successor'),recipient=identity('PRINCIPAL','recipient');
export function time(at=T0){return {recorded_at:at,effective_from:at,observed_at:at,valid_until:end};}
export function claim(owner=worker,generation=1){return {claim:identity('CONTINUATION','claim:'+generation),principal,causal_episode:identity('CAUSAL_OCCURRENCE','episode:cause'),owner_incarnation:owner,generation,fence_token:'opaque-fence:'+generation,temporal:time(),admission_evidence_refs:['source:continuation-admission']};}
export function delegation(owner=worker){return [{from:sponsor,to:owner,generation:1,permission:'ALLOW' as const,temporal:time(),evidence_refs:['source:delegation']}];}
export const attempt=identity('RELEASE_ATTEMPT','attempt:1');
export function intent(overrides:Partial<ReleaseIntent>={}):ReleaseIntent{
 const argumentsValue={target:'fixture',value:'requested'};const i:any={schema_version:ENFORCEMENT_SCHEMA,intent:identity('INTENT','intent:1'),principal,sponsor,grantee:worker,incarnation:worker,objective:identity('OBJECTIVE','object:one'),obligation:identity('OBLIGATION','obligation:one'),work_episode:identity('WORK_EPISODE','episode:work'),causal_episode:identity('CAUSAL_OCCURRENCE','episode:cause'),occurrence:identity('CAUSAL_OCCURRENCE','occurrence:one'),authority_domain:'domain:one',authority_generation:1,authority_policy_id:'policy:authority',authority_policy_version:1,privacy_policy_id:'policy:privacy',privacy_policy_version:1,delegation_digest:digest(delegation()),lease_id:'lease:one',purpose:'bounded-fixture',object_refs:['fixture:object'],resource_refs:['fixture:resource'],capability_id:'capability:one',qualification_id:'qualification:one',configuration_digest:digest('configuration:one'),role:'bounded-fixture',tool_id:'fixture.action',operation:'set-fixture',arguments:argumentsValue,expected_effect:{value:'requested'},effect_class:'FIXTURE_WRITE',consequence_class:'BOUNDED',value:{currency:'NONE',amount_minor:0},resources:{units:1,cost_minor:0},privacy:{classification:'FIXTURE_NON_SENSITIVE',recipient,purpose:'bounded-fixture',retention_until:end,minimum_necessary_digest:digest(argumentsValue),egress:'LOCAL_FIXTURE_ONLY',reuse:'THIS_PURPOSE_ONLY',transfer:'NO_TRANSFER'},retry_class:'IDEMPOTENT_BY_KEY',idempotency_key:'key:one',temporal:time(),evidence_refs:['source:intent'],provenance_refs:['provenance:intent'],...overrides};return redigest(i);
}
export function redigest(i:any):ReleaseIntent{const {operation_digest,...rest}=i;return decodeIntent({...rest,operation_digest:digest(rest)}) as ReleaseIntent;}
export function authorityDoc(i=intent(),a=attempt):AuthorityDocument{return {schema_version:'IRIS_B3_AUTHORITY_V1',issued_at:T0,permission:'ALLOW',binding:intentBinding(i),release_attempt:a,policy_id:i.authority_policy_id,policy_version:i.authority_policy_version,privacy_policy_id:i.privacy_policy_id,privacy_policy_version:i.privacy_policy_version,latest_generation:i.authority_generation,worker_status:'ACTIVE',worker_temporal:time(),qualification:{qualification_id:i.qualification_id,configuration_digest:i.configuration_digest,role:i.role,capability_id:i.capability_id,tool_id:i.tool_id,status:'QUALIFIED',temporal:time(),evidence_refs:['source:qualification']},lease:{lease_id:i.lease_id,issued_at:T0,state:'ACTIVE',generation:i.authority_generation,temporal:time(),evidence_refs:['source:lease']},delegation:delegation(i.grantee),privacy_permission:{retain:'ALLOW',use:'ALLOW',disclose:'ALLOW',minimum_necessary:'ALLOW',temporal:time(),evidence_refs:['source:privacy']},limits:{currency:'NONE',max_value_minor:0,max_resource_units:1,max_cost_minor:0},temporal:time(),evidence_refs:['source:authorization'],provenance_refs:['provenance:authorization']};}
export function currentDoc(doc:unknown,revision=1,at=T0){const row=value('CURRENT',{subject:principal,predicate:authorityPredicate('domain:one'),value:doc,epistemic:{knowledge_state:'KNOWN',applicability_state:'APPLICABLE',freshness_state:'CURRENT_AS_OF',coverage_state:'COMPLETE_FOR_DECLARED_SCOPE',as_of:at,evidence_refs:['source:authority'],invalidators:[]}},principal,'current:authority');row.version=revision;row.temporal=time(at);return command(row);}
export async function setup(mode:'MEMORY'|'SQL'='MEMORY',opts:{issue?:boolean;doc?:unknown;i?:ReleaseIntent;a?:Identity;dataDir?:string}={}){
 let now=T1;const clock=()=>now,e=mode==='SQL'?await engine(undefined,opts.dataDir):null;
 const repo:EnforcementRepository=e?new PostgresEnforcementRepository(e.executor,clock):new MemoryEnforcementRepository(clock),i=opts.i??intent(),a=opts.a??attempt;
 const refs=[principal,sponsor,worker,successor,recipient,i.intent,i.objective,i.obligation,i.work_episode,i.causal_episode,i.occurrence,claim().claim];
 for(const ref of refs){const row=identityRow(ref);row.temporal=time();await repo.canonical.append(command(row));}
 const c=claim(),row=value('CONTINUATION',c,c.claim);row.temporal=c.temporal;row.references=[reference(c.causal_episode),reference(c.owner_incarnation)];await repo.canonical.append(command(row));
 await repo.canonical.append(currentDoc(opts.doc??authorityDoc(i,a)));
 await repo.command({kind:'ADMIT_CONTINUATION',value:{claim:c}});
 if(opts.issue!==false)await repo.command({kind:'ISSUE_LEASE',value:{intent:i,attempt:a,fence:c}});
 return {repo,i,a,c,e,setNow:(t:string)=>{now=t;},close:async()=>{await e?.db.close();}};
}
export function receipt(i:ReleaseIntent,a:Identity):SubmissionReceipt{return {receipt:identity('RECEIPT','receipt:one'),attempt:a,intent:i.intent,occurrence:i.occurrence,operation_digest:i.operation_digest,provider_call_id:'fixture-call:1',evidence_refs:['source:provider-accepted'],status:'SUBMISSION_KNOWN'};}
export function service(s:Awaited<ReturnType<typeof setup>>,transport?:Partial<ConsequentialTransport>,actor= {principal:s.i.principal,grantee:s.i.grantee,incarnation:s.i.incarnation,configuration_digest:s.i.configuration_digest}){let calls=0;const t:ConsequentialTransport={binding:{tool_id:s.i.tool_id,configuration_digest:s.i.configuration_digest,capability_id:s.i.capability_id,qualification_id:s.i.qualification_id},preflight:async()=>({ready:true}),submit:async(i,a)=>{calls++;return receipt(i,a);},...transport};return {service:new ReleaseService(s.repo,t,actor),calls:()=>calls,request:{intent:s.i,attempt:s.a,fence:s.c,retry:false}};}
export function deferred<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};}
