import test from 'node:test';import assert from 'node:assert/strict';
import {setup,service,receipt,principal,T0,T1,T2,claim,successor,redigest,intent,currentDoc,authorityDoc,attempt,worker,delegation} from './fixtures.ts';
import {MemoryEnforcementRepository,PostgresEnforcementRepository} from '../../src/enforcement/backends.ts';
import {ReleaseService,consumeSubmissionPermit,type SubmissionPermit} from '../../src/enforcement/repository.ts';
import {digest} from '../../src/enforcement/contracts.ts';
import {CanonicalActionFixtureAdapter,ActionFixtureAdapter} from '../../src/tools/action-fixture-adapter.ts';
import {releaseAction} from '../../src/runtime/act.ts';
import {runConsequentialCircuit,runBoundedCircuit} from '../../src/runtime/iris-workflow.ts';
import {fixtureIntent} from '../helpers.ts';
import {identity} from '../../src/semantic-kernel/identity.ts';
import {identityRow,command} from '../canonical-repository/fixtures.ts';
for(const mode of ['MEMORY','SQL'] as const){
 test(`${mode} canonical snapshot roundtrip preserves all enforcement state and rejects tampering atomically`,async()=>{const s=await setup(mode),f=service(s);try{await f.service.release(f.request);await s.repo.command({kind:'TRANSFER_CONTINUATION',value:{expected:s.c,successor:claim(successor,2)}});await s.repo.command({kind:'REVOKE',value:{principal,domain:s.i.authority_domain,expected_generation:1,evidence_refs:['source:revoked']}});const wire=await s.repo.exportSnapshot(),copy=new MemoryEnforcementRepository(()=>T1);await copy.importSnapshot(wire);assert.equal(await copy.exportSnapshot(),wire);assert.deepEqual(await copy.reconstruct(principal,T1),await s.repo.reconstruct(principal,T1));for(const mutate of [(v:any)=>{v.events[0].result.generation=22;},(v:any)=>{v.events[0].canonical_digest=digest('foreign');},(v:any)=>{v.events[0].sequence=2;},(v:any)=>{v.events[1].canonical_count=0;},(v:any)=>{v.events[1].at=T0;},(v:any)=>{v.events[0].extra=true;},(v:any)=>{v.events[0].command.kind='UNKNOWN';},(v:any)=>{v.canonical.records[0].principal.id='foreign';}]){const v=JSON.parse(wire);mutate(v);const empty=new MemoryEnforcementRepository(()=>T1),before=await empty.exportSnapshot();await assert.rejects(()=>empty.importSnapshot(JSON.stringify(v)));assert.equal(await empty.exportSnapshot(),before);}const empty=new MemoryEnforcementRepository(()=>T1);await assert.rejects(()=>empty.importSnapshot(wire.replace('"IRIS_B3_V1"','"IRIS_B3_V1","schema_version":"IRIS_B3_V1"')),/DUPLICATE_JSON/);}finally{await s.close();}});
 test(`${mode} repeated invocation is read-only and attempt snapshots immutable`,async()=>{const s=await setup(mode),f=service(s);try{await f.service.release(f.request);const wire=await s.repo.exportSnapshot(),a=await s.repo.getAttempt(s.a);assert.throws(()=>{(a as any).state='PREPARED';});assert.throws(()=>{(a.intent.arguments as any).value='foreign';});await f.service.release(f.request);assert.equal(await s.repo.exportSnapshot(),wire);}finally{await s.close();}});
 test(`${mode} clock rollback rejects new state changes`,async()=>{const s=await setup(mode);try{s.setNow(T0);const before=await s.repo.exportSnapshot();await assert.rejects(()=>s.repo.command({kind:'TRANSFER_CONTINUATION',value:{expected:s.c,successor:claim(successor,2)}}),/TIME_REGRESSION/);assert.equal(await s.repo.exportSnapshot(),before);}finally{await s.close();}});
 test(`${mode} source authority generation cannot regress behind issued lease`,async()=>{const s=await setup(mode);try{const g2=redigest({...s.i,intent:identity('INTENT','generation2'),authority_generation:2,lease_id:'lease:g2',delegation_digest:digest([{...delegation()[0],generation:2}])}),a2=identity('RELEASE_ATTEMPT','attempt:g2');const row=identityRow(g2.intent);await s.repo.canonical.append(command(row));const d=authorityDoc(g2,a2);d.delegation[0]!.generation=2;await s.repo.canonical.append(currentDoc(d,2));await s.repo.command({kind:'ISSUE_LEASE',value:{intent:g2,attempt:a2,fence:s.c}});await s.repo.canonical.append(currentDoc(authorityDoc(),3));await assert.rejects(()=>s.repo.command({kind:'ISSUE_LEASE',value:{intent:s.i,attempt:s.a,fence:s.c}}),/STATE_REGRESSION/);}finally{await s.close();}});
 test(`${mode} a distinct successor may release only with its own validated lease and Current`,async()=>{const s=await setup(mode);try{const next=claim(successor,2);await s.repo.command({kind:'TRANSFER_CONTINUATION',value:{expected:s.c,successor:next}});const i=redigest({...s.i,intent:identity('INTENT','successor:intent'),grantee:successor,incarnation:successor,lease_id:'lease:successor',delegation_digest:digest(delegation(successor))}),a=identity('RELEASE_ATTEMPT','attempt:successor');await s.repo.canonical.append(command(identityRow(i.intent)));await s.repo.canonical.append(currentDoc(authorityDoc(i,a),2));await s.repo.command({kind:'ISSUE_LEASE',value:{intent:i,attempt:a,fence:next}});const f=service({...s,i,a,c:next});assert.equal((await f.service.release(f.request)).state,'RELEASED_SUBMITTED');assert.equal(f.calls(),1);}finally{await s.close();}});
}
test('SQL imported history is atomic on injected mid-insert failure',async()=>{const s=await setup('SQL');try{const wire=await s.repo.exportSnapshot();await s.e!.db.exec('create schema empty_test');await s.e!.db.exec('set search_path to empty_test, public');await s.e!.db.exec('create table iris_b2_journal (like public.iris_b2_journal including all)');await s.e!.db.exec('create table iris_b3_enforcement_journal (like public.iris_b3_enforcement_journal including all)');let n=0;const original=s.e!.executor,repo=new PostgresEnforcementRepository({query:original.query.bind(original),transaction:w=>original.transaction(tx=>w({query:async(sql,args)=>{if(sql.startsWith('insert ')&&++n===3)throw Error('IMPORT_ROLLBACK_PROBE');return tx.query(sql,args);}}))},()=>T1);await assert.rejects(()=>repo.importSnapshot(wire),/IMPORT_ROLLBACK/);assert.equal((await s.e!.db.query('select count(*) as n from empty_test.iris_b2_journal')).rows[0].n,0);assert.equal((await s.e!.db.query('select count(*) as n from empty_test.iris_b3_enforcement_journal')).rows[0].n,0);}finally{await s.close();}});
test('SQL raw journal corruption blocks replay and release; append-only/gap/NULL guards reject',async()=>{const s=await setup('SQL');try{await assert.rejects(()=>s.e!.db.exec('update iris_b3_enforcement_journal set event=event'));await assert.rejects(()=>s.e!.db.exec('delete from iris_b3_enforcement_journal'));await assert.rejects(()=>s.e!.db.exec('truncate iris_b3_enforcement_journal'));const raw=JSON.parse(await s.repo.exportSnapshot()).events[0];for(const mutate of [(v:any)=>{v.sequence=100;},(v:any)=>{v.at=null;},(v:any)=>{v.extra=1;},(v:any)=>{v.command.kind=null;}]){const e=structuredClone(raw);e.sequence=3;mutate(e);await assert.rejects(()=>s.e!.db.query('insert into iris_b3_enforcement_journal(sequence,event) values($1,$2)',[e.sequence,e]));}const poisoned=structuredClone(raw);poisoned.sequence=3;poisoned.command={kind:'COMPLETE',value:{fake:true}};await s.e!.db.query('insert into iris_b3_enforcement_journal(sequence,event) values($1,$2)',[3,poisoned]);const f=service(s);await assert.rejects(()=>f.service.release(f.request));assert.equal(f.calls(),0);}finally{await s.close();}});
test('all live release facades share one owner; fixture adapter rejects forged/replayed permits',async()=>{const s=await setup(),fake=new CanonicalActionFixtureAdapter({tool_id:s.i.tool_id,configuration_digest:s.i.configuration_digest,capability_id:s.i.capability_id,qualification_id:s.i.qualification_id},{before:true}),actor={principal:s.i.principal,grantee:s.i.grantee,incarnation:s.i.incarnation,configuration_digest:s.i.configuration_digest},real=new ReleaseService(s.repo,fake,actor),request={intent:s.i,attempt:s.a,fence:s.c,retry:false};await assert.rejects(()=>fake.submit(s.i,s.a,{dispatch_id:'forged'}),/PERMIT_REQUIRED/);assert.equal(fake.calls.length,0);const results=await Promise.all([releaseAction(real,request),runConsequentialCircuit(real,request)]);assert.equal(fake.calls.length,1);assert.ok(results.some(a=>a.state==='RELEASED_SUBMITTED'));assert.deepEqual(fake.read(),s.i.arguments);const old=new ActionFixtureAdapter({before:true});await assert.rejects(()=>old.execute(fixtureIntent()),/CANONICAL_RELEASE_REQUIRED/);assert.equal(old.calls.length,0);});
test('a consumed/expired process-local permit cannot cause a second fixture dispatch',async()=>{const s=await setup();let saved!:SubmissionPermit;let calls=0;const f=service(s,{submit:async(i,a,p)=>{saved=p;consumeSubmissionPermit(p,i,a);calls++;assert.throws(()=>consumeSubmissionPermit(p,i,a),/PERMIT_REQUIRED/);return receipt(i,a);}});await f.service.release(f.request);assert.throws(()=>consumeSubmissionPermit(saved,s.i,s.a),/PERMIT_REQUIRED/);assert.equal(calls,1);});
test('mismatched transport configuration fails before preflight',async()=>{const s=await setup(),f=service(s,{binding:{tool_id:s.i.tool_id,configuration_digest:digest('wrong'),capability_id:s.i.capability_id,qualification_id:s.i.qualification_id},preflight:async()=>{throw Error('must not call');}});await assert.rejects(()=>f.service.release(f.request),/TRANSPORT_BINDING/);assert.equal(f.calls(),0);assert.equal((await s.repo.inspect()).attempts.length,0);});
