// B4 proof owner; B1 owns identity/time/lifecycle, B2 canonical representation,
// B3 owns release/authority. This module grants no dispatch capability.
import {decodeIdentity,sameIdentity,type Identity} from '../semantic-kernel/identity.ts';
import {instant,decodeTemporal,knownAsOf} from '../semantic-kernel/temporal.ts';
import {demand,record,text,version,evidence,freeze,strings} from '../semantic-kernel/validation.ts';
import {jsonValue,denseArray} from '../domain/json.ts';
import {canonicalJSON,type CanonicalRepository} from '../state/repository.ts';
import {SCHEMA_VERSION,type Reference} from '../domain/canonical.ts';
import {digest,sha,decodeAuthority,authorityPredicate} from '../enforcement/contracts.ts';
import type {ReleaseAttempt} from '../enforcement/repository.ts';
export const B4='IRIS_B4_V1' as const;
export const same=(a:unknown,b:unknown)=>canonicalJSON(a)===canonicalJSON(b);
export const predicate=(kind:string)=>canonicalJSON([B4,text(kind)]);
export function id(input:unknown,kind:Identity['kind']):Identity{const ref=decodeIdentity(input);demand(ref.kind===kind,'B4_IDENTITY_KIND');return ref;}
export function refs(input:unknown){const a=evidence(denseArray(input));demand(new Set(a).size===a.length,'B4_DUPLICATE_REF');return a;}
export function ids(input:unknown,kind?:Identity['kind']){const a=denseArray(input).map(v=>kind?id(v,kind):decodeIdentity(v));demand(new Set(a.map(v=>canonicalJSON(v))).size===a.length,'B4_DUPLICATE_IDENTITY');return a;}
export interface SourceQualification {schema_version:typeof B4;source_id:string;configuration_digest:string;source_class:'QUALIFICATION_FIXTURE'|'LIVE_SOURCE';verification_contract:'OCCURRENCE_VALUE_SCAN_V1';principal:Identity;tool_id:string;operation:string;effect_class:string;scope_refs:string[];status:'QUALIFIED';privacy:{recipient:Identity;purpose:string;retain:'ALLOW';use:'ALLOW';disclose:'ALLOW';egress:string};temporal:ReturnType<typeof decodeTemporal>;evidence_refs:string[]}
export function decodeSourceQualification(input:unknown):Readonly<SourceQualification>{const r=record(input,['schema_version','source_id','configuration_digest','source_class','verification_contract','principal','tool_id','operation','effect_class','scope_refs','status','privacy','temporal','evidence_refs']);demand(r.schema_version===B4&&r.status==='QUALIFIED'&&['QUALIFICATION_FIXTURE','LIVE_SOURCE'].includes(String(r.source_class))&&r.verification_contract==='OCCURRENCE_VALUE_SCAN_V1','B4_SOURCE_NOT_QUALIFIED');const p=record(r.privacy,['recipient','purpose','retain','use','disclose','egress']);demand(p.retain==='ALLOW'&&p.use==='ALLOW'&&p.disclose==='ALLOW','B4_READBACK_PRIVACY_DENIED');return freeze({schema_version:B4,source_id:text(r.source_id),configuration_digest:sha(r.configuration_digest),source_class:r.source_class as SourceQualification['source_class'],verification_contract:'OCCURRENCE_VALUE_SCAN_V1',principal:id(r.principal,'PRINCIPAL'),tool_id:text(r.tool_id),operation:text(r.operation),effect_class:text(r.effect_class),scope_refs:refs(r.scope_refs),status:'QUALIFIED',privacy:{recipient:decodeIdentity(p.recipient),purpose:text(p.purpose),retain:'ALLOW',use:'ALLOW',disclose:'ALLOW',egress:text(p.egress)},temporal:decodeTemporal(r.temporal),evidence_refs:refs(r.evidence_refs)});}
export interface Readback {schema_version:typeof B4;source_id:string;configuration_digest:string;principal:Identity;intent:Identity;occurrence:Identity;operation_digest:string;observed_at:string;readback_version:number;scope_refs:string[];settled_through:string|null;submission_finality:'SETTLED'|'PENDING'|'UNKNOWN';exhaustive:boolean;entries:{entry_id:string;provider_call_id:string;operation_digest:string;occurrence:Identity;value:unknown}[];unavailable_refs:string[];conflict_refs:string[];evidence_refs:string[]}
export function decodeReadback(input:unknown):Readonly<Readback>{const r=record(input,['schema_version','source_id','configuration_digest','principal','intent','occurrence','operation_digest','observed_at','readback_version','scope_refs','settled_through','submission_finality','exhaustive','entries','unavailable_refs','conflict_refs','evidence_refs']);demand(r.schema_version===B4,'B4_SCHEMA_REQUIRED');demand(['SETTLED','PENDING','UNKNOWN'].includes(String(r.submission_finality)),'B4_FINALITY_REQUIRED');demand(typeof r.exhaustive==='boolean','B4_EXHAUSTIVE_COORDINATE');const entries=denseArray(r.entries).map(v=>{const e=record(v,['entry_id','provider_call_id','operation_digest','occurrence','value']);return {entry_id:text(e.entry_id),provider_call_id:text(e.provider_call_id),operation_digest:sha(e.operation_digest),occurrence:id(e.occurrence,'CAUSAL_OCCURRENCE'),value:jsonValue(e.value)};});demand(new Set(entries.map(e=>e.entry_id)).size===entries.length,'B4_DUPLICATE_ENTRY');return freeze({schema_version:B4,source_id:text(r.source_id),configuration_digest:sha(r.configuration_digest),principal:id(r.principal,'PRINCIPAL'),intent:id(r.intent,'INTENT'),occurrence:id(r.occurrence,'CAUSAL_OCCURRENCE'),operation_digest:sha(r.operation_digest),observed_at:instant(r.observed_at),readback_version:version(r.readback_version),scope_refs:refs(r.scope_refs),settled_through:r.settled_through===null?null:instant(r.settled_through),submission_finality:r.submission_finality as Readback['submission_finality'],exhaustive:r.exhaustive,entries,unavailable_refs:strings(denseArray(r.unavailable_refs)),conflict_refs:strings(denseArray(r.conflict_refs)),evidence_refs:refs(r.evidence_refs)});}
export async function currentProof(repo:CanonicalRepository,principal:Identity,subject:Identity,kind:string,at:string){const current=await repo.current({schema_version:SCHEMA_VERSION,principal,subject,predicate:predicate(kind),as_of:at});demand(current.status==='RECORDED_AS_OF'&&current.record,'B4_CURRENT_REQUIRED');const p=current.record.payload as {value:unknown;epistemic:{knowledge_state:string;applicability_state:string;freshness_state:string;coverage_state:string;invalidators:string[]}};demand(p.epistemic.knowledge_state==='KNOWN'&&p.epistemic.applicability_state==='APPLICABLE'&&p.epistemic.freshness_state==='CURRENT_AS_OF'&&p.epistemic.coverage_state==='COMPLETE_FOR_DECLARED_SCOPE'&&p.epistemic.invalidators.length===0,'B4_CURRENT_EPISTEMIC_HOLD');return {record:current.record,value:p.value};}
export async function qualifiedSource(repo:CanonicalRepository,a:ReleaseAttempt,sourceId:string,at:string){const c=await currentProof(repo,a.intent.principal,a.intent.principal,'SOURCE:'+sourceId,at),q=decodeSourceQualification(c.value),i=a.intent;demand(q.source_id===sourceId&&sameIdentity(q.principal,i.principal)&&q.tool_id===i.tool_id&&q.operation===i.operation&&q.effect_class===i.effect_class&&same(q.scope_refs,i.object_refs),'B4_SOURCE_BINDING');demand(sameIdentity(q.privacy.recipient,i.privacy.recipient)&&q.privacy.purpose===i.privacy.purpose&&q.privacy.egress===i.privacy.egress,'B4_SOURCE_PRIVACY_BINDING');demand(q.temporal.valid_until!==undefined&&q.temporal.observed_at!==undefined&&(q.temporal.requalification_at===undefined||Date.parse(q.temporal.requalification_at)>Date.parse(at))&&knownAsOf(q.temporal,at)&&Date.parse(i.privacy.retention_until)>Date.parse(at),'B4_SOURCE_STALE');const authority=await repo.current({schema_version:SCHEMA_VERSION,principal:i.principal,subject:i.principal,predicate:authorityPredicate(i.authority_domain),as_of:at});demand(authority.status==='RECORDED_AS_OF'&&authority.record,'B4_SOURCE_PRIVACY_CURRENT_REQUIRED');const p=authority.record.payload as {value:unknown;epistemic:{knowledge_state:string;applicability_state:string;freshness_state:string;coverage_state:string;invalidators:string[]}};demand(p.epistemic.knowledge_state==='KNOWN'&&p.epistemic.applicability_state==='APPLICABLE'&&p.epistemic.freshness_state==='CURRENT_AS_OF'&&p.epistemic.coverage_state==='COMPLETE_FOR_DECLARED_SCOPE'&&!p.epistemic.invalidators.length,'B4_SOURCE_PRIVACY_UNKNOWN');const privacyDoc=decodeAuthority(p.value);demand(same(privacyDoc.binding.privacy,i.privacy)&&privacyDoc.privacy_permission.retain==='ALLOW'&&privacyDoc.privacy_permission.use==='ALLOW'&&privacyDoc.privacy_permission.disclose==='ALLOW'&&privacyDoc.privacy_permission.minimum_necessary==='ALLOW'&&privacyDoc.privacy_permission.temporal.valid_until!==undefined&&knownAsOf(privacyDoc.privacy_permission.temporal,at),'B4_SOURCE_PRIVACY_CURRENT_DENIED');return {qualification:q,current_record_id:c.record.record_id,current_version:c.record.version,current_digest:digest(c.record)};}
export type VerifiedDisposition='EFFECT_VERIFIED'|'NO_EFFECT_VERIFIED'|'PARTIAL_EFFECT'|'AMBIGUOUS_EFFECT'|'CONFLICTED_EFFECT'|'UNAVAILABLE_READBACK'|'UNKNOWN';
export interface EffectProof {schema_version:typeof B4;verification:Identity;attempt:Identity;attempt_version:number;intent:Identity;occurrence:Identity;operation_digest:string;at:string;qualification:Awaited<ReturnType<typeof qualifiedSource>>;observation:Readonly<Readback>;disposition:VerifiedDisposition;proof:string;evidence_refs:string[];prediction_ref:Reference|null;experience_class:'SYNTHETIC_QUALIFICATION'|'EMPIRICAL_SOURCE_READBACK';authority:'NONE'}
export function classifyReadback(a:ReleaseAttempt,q:SourceQualification,o:Readonly<Readback>,at:string):{disposition:VerifiedDisposition;proof:string}{
 const i=a.intent;demand(o.source_id===q.source_id&&o.configuration_digest===q.configuration_digest&&sameIdentity(o.principal,i.principal)&&sameIdentity(o.intent,i.intent)&&sameIdentity(o.occurrence,i.occurrence)&&o.operation_digest===i.operation_digest&&same(o.scope_refs,q.scope_refs),'B4_READBACK_BINDING');demand(Date.parse(o.observed_at)<=Date.parse(at)&&Date.parse(o.observed_at)>=Date.parse(a.updated_at)&&knownAsOf(q.temporal,o.observed_at),'B4_READBACK_CUT');demand(o.settled_through===null||Date.parse(o.settled_through)<=Date.parse(o.observed_at),'B4_FUTURE_SETTLEMENT');
 for(const e of o.entries)demand(e.operation_digest===i.operation_digest&&sameIdentity(e.occurrence,i.occurrence),'B4_CROSS_OCCURRENCE_ENTRY');
 if(o.conflict_refs.length||o.entries.length>1)return {disposition:'CONFLICTED_EFFECT',proof:'CONFLICT'};
 if(o.unavailable_refs.length)return {disposition:'UNAVAILABLE_READBACK',proof:'UNAVAILABLE'};
 if(o.submission_finality!=='SETTLED'||!o.exhaustive||o.settled_through===null||Date.parse(o.settled_through)<Date.parse(at))return {disposition:'UNKNOWN',proof:'NONE'};
 if(!o.entries.length)return {disposition:'NO_EFFECT_VERIFIED',proof:'POSITIVE_ABSENCE'};
 const e=o.entries[0]!;if(a.receipt)demand(e.provider_call_id===a.receipt.provider_call_id,'B4_RECEIPT_READBACK_BINDING');
 if(same(e.value,i.expected_effect))return {disposition:'EFFECT_VERIFIED',proof:'MATCHING_EFFECT'};
 const expected=i.expected_effect,actual=e.value;
 const partial=expected!==null&&actual!==null&&typeof expected==='object'&&typeof actual==='object'&&!Array.isArray(expected)&&!Array.isArray(actual)&&Object.keys(expected).some(k=>Object.hasOwn(actual,k)&&same((expected as Record<string,unknown>)[k],(actual as Record<string,unknown>)[k]));
 return partial?{disposition:'PARTIAL_EFFECT',proof:'PARTIAL_MATCH'}:{disposition:'AMBIGUOUS_EFFECT',proof:'AMBIGUOUS'};
}
export interface ClosureContract {schema_version:typeof B4;principal:Identity;objective:Identity;mandatory:{obligation:Identity;resolution:Identity|null;intent:Identity}[];criteria:{criterion_id:string;intent:Identity}[];authority_domain:string;privacy_purpose:string;temporal:ReturnType<typeof decodeTemporal>;evidence_refs:string[]}
export function decodeClosure(input:unknown):Readonly<ClosureContract>{const r=record(input,['schema_version','principal','objective','mandatory','criteria','authority_domain','privacy_purpose','temporal','evidence_refs']);demand(r.schema_version===B4,'B4_SCHEMA_REQUIRED');const mandatory=denseArray(r.mandatory).map(v=>{const m=record(v,['obligation','resolution','intent']);return {obligation:id(m.obligation,'OBLIGATION'),resolution:m.resolution===null?null:id(m.resolution,'DECISION_REQUIREMENT'),intent:id(m.intent,'INTENT')};}),criteria=denseArray(r.criteria).map(v=>{const c=record(v,['criterion_id','intent']);return {criterion_id:text(c.criterion_id),intent:id(c.intent,'INTENT')};});demand(mandatory.length>0&&criteria.length>0,'B4_EXPLICIT_CLOSURE_CRITERIA');demand(new Set(mandatory.map(m=>canonicalJSON(m.obligation))).size===mandatory.length&&new Set(criteria.map(c=>c.criterion_id)).size===criteria.length,'B4_DUPLICATE_CLOSURE_CRITERION');return freeze({schema_version:B4,principal:id(r.principal,'PRINCIPAL'),objective:id(r.objective,'OBJECTIVE'),mandatory,criteria,authority_domain:text(r.authority_domain),privacy_purpose:text(r.privacy_purpose),temporal:decodeTemporal(r.temporal),evidence_refs:refs(r.evidence_refs)});}
