import {B4,same,predicate,id,ids,refs,currentProof,qualifiedSource,decodeReadback,classifyReadback,decodeClosure,type EffectProof} from './contracts.ts';
import {sameIdentity,type Identity} from '../semantic-kernel/identity.ts';
import {decodeLifecycle,reduceLifecycle,reduceEffect,type EffectState} from '../semantic-kernel/lifecycle.ts';
import {decodeContinuation} from '../semantic-kernel/continuation.ts';
import {decodeTemporal,knownAsOf,instant} from '../semantic-kernel/temporal.ts';
import {demand,record,text,version,freeze,member} from '../semantic-kernel/validation.ts';
import {denseArray,jsonValue} from '../domain/json.ts';
import {SCHEMA_VERSION,decodeReference,sameRepositoryIdentity,type CanonicalRecord,type Reference} from '../domain/canonical.ts';
import {canonicalJSON,type AppendCommand,type CanonicalRepository} from '../state/repository.ts';
import {digest,sha,decodeAuthority,authorityPredicate,type ValidatedAuthoritySnapshot} from '../enforcement/contracts.ts';
import type {State,ReleaseAttempt,EnforcementEvent} from '../enforcement/repository.ts';
export const RECOVERY_COMMANDS=['VERIFY_EFFECT','RECONCILE_CLOSURE','AUTHORIZE_VERIFIED_RETRY','QUALIFY_CHECKPOINT','VERIFY_PROJECTION'] as const;
export const isRecoveryCommand=(kind:string)=>RECOVERY_COMMANDS.includes(kind as typeof RECOVERY_COMMANDS[number]);
export interface RecoveryContext {commands:readonly AppendCommand[];events:readonly EnforcementEvent[]}
export interface RecoveryState {effects:(EffectProof&{request_digest:string})[];closures:ProofResult[];checkpoints:ProofResult[];runs:ProofResult[];retries:{attempt:Identity;verification:Identity;attempt_version:number;expires_at:string;source_version:number;source_record:string;source_digest:string;policy_version:number;policy_digest:string;compensation:Identity|null}[]}
export interface ProofResult {schema_version:typeof B4;kind:string;identity:string;principal:Identity;at:string;data:Record<string,unknown>;authority:'NONE'}
const result=(proof:unknown,materialized:AppendCommand[]=[])=>({proof,materialized});
const findAttempt=(s:State,input:unknown)=>{const ref=id(input,'RELEASE_ATTEMPT'),a=s.attempts.find(a=>sameIdentity(a.attempt,ref));demand(a,'B4_ATTEMPT_MISSING');return a;};
export function latestEffect(s:RecoveryState,a:ReleaseAttempt){return s.effects.filter(e=>sameIdentity(e.attempt,a.attempt)&&e.attempt_version===a.version).at(-1);}
function applicable(t:ReturnType<typeof decodeTemporal>,at:string){demand(t.valid_until!==undefined&&t.observed_at!==undefined&&(t.requalification_at===undefined||Date.parse(t.requalification_at)>Date.parse(at))&&knownAsOf(t,at),'B4_PROOF_STALE');}
function snapshot(c:RecoveryContext){return {canonical_count:c.commands.length,canonical_digest:digest(c.commands),enforcement_count:c.events.length,enforcement_digest:digest(c.events)};}
async function model(repo:CanonicalRepository,principal:Identity,at:string){return repo.reconstruct({schema_version:SCHEMA_VERSION,principal,as_of:at});}
function selected(m:Awaited<ReturnType<typeof model>>,ref:Identity,kind:string){const v=m.views.find(v=>v.selected?.object_type===kind&&sameRepositoryIdentity(v.selected.object,ref));demand(v?.selected&&v.known_effective,'B4_REGISTERED_CURRENT_OBJECT_REQUIRED');return v.selected;}
function identityReference(m:Awaited<ReturnType<typeof model>>,ref:Identity):Reference{const row=selected(m,ref,'IDENTITY');return {record_id:row.record_id,object:row.object,version:row.version};}
function canonicalRow(m:Awaited<ReturnType<typeof model>>,object:Identity,kind:'EFFECT'|'LIFECYCLE',payload:unknown,at:string,eventId:string,old:CanonicalRecord|undefined,references:Reference[],evidenceRefs:string[]):CanonicalRecord{return {schema_version:SCHEMA_VERSION,record_id:old?.record_id??canonicalJSON([B4,kind,object]),event_ref:eventId,object_type:kind,object,principal:m.principal,version:(old?.version??0)+1,temporal:{recorded_at:at,effective_from:at,observed_at:at},evidence_refs:evidenceRefs,provenance_refs:evidenceRefs,privacy_refs:old?.privacy_refs??[],authority_refs:old?.authority_refs??[],references,source_representations:[],payload};}
function assertEffectProjection(s:State,m:Awaited<ReturnType<typeof model>>,principal:Identity){const attempts=s.attempts.filter(a=>sameIdentity(a.intent.principal,principal));for(const a of attempts){const latest=s.effects.filter(e=>sameIdentity(e.attempt,a.attempt)).at(-1);if(latest){const row=selected(m,a.intent.intent,'EFFECT'),p=row.payload as EffectState;demand(p.disposition===latest.disposition&&p.operation_digest===a.intent.operation_digest&&sameIdentity(p.occurrence,a.intent.occurrence),'B4_CANONICAL_EFFECT_PROOF_DRIFT');}}}
export async function recoveryEvidence(s:State,repo:CanonicalRepository,principalInput:unknown,at:string){
 const principal=id(principalInput,'PRINCIPAL'),m=await model(repo,principal,at),scope=await currentProof(repo,principal,principal,'RECOVERY_SCOPE',at),r=record(scope.value,['schema_version','principal','required_roots','required_current','purpose','temporal','evidence_refs']);demand(r.schema_version===B4&&sameIdentity(id(r.principal,'PRINCIPAL'),principal),'B4_RECOVERY_SCOPE_BINDING');applicable(decodeTemporal(r.temporal),at);refs(r.evidence_refs);text(r.purpose);const roots=ids(r.required_roots),currents=denseArray(r.required_current).map(decodeReference);demand(roots.length>0&&currents.length>0,'B4_RECOVERY_SCOPE_EMPTY');
 const rootViews=roots.map(root=>{identityReference(m,root);const life=['OBJECTIVE','OBLIGATION','DECISION_REQUIREMENT'].includes(root.kind)?selected(m,root,'LIFECYCLE'):null;return {root,lifecycle:life?.payload??null,canonical_facts:m.views.filter(v=>v.selected&&sameRepositoryIdentity(v.selected.object,root)).map(v=>({record_id:v.record_id,version:v.selected!.version,known_effective:v.known_effective,object_type:v.selected!.object_type,payload:v.selected!.payload,evidence_refs:v.selected!.evidence_refs,provenance_refs:v.selected!.provenance_refs,privacy_refs:v.selected!.privacy_refs}))};});
 for(const ref of currents){const v=m.views.find(v=>v.record_id===ref.record_id);demand(v?.known_effective&&v.selected?.object_type==='CURRENT'&&sameRepositoryIdentity(v.selected.object,ref.object)&&v.selected.version===ref.version,'B4_RECOVERY_DEPENDENCY_DRIFT');const p=v.selected.payload as {epistemic:{knowledge_state:string;applicability_state:string;freshness_state:string;coverage_state:string;invalidators:string[]}};demand(p.epistemic.knowledge_state==='KNOWN'&&p.epistemic.applicability_state==='APPLICABLE'&&p.epistemic.freshness_state==='CURRENT_AS_OF'&&p.epistemic.coverage_state==='COMPLETE_FOR_DECLARED_SCOPE'&&p.epistemic.invalidators.length===0,'B4_RECOVERY_CURRENT_UNKNOWN');}
 const semanticHolds=rootViews.flatMap(root=>{const reasons:string[]=[];if(root.lifecycle&&(root.lifecycle as {state:string}).state==='UNKNOWN')reasons.push('LIFECYCLE_UNKNOWN:'+canonicalJSON(root.root));for(const fact of root.canonical_facts){if(!fact.known_effective)reasons.push('CANONICAL_INACTIVE:'+fact.record_id);const payload=fact.payload as Record<string,unknown>,ep=fact.object_type==='EPISTEMIC'?payload:payload.epistemic as Record<string,unknown>|undefined;if(ep&&(ep.knowledge_state!=='KNOWN'||ep.applicability_state==='UNKNOWN'||ep.freshness_state!=='CURRENT_AS_OF'||ep.coverage_state!=='COMPLETE_FOR_DECLARED_SCOPE'||(ep.invalidators as unknown[]).length))reasons.push('CANONICAL_EPISTEMIC_HOLD:'+fact.record_id);}return reasons;});const attempts=s.attempts.filter(a=>sameIdentity(a.intent.principal,principal));for(const a of attempts)demand([a.intent.objective,a.intent.obligation].every(ref=>roots.some(root=>sameIdentity(root,ref))),'B4_RECOVERY_ROOT_COVERAGE');for(const view of m.views.filter(v=>v.selected?.object_type==='CURRENT'&&(v.selected.payload as {predicate:string}).predicate===predicate('OBLIGATION'))){const p=view.selected!.payload as {value:{objective:Identity;obligation:Identity;mandatory:boolean};epistemic:{knowledge_state:string;applicability_state:string;freshness_state:string;coverage_state:string;invalidators:string[]}};demand(view.known_effective&&p.epistemic.knowledge_state==='KNOWN'&&p.epistemic.applicability_state==='APPLICABLE'&&p.epistemic.freshness_state==='CURRENT_AS_OF'&&p.epistemic.coverage_state==='COMPLETE_FOR_DECLARED_SCOPE'&&!p.epistemic.invalidators.length,'B4_RECOVERY_OBLIGATION_CURRENT_UNKNOWN');demand(typeof p.value.mandatory==='boolean','B4_RECOVERY_OBLIGATION_MEMBERSHIP_UNKNOWN');if(p.value.mandatory===true&&roots.some(root=>same(root,p.value.objective)))demand(roots.some(root=>same(root,p.value.obligation)),'B4_RECOVERY_MANDATORY_ROOT_MISSING');}assertEffectProjection(s,m,principal);const unresolved=attempts.filter(a=>{const e=latestEffect(s,a);return ['SUBMITTING','AMBIGUOUS_SUBMISSION','RELEASED_SUBMITTED'].includes(a.state)&&(!e||!['EFFECT_VERIFIED','NO_EFFECT_VERIFIED'].includes(e.disposition));}).map(a=>a.attempt);
 const authority=await Promise.all(attempts.map(async a=>{const c=await repo.current({schema_version:SCHEMA_VERSION,principal,subject:principal,predicate:authorityPredicate(a.intent.authority_domain),as_of:at});demand(c.status==='RECORDED_AS_OF'&&c.record,'B4_RECOVERY_AUTHORITY_UNKNOWN');const p=c.record.payload as {value:unknown;epistemic:{knowledge_state:string;applicability_state:string;freshness_state:string;coverage_state:string;invalidators:string[]}};demand(p.epistemic.knowledge_state==='KNOWN'&&p.epistemic.applicability_state==='APPLICABLE'&&p.epistemic.freshness_state==='CURRENT_AS_OF'&&p.epistemic.coverage_state==='COMPLETE_FOR_DECLARED_SCOPE'&&!p.epistemic.invalidators.length,'B4_RECOVERY_AUTHORITY_UNKNOWN');const d=decodeAuthority(p.value);applicable(d.temporal,at);demand(sameIdentity(d.binding.principal,principal)&&d.latest_generation>=a.intent.authority_generation,'B4_RECOVERY_AUTHORITY_BINDING');demand(['ALLOW','DENY'].includes(d.permission),'B4_RECOVERY_AUTHORITY_UNKNOWN');demand(['retain','use','disclose','minimum_necessary'].every(flag=>d.privacy_permission[flag as 'retain']==='ALLOW'),'B4_RECOVERY_PRIVACY_HOLD');applicable(d.privacy_permission.temporal,at);demand(Date.parse(a.intent.privacy.retention_until)>Date.parse(at),'B4_RECOVERY_RETENTION_EXPIRED');return {domain:a.intent.authority_domain,current_record:c.record.record_id,current_version:c.record.version,permission:d.permission,privacy:d.privacy_permission,resources:d.limits,revocations:s.revocations.filter(r=>sameIdentity(r.principal,principal)&&r.domain===a.intent.authority_domain)};}));
 const claims=s.claims.filter(c=>sameIdentity(c.principal,principal));demand(claims.length>0,'B4_RECOVERY_CONTINUATION_UNKNOWN');for(const c of claims){applicable(c.temporal,at);identityReference(m,c.owner_incarnation);}
 return freeze({schema_version:B4,principal,as_of:at,dimensions:{identity:'PASS',canonical_Current:'PASS',coverage:semanticHolds.length?'HOLD':'PASS',authority:'KNOWN_NO_NEW_AUTHORITY',privacy:'PASS',temporal:'PASS',continuation:'PASS',obligations:'PRESERVED',effects:unresolved.length?'HOLD':'PASS'},roots:rootViews,canonical:m,authority,claims,attempts:attempts.map(a=>({attempt:a.attempt,state:a.state,version:a.version,intent:a.intent,effect:latestEffect(s,a)??null,next_safe_action:['SUBMITTING','AMBIGUOUS_SUBMISSION','RELEASED_SUBMITTED'].includes(a.state)&&!latestEffect(s,a)?'RECONCILE_FIRST':a.state==='DENIED'?'HOLD':'VALIDATE_BEFORE_NEW_RELEASE'})),unresolved_effects:unresolved,semantic_holds:semanticHolds,admission:unresolved.length?'HOLD_RECONCILIATION_REQUIRED':semanticHolds.length?'HOLD_CANONICAL_REQUALIFICATION_REQUIRED':'RECOVERY_EVIDENCE_PASS',continuity_ON:false,authority_effect:'NONE'});
}
export async function reduceRecovery(s:State,repo:CanonicalRepository,kind:string,input:unknown,at:string,context:RecoveryContext,validateRelease:(a:ReleaseAttempt)=>Promise<Readonly<ValidatedAuthoritySnapshot>>):Promise<{proof:unknown;materialized:AppendCommand[]}>{
 if(kind==='VERIFY_EFFECT'){
  const r=record(input,['schema_version','verification','attempt','expected_attempt_version','source_id','source_version','observation','prediction_ref']);demand(r.schema_version===B4,'B4_SCHEMA_REQUIRED');const verification=id(r.verification,'VERIFICATION'),a=findAttempt(s,r.attempt),requestDigest=digest(input),prior=s.effects.find(e=>sameIdentity(e.verification,verification));if(prior){demand(prior.request_digest===requestDigest,'B4_VERIFICATION_IDENTITY_DRIFT');return result(prior);}
  demand(version(r.expected_attempt_version)===a.version,'B4_ATTEMPT_VERSION_DRIFT');demand(['SUBMITTING','AMBIGUOUS_SUBMISSION','RELEASED_SUBMITTED'].includes(a.state),'B4_POSSIBLE_SUBMISSION_REQUIRED');const q=await qualifiedSource(repo,a,text(r.source_id),at);demand(version(r.source_version)===q.current_version,'B4_SOURCE_VERSION_DRIFT');const o=decodeReadback(r.observation),classification=classifyReadback(a,q.qualification,o,at),prediction=r.prediction_ref===null?null:decodeReference(r.prediction_ref);
  if(prediction!==null){const preparedEvent=context.events.find(e=>{const c=e.command as {kind:string;value:{attempt?:Identity}};return c.kind==='PREPARE'&&c.value.attempt&&sameIdentity(c.value.attempt,a.attempt);}),prefix=preparedEvent?context.commands.slice(0,preparedEvent.canonical_count):[],row=prefix.map(c=>c.value).find(v=>v.record_id===prediction.record_id&&v.version===prediction.version&&same(v.object,prediction.object)&&sameIdentity(v.principal,a.intent.principal));demand(row&&Date.parse(row.temporal.recorded_at)<Date.parse(a.prepared_at)&&[a.intent.intent,a.intent.work_episode,a.intent.causal_episode].some(object=>same(object,prediction.object)),'B4_PROSPECTIVE_PREDICTION_REQUIRED');}
  const priorRead=s.effects.filter(e=>sameIdentity(e.attempt,a.attempt)&&e.observation.source_id===o.source_id).at(-1);demand(!priorRead||o.readback_version>priorRead.observation.readback_version&&Date.parse(o.observed_at)>=Date.parse(priorRead.observation.observed_at),'B4_READBACK_VERSION_REGRESSION');
  const proof:EffectProof&{request_digest:string}={schema_version:B4,verification,attempt:a.attempt,attempt_version:a.version,intent:a.intent.intent,occurrence:a.intent.occurrence,operation_digest:a.intent.operation_digest,at,qualification:q,observation:o,...classification,evidence_refs:[...q.qualification.evidence_refs,...o.evidence_refs],prediction_ref:prediction,experience_class:q.qualification.source_class==='QUALIFICATION_FIXTURE'?'SYNTHETIC_QUALIFICATION':'EMPIRICAL_SOURCE_READBACK',authority:'NONE',request_digest:requestDigest};
  const m=await model(repo,a.intent.principal,at),old=m.views.find(v=>v.selected?.object_type==='EFFECT'&&sameIdentity(v.selected.object as Identity,a.intent.intent))?.selected??undefined,eventId=canonicalJSON([verification]);let materialized:AppendCommand[]=[];
  if(!old||(old.payload as EffectState).disposition!==proof.disposition){const payload=old?reduceEffect(old.payload,{event_id:eventId,intent:a.intent.intent,operation_digest:a.intent.operation_digest,occurrence:a.intent.occurrence,expected_version:old.version,next_disposition:proof.disposition,kind:['EFFECT_VERIFIED','NO_EFFECT_VERIFIED'].includes((old.payload as EffectState).disposition)?'CORRECTION':'OBSERVATION',proof:classification.proof,evidence_refs:proof.evidence_refs,at}):{intent:a.intent.intent,operation_digest:a.intent.operation_digest,occurrence:a.intent.occurrence,version:1,disposition:proof.disposition,last_event_ref:eventId,proof:classification.proof,evidence_refs:proof.evidence_refs};const row=canonicalRow(m,a.intent.intent,'EFFECT',payload,at,eventId,old,[identityReference(m,a.intent.intent),identityReference(m,a.intent.occurrence)],proof.evidence_refs);materialized=[{schema_version:SCHEMA_VERSION,expected_version:old?.version??0,transition:old?{event_id:eventId,intent:a.intent.intent,operation_digest:a.intent.operation_digest,occurrence:a.intent.occurrence,expected_version:old.version,next_disposition:proof.disposition,kind:['EFFECT_VERIFIED','NO_EFFECT_VERIFIED'].includes((old.payload as EffectState).disposition)?'CORRECTION':'OBSERVATION',proof:classification.proof,evidence_refs:proof.evidence_refs,at}:null,value:row}];}
  s.effects.push(proof);return result(proof,materialized);
 }
 if(kind==='RECONCILE_CLOSURE'){
  const r=record(input,['schema_version','reconciliation','principal','objective','expected_version','contract_version']);demand(r.schema_version===B4,'B4_SCHEMA_REQUIRED');const principal=id(r.principal,'PRINCIPAL'),objective=id(r.objective,'OBJECTIVE'),identity=text(r.reconciliation),m=await model(repo,principal,at),life=selected(m,objective,'LIFECYCLE'),current=await currentProof(repo,principal,objective,'CLOSURE',at),contract=decodeClosure(current.value);demand(current.record.version===version(r.contract_version)&&life.version===version(r.expected_version),'B4_CLOSURE_VERSION_DRIFT');demand(sameIdentity(contract.objective,objective)&&sameIdentity(contract.principal,principal),'B4_CLOSURE_BINDING');applicable(contract.temporal,at);demand(!s.closures.some(c=>c.identity===identity),'B4_DUPLICATE_RECONCILIATION');
  const memberships=m.views.filter(v=>v.selected?.object_type==='CURRENT'&&(v.selected.payload as {predicate:string}).predicate===predicate('OBLIGATION')).map(v=>{demand(v.known_effective,'B4_OBLIGATION_RELATION_STALE');const p=v.selected!.payload as {value:unknown;subject:Identity;epistemic:{knowledge_state:string;applicability_state:string;freshness_state:string;coverage_state:string;invalidators:string[]}};demand(p.epistemic.knowledge_state==='KNOWN'&&p.epistemic.applicability_state==='APPLICABLE'&&p.epistemic.freshness_state==='CURRENT_AS_OF'&&p.epistemic.coverage_state==='COMPLETE_FOR_DECLARED_SCOPE'&&!p.epistemic.invalidators.length,'B4_OBLIGATION_RELATION_UNKNOWN');const o=record(p.value,['schema_version','principal','objective','obligation','mandatory','intent','resolution','temporal','evidence_refs']);demand(o.schema_version===B4&&typeof o.mandatory==='boolean'&&sameIdentity(id(o.principal,'PRINCIPAL'),principal)&&sameIdentity(id(o.obligation,'OBLIGATION'),p.subject),'B4_OBLIGATION_RELATION_BINDING');applicable(decodeTemporal(o.temporal),at);refs(o.evidence_refs);return {objective:id(o.objective,'OBJECTIVE'),mandatory:o.mandatory,obligation:id(o.obligation,'OBLIGATION'),intent:id(o.intent,'INTENT'),resolution:o.resolution===null?null:id(o.resolution,'DECISION_REQUIREMENT')};}).filter(o=>sameIdentity(o.objective,objective)&&o.mandatory);
  demand(same(memberships.map(({objective:o,mandatory:b,...rest})=>rest).sort((a,b)=>canonicalJSON(a)<canonicalJSON(b)?-1:canonicalJSON(a)>canonicalJSON(b)?1:0),[...contract.mandatory].sort((a,b)=>canonicalJSON(a)<canonicalJSON(b)?-1:canonicalJSON(a)>canonicalJSON(b)?1:0)),'B4_MANDATORY_ROSTER_DRIFT');
  assertEffectProjection(s,m,principal);const all=s.attempts.filter(a=>sameIdentity(a.intent.principal,principal)&&sameIdentity(a.intent.objective,objective));demand(all.length>0,'B4_CLOSURE_EFFECT_COVERAGE_REQUIRED');for(const a of all){const e=latestEffect(s,a);demand(e?.disposition==='EFFECT_VERIFIED','B4_CLOSURE_UNRESOLVED_EFFECT');demand(a.intent.authority_domain===contract.authority_domain&&a.intent.privacy.purpose===contract.privacy_purpose,'B4_CLOSURE_AUTHORITY_PRIVACY_BINDING');const q=await qualifiedSource(repo,a,e.observation.source_id,at);demand(q.current_version===e.qualification.current_version&&q.current_digest===e.qualification.current_digest,'B4_CLOSURE_SOURCE_CHANGED');}
  for(const criterion of contract.criteria)demand(all.some(a=>sameIdentity(a.intent.intent,criterion.intent)),'B4_CLOSURE_CRITERION_UNPROVEN');
  const recovered=await recoveryEvidence(s,repo,principal,at);demand(recovered.admission==='RECOVERY_EVIDENCE_PASS','B4_CLOSURE_CANONICAL_REQUALIFICATION_REQUIRED');const materialized:AppendCommand[]=[];for(const obligation of contract.mandatory){const a=all.find(a=>sameIdentity(a.intent.intent,obligation.intent)&&sameIdentity(a.intent.obligation,obligation.obligation));demand(a,'B4_UNRELATED_OBLIGATION_EFFECT');if(obligation.resolution){const resolution=decodeLifecycle(selected(m,obligation.resolution,'LIFECYCLE').payload);demand(resolution.state==='RESOLVED','B4_MANDATORY_RESOLUTION_OPEN');}}
  for(const target of [...contract.mandatory.map(o=>o.obligation),objective]){const row=selected(m,target,'LIFECYCLE'),state=decodeLifecycle(row.payload);demand(state.state==='NONTERMINAL','B4_TERMINAL_CORRECTION_REQUIRED');const event={event_id:canonicalJSON([identity,target]),object:target,principal,expected_version:row.version,next_state:'SATISFIED' as const,kind:'TRANSITION' as const,evidence_refs:contract.evidence_refs,at,basis_ref:identity,basis_kind:'CLOSURE_RECONCILIATION' as const,basis_knowledge:'KNOWN' as const},payload=reduceLifecycle(row.payload,event);materialized.push({schema_version:SCHEMA_VERSION,expected_version:row.version,transition:event,value:canonicalRow(m,target,'LIFECYCLE',payload,at,event.event_id,row,row.references,[...contract.evidence_refs])});}
  const proof:ProofResult={schema_version:B4,kind,identity,principal,at,data:{objective,contract_record:current.record.record_id,contract_version:current.record.version,criteria:contract.criteria,mandatory:contract.mandatory,effect_verifications:all.map(a=>latestEffect(s,a)!.verification),snapshot:snapshot(context),canonical_transitions:materialized.map(c=>({record_id:c.value.record_id,version:c.value.version}))},authority:'NONE'};s.closures.push(proof);return result(proof,materialized);
 }
 if(kind==='AUTHORIZE_VERIFIED_RETRY'){
  const r=record(input,['schema_version','attempt','expected_attempt_version','verification','policy_version','compensation_attempt']);demand(r.schema_version===B4,'B4_SCHEMA_REQUIRED');const a=findAttempt(s,r.attempt),e=latestEffect(s,a);assertEffectProjection(s,await model(repo,a.intent.principal,at),a.intent.principal);demand(version(r.expected_attempt_version)===a.version&&e&&sameIdentity(e.verification,id(r.verification,'VERIFICATION'))&&e.disposition==='NO_EFFECT_VERIFIED','B4_RETRY_POSITIVE_ABSENCE_REQUIRED');demand(a.intent.retry_class!=='NON_IDEMPOTENT_UNSAFE','B4_UNSAFE_RETRY');const q=await qualifiedSource(repo,a,e.observation.source_id,at);demand(q.current_version===e.qualification.current_version&&q.current_digest===e.qualification.current_digest,'B4_RETRY_SOURCE_CHANGED');
  const policy=await currentProof(repo,a.intent.principal,a.intent.intent,'RETRY',at),p=record(policy.value,['schema_version','intent','operation_digest','max_retries','proof_valid_until','compensation_attempt','temporal','evidence_refs']);demand(p.schema_version===B4&&policy.record.version===version(r.policy_version)&&sameIdentity(id(p.intent,'INTENT'),a.intent.intent)&&sha(p.operation_digest)===a.intent.operation_digest,'B4_RETRY_POLICY_BINDING');applicable(decodeTemporal(p.temporal),at);refs(p.evidence_refs);const expires=instant(p.proof_valid_until);demand(Date.parse(expires)>Date.parse(at)&&Date.parse(expires)<=Date.parse(q.qualification.temporal.valid_until!),'B4_RETRY_PROOF_EXPIRED');demand(s.retries.filter(x=>sameIdentity(x.attempt,a.attempt)).length<version(p.max_retries),'B4_RETRY_LIMIT');
  const compensation=r.compensation_attempt===null?null:id(r.compensation_attempt,'RELEASE_ATTEMPT');demand(same(compensation,p.compensation_attempt),'B4_COMPENSATION_POLICY_BINDING');if(compensation){const c=findAttempt(s,compensation),ce=latestEffect(s,c);demand(!sameIdentity(c.attempt,a.attempt)&&sameIdentity(c.intent.principal,a.intent.principal)&&sameIdentity(c.intent.objective,a.intent.objective)&&ce?.disposition==='EFFECT_VERIFIED','B4_COMPENSATION_NOT_VERIFIED');await validateRelease(c);}
  await validateRelease(a);demand(a.version<Number.MAX_SAFE_INTEGER,'VERSION_OVERFLOW');a.state='RETRY_SAFE_VERIFIED';a.receipt=null;a.reason='B4_VERIFIED_RETRY_REVALIDATION_REQUIRED';a.version++;a.updated_at=at;const authorization={attempt:a.attempt,verification:e.verification,attempt_version:a.version,expires_at:expires,source_version:q.current_version,source_record:q.current_record_id,source_digest:q.current_digest,policy_version:policy.record.version,policy_digest:digest(policy.record),compensation};s.retries.push(authorization);return result(authorization);
 }
 if(kind==='QUALIFY_CHECKPOINT'){
  const r=record(input,['schema_version','checkpoint_id','principal','workflow','step_id','payload','qualification_version','continuation','effect_class','replay_class']);demand(r.schema_version===B4,'B4_SCHEMA_REQUIRED');const principal=id(r.principal,'PRINCIPAL'),workflow=id(r.workflow,'WORK_EPISODE'),identity=text(r.checkpoint_id),step=text(r.step_id),payload=jsonValue(r.payload),continuation=decodeContinuation(r.continuation),effectClass=member(r.effect_class,['ZERO_EFFECT','EFFECTFUL'] as const),replayClass=member(r.replay_class,['ZERO_EFFECT_SAFE','READ_ONLY_SAFE','NO_AUTOMATIC_REPLAY'] as const);demand(sameIdentity(continuation.principal,principal)&&s.claims.some(c=>same(c,continuation)),'B4_CHECKPOINT_FENCE_DRIFT');demand(!s.checkpoints.some(c=>c.identity===identity),'B4_CHECKPOINT_IDENTITY_DRIFT');const q=await currentProof(repo,principal,workflow,'CHECKPOINT:'+step,at),c=record(q.value,['schema_version','workflow','step_id','payload_digest','effect_class','replay_class','temporal','evidence_refs']);demand(c.schema_version===B4&&q.record.version===version(r.qualification_version)&&sameIdentity(id(c.workflow,'WORK_EPISODE'),workflow)&&c.step_id===step&&sha(c.payload_digest)===digest(payload)&&c.effect_class===effectClass&&c.replay_class===replayClass,'B4_CHECKPOINT_QUALIFICATION_BINDING');applicable(decodeTemporal(c.temporal),at);refs(c.evidence_refs);demand(effectClass!=='EFFECTFUL'||replayClass==='NO_AUTOMATIC_REPLAY'||replayClass==='READ_ONLY_SAFE','B4_EFFECTFUL_REPLAY_FORBIDDEN');
  const recovery=await recoveryEvidence(s,repo,principal,at);demand(recovery.admission==='RECOVERY_EVIDENCE_PASS','B4_CHECKPOINT_RECONCILIATION_REQUIRED');const proof:ProofResult={schema_version:B4,kind,identity,principal,at,data:{workflow,step_id:step,payload,payload_digest:digest(payload),continuation,effect_class:effectClass,replay_class:replayClass,qualification_record:q.record.record_id,qualification_version:q.record.version,qualification_digest:digest(q.record),valid_until:decodeTemporal(c.temporal).valid_until,recovery,snapshot:snapshot(context)},authority:'NONE'};s.checkpoints.push(proof);return result(proof);
 }
 if(kind==='VERIFY_PROJECTION'){
  const r=record(input,['schema_version','principal','run','scope_version']);demand(r.schema_version===B4,'B4_SCHEMA_REQUIRED');const principal=id(r.principal,'PRINCIPAL'),run=id(r.run,'PROJECTION_RUN'),scope=await currentProof(repo,principal,principal,'RECOVERY_SCOPE',at);demand(scope.record.version===version(r.scope_version),'B4_PROJECTION_SCOPE_DRIFT');demand(!s.runs.some(p=>p.identity===run.id),'B4_PROJECTION_RUN_IDENTITY_DRIFT');const recovery=await recoveryEvidence(s,repo,principal,at),dependencies=recovery.canonical.views.map(v=>({record_id:v.record_id,object:v.selected?.object??null,version:v.selected?.version??null,temporal:v.temporal,known_effective:v.known_effective})),sourceEvaluations=dependencies.map(d=>({...d,disposition:d.known_effective?'RECORDED_EFFECTIVE_AS_OF':'UNAVAILABLE_AS_OF'})),output={roots:recovery.roots,attempts:recovery.attempts,authority:recovery.authority,continuation:recovery.claims,unresolved_effects:recovery.unresolved_effects,dimensions:recovery.dimensions};const proof:ProofResult={schema_version:B4,kind,identity:run.id,principal,at,data:{run,as_of:at,bracket:{started_at:at,ended_at:at,status:'PINNED_CANONICAL_SNAPSHOT',...snapshot(context)},dependencies,source_evaluations:sourceEvaluations,output,content_hash:digest(output),completeness:recovery.admission==='RECOVERY_EVIDENCE_PASS'?'COMPLETE_FOR_DECLARED_SCOPE':'INCOMPLETE',non_authoritative:true},authority:'NONE'};s.runs.push(proof);return result(proof);
 }
 demand(false,'B4_UNSUPPORTED_COMMAND');
}
export async function validateRetryAtRelease(s:State,repo:CanonicalRepository,a:ReleaseAttempt,at:string){const proof=s.retries.filter(p=>sameIdentity(p.attempt,a.attempt)&&p.attempt_version===a.version).at(-1);demand(proof&&Date.parse(proof.expires_at)>Date.parse(at),'B4_RETRY_PROOF_EXPIRED');const q=await currentProof(repo,a.intent.principal,a.intent.principal,'SOURCE:'+s.effects.find(e=>sameIdentity(e.verification,proof.verification))!.observation.source_id,at);demand(q.record.version===proof.source_version&&digest(q.record)===proof.source_digest,'B4_RETRY_SOURCE_CHANGED');const p=await currentProof(repo,a.intent.principal,a.intent.intent,'RETRY',at);demand(p.record.version===proof.policy_version&&digest(p.record)===proof.policy_digest,'B4_RETRY_POLICY_CHANGED');const body=record(p.value,['schema_version','intent','operation_digest','max_retries','proof_valid_until','compensation_attempt','temporal','evidence_refs']);demand(body.schema_version===B4&&body.operation_digest===a.intent.operation_digest&&body.proof_valid_until===proof.expires_at&&same(body.compensation_attempt,proof.compensation),'B4_RETRY_POLICY_CHANGED');}
