import {B6,decodePilotRequest,decodeScope,type PilotRequest} from './contracts.ts';
import {selectPrimary,coverageFact} from './selector.ts';
import {decodeRootDisposition,REASON_DOMAINS} from '../domain/root-disposition.ts';
import {SCHEMA_VERSION,type CanonicalRecord} from '../domain/canonical.ts';
import {reduceCoverage} from '../semantic-kernel/epistemic.ts';
import {sameIdentity,type Identity,type Relation,decodeRelation,resolutionsEquivalent} from '../semantic-kernel/identity.ts';
import {demand,record,evidence,member,freeze} from '../semantic-kernel/validation.ts';
import {denseArray,jsonValue} from '../domain/json.ts';
import {digest} from '../enforcement/contracts.ts';
import {EnforcementRepository,decodeEnforcementSnapshot} from '../enforcement/repository.ts';
import {MemoryCanonicalRepository,canonicalJSON,type CanonicalRepository} from '../state/repository.ts';
import {CapabilityContext,same,predicate} from '../capability/context.ts';
import {filterPrivacy} from '../capability/privacy.ts';
import {RecoveryService} from '../recovery/service.ts';
import {B4} from '../recovery/contracts.ts';
type RecoveryOutput={roots:{root:Identity}[];attempts:{attempt:Identity;state:string;intent:{intent:Identity};next_safe_action:string}[];unresolved_effects:Identity[];dimensions:Record<string,unknown>};
type Foundation={output:RecoveryOutput;completeness:string};

async function compile(repository:CanonicalRepository,request:Readonly<PilotRequest>,foundation:Foundation){
 const wire=await repository.exportSnapshot(),c=new CapabilityContext(repository,request.principal,request.as_of,wire),bound=await c.boundReference(request.scope_ref,request.principal,'PILOT_SCOPE'),scope=decodeScope(bound.value);
 demand(same(scope.principal,request.principal)&&same(scope.recipient,request.recipient)&&scope.purpose===request.purpose&&scope.boundary_id===request.boundary_id&&scope.consumer_class===request.consumer_class,'B6_SCOPE_BOUNDARY_MISMATCH');
 demand([...foundation.output.roots.map(r=>r.root),...foundation.output.attempts.map(a=>a.intent.intent)].every(root=>scope.roots.some(r=>same(r.object,root))),'B6_RECOVERY_ROOT_CONSERVATION');
 const refs=[...scope.roots,...scope.sources.map(s=>s.reference)],compounds=[],facts=[],publicFacts=[],visible=[],source_evaluations=[];
 for(const ref of refs){
  const row=await c.reference(ref);demand(row.object_type==='ROOT_DISPOSITION','B6_CANONICAL_DISPOSITION_REQUIRED');const q=decodeRootDisposition(row.payload);
  demand(same(q.principal_ref,request.principal)&&q.as_of===request.as_of&&q.version===row.version&&same(q.root_ref,row.object)&&q.boundary_id===request.boundary_id&&q.consumer_class===request.consumer_class&&same(q.privacy.recipient_ref,request.recipient)&&q.privacy.purpose_ref===request.purpose,'B6_ROOT_BOUNDARY_OR_CUT_DRIFT');
  demand(q.invalidator_refs.length===0&&q.epistemic.invalidators.length===0,'B6_REQUALIFICATION_REQUIRED');
  const domains=Object.keys(REASON_DOMAINS).filter(d=>!['REACTIVATION','INVALIDATOR'].includes(d)&&(d!=='LIFECYCLE'||q.lifecycle!==null));
  demand(domains.every(d=>q.reason_set.some(r=>r.reason_type===d)),'B6_INCOMPLETE_COMPOUND_REASONS');
  const basis=new Set([...row.evidence_refs,...row.provenance_refs]);demand([...q.provenance_refs,...q.epistemic.evidence_refs,...q.privacy.evidence_refs,...q.reason_set.flatMap(r=>r.evidence_refs),...q.reactivation_refs,...q.invalidator_refs].every(r=>basis.has(r)),'B6_UNQUALIFIED_REASON_BASIS');
  const model=await repository.reconstruct({schema_version:SCHEMA_VERSION,principal:request.principal,as_of:request.as_of});
  if(q.lifecycle){const selected=model.views.find(v=>v.known_effective&&v.selected?.object_type==='LIFECYCLE'&&same(v.selected.object,q.root_ref))?.selected;demand(selected&&same(selected.payload,q.lifecycle)&&row.references.some(r=>same(r,c.ref(selected))),'B6_LIFECYCLE_SOURCE_DRIFT');}
  for(const view of model.views.filter(v=>v.selected?.object_type==='EPISTEMIC'&&same(v.selected.object,q.root_ref))){demand(view.known_effective&&same(view.selected!.payload,q.epistemic)&&row.references.some(r=>same(r,c.ref(view.selected!))),'B6_EPISTEMIC_SOURCE_DRIFT');}
  const policyId='pilot:'+row.record_id,policy=await c.current(request.principal,'PRIVACY:'+policyId),p=policy.value as Record<string,unknown>;
  await filterPrivacy(c,{policy_id:policyId,purpose:request.purpose,recipient:request.recipient,classification:'PILOT_COMPOUND',payload:q,source_refs:[ref],retain:true,disclose:false});
  const disclosure=p.disclose==='ALLOW'?'PERMITTED':p.disclose==='DENY'?'PROHIBITED':'UNKNOWN';demand(disclosure===q.privacy.disclosure_result,'B6_DISCLOSURE_SOURCE_DRIFT');
  const primary=selectPrimary(q),fact=coverageFact(q,primary),publicFact=coverageFact(q,primary,true);
  compounds.push({reference:ref,canonical:q,selected_primary:primary,policy_ref:c.ref(policy.row),operational_fact:fact});facts.push(fact);publicFacts.push(publicFact);
  const reasons=primary==='PRIVACY_EXCLUDED'?q.reason_set.filter(r=>r.reason_type==='DISCLOSURE'):q.reason_set;
  visible.push({root_ref:q.root_ref,primary_visible_disposition:primary,reason_set:reasons});
  source_evaluations.push({reference:ref,record_digest:digest(row),source_id:scope.sources.find(s=>same(s.reference,ref))?.source_id??null,selected_as_of:request.as_of,temporal:row.temporal,disposition:primary});
 }
 const resolutions=[];
 for(const ref of scope.resolutions){const row=await c.reference(ref);demand(row.object_type==='CURRENT','B6_RESOLUTION_CURRENT_REQUIRED');const payload=row.payload as {subject:Identity;predicate:string;value:unknown;epistemic:unknown};const current=await c.current(row.object as Identity,'PILOT_RESOLUTION');demand(same(c.ref(current.row),ref),'B6_RESOLUTION_SELECTED_DRIFT');const r=record(payload.value,['schema_version','resolution','resolution_kind','roots','evidence_refs']);demand(r.schema_version===B6&&same(r.resolution,row.object)&&row.object.kind==='RESOLUTION','B6_RESOLUTION_IDENTITY');const roots=denseArray(r.roots).map(v=>{const item=record(v,['record_id','object','version']);const matched=refs.find(f=>same(f,item));demand(matched&&scope.roots.some(x=>same(x,matched))&&row.references.some(x=>same(x,matched)),'B6_RESOLUTION_ROOT_DRIFT');return matched;});demand(roots.length>0&&new Set(roots.map(r=>r.record_id)).size===roots.length,'B6_RESOLUTION_ROOT_ROSTER');evidence(denseArray(r.evidence_refs));resolutions.push({reference:ref,resolution:row.object as Identity,resolution_kind:member(r.resolution_kind,['DECIDE','ACT','AUTHORIZE','RECONCILE_EFFECT','RESOLVE_CONFLICT'] as const),roots});}
 const relations:Readonly<Relation>[]=[];
 for(const ref of scope.equivalences){const row=await c.reference(ref);demand(row.object_type==='RELATION','B6_EXPLICIT_EQUIVALENCE_REQUIRED');const rel=decodeRelation(row.payload);demand(rel.kind==='RESOLUTION_EQUIVALENCE'&&resolutions.some(r=>same(r.resolution,rel.source))&&resolutions.some(r=>same(r.resolution,rel.target)),'B6_EQUIVALENCE_SCOPE');relations.push(rel);}
 const groups:{resolution:Identity;resolution_kind:string;root_refs:Identity[]}[]=[];
 for(const item of visible.filter(v=>scope.roots.some(r=>same(r.object,v.root_ref))&&['KNOWN_REQUIRED','CONFLICT_HOLD'].includes(v.primary_visible_disposition))){const matches=resolutions.filter(r=>r.roots.some(ref=>same(ref.object,item.root_ref)));demand(matches.length===1,'B6_EXACT_RESOLUTION_REQUIRED');const r=matches[0]!;let group=groups.find(g=>sameIdentity(g.resolution,r.resolution)||resolutionsEquivalent(g.resolution,r.resolution,request.principal,relations,request.as_of));if(group)demand(group.resolution_kind===r.resolution_kind,'B6_EQUIVALENCE_ACTION_CONFLICT');else{group={resolution:r.resolution,resolution_kind:r.resolution_kind,root_refs:[]};groups.push(group);}group.root_refs.push(item.root_ref);}
 const roots=facts.map(f=>f.root),coverage=reduceCoverage({roots,principal:request.principal,as_of:request.as_of},facts),publicCoverage=reduceCoverage({roots,principal:request.principal,as_of:request.as_of},publicFacts);
 const workRouting=foundation.output.attempts.map(a=>{const q=visible.find(r=>same(r.root_ref,a.intent.intent))!;if(q.primary_visible_disposition==='PRIVACY_EXCLUDED')return {root_ref:q.root_ref,next_safe_action:'PRIVACY_EXCLUDED',release_state:'NOT_DISCLOSED'};if(foundation.output.unresolved_effects.some(ref=>same(ref,a.attempt))){demand(!['TERMINAL_RETAINED','JUSTIFIED_NOT_APPLICABLE','DEFERRED_SUPPRESSED_WITH_REACTIVATION'].includes(q.primary_visible_disposition),'B6_UNRESOLVED_EFFECT_SUPPRESSION');if(q.primary_visible_disposition==='KNOWN_REQUIRED')demand(groups.some(g=>g.resolution_kind==='RECONCILE_EFFECT'&&g.root_refs.some(root=>same(root,q.root_ref))),'B6_RECONCILIATION_RESOLUTION_REQUIRED');}return {root_ref:q.root_ref,next_safe_action:a.next_safe_action,release_state:a.state};});
 const hidden=visible.some(v=>v.primary_visible_disposition==='PRIVACY_EXCLUDED'),publicOutput={schema_version:B6,principal:request.principal,recipient:request.recipient,purpose:request.purpose,as_of:request.as_of,roots:visible.slice(0,scope.roots.length),source_coverage:visible.slice(scope.roots.length),interventions:groups,completeness_state:publicCoverage.coverage_state,coverage_gaps:publicCoverage.coverage_state==='COMPLETE_FOR_DECLARED_SCOPE'?[]:['DECLARED_SCOPE_NOT_COMPLETE'],recovery_completeness:hidden?'UNKNOWN':foundation.completeness,work_routing:workRouting,qualification_boundary:'PINNED_AS_OF_ONLY',requalification_before_action:true,continuity_ON:false,authority_effect:'NONE',admission:'NOT_ADJUDICATED'};
 return freeze({scope_ref:request.scope_ref,compound_audit:compounds,facts:coverage.facts,coverage:coverage.coverage_state,source_evaluations,public_output:publicOutput,content_hash:digest(publicOutput)});
}

const runPredicate=(request:Readonly<PilotRequest>)=>predicate('PILOT_RUN:'+request.run.id);
async function runRow(repo:CanonicalRepository,r:Readonly<PilotRequest>){return repo.current({schema_version:SCHEMA_VERSION,principal:r.principal,subject:r.principal,predicate:runPredicate(r),as_of:r.as_of});}
function runCommand(request:Readonly<PilotRequest>,state:'CAPTURED'|'COMPLETE',data:unknown,revision:number):unknown{
 const event=canonicalJSON([B6,request.run,revision]),row:CanonicalRecord={schema_version:SCHEMA_VERSION,record_id:canonicalJSON([B6,request.principal,request.run]),event_ref:event,object_type:'CURRENT',object:request.principal,principal:request.principal,version:revision,temporal:{recorded_at:request.as_of,effective_from:request.as_of,observed_at:request.as_of},evidence_refs:['B6:derived-projection-not-current-or-authority'],provenance_refs:[request.scope_ref.record_id],privacy_refs:['B6:private-compound-audit'],authority_refs:[],references:[request.scope_ref],source_representations:[],payload:{subject:request.principal,predicate:runPredicate(request),value:{schema_version:B6,run:request.run,request,request_digest:digest(request),state,data:jsonValue(data),institutional_current:false,authority_effect:'NONE',continuity_ON:false},epistemic:{knowledge_state:'UNKNOWN',applicability_state:'UNKNOWN',freshness_state:'UNKNOWN',coverage_state:'UNKNOWN',as_of:request.as_of,evidence_refs:[],invalidators:[]}}};
 return {schema_version:SCHEMA_VERSION,expected_version:revision-1,transition:{event_id:event,kind:revision===1?'ASSERT':'CORRECTION',at:request.as_of,evidence_refs:row.evidence_refs},value:row};
}
function stored(row:CanonicalRecord,request:Readonly<PilotRequest>){const p=record(row.payload,['subject','predicate','value','epistemic']),v=record(p.value,['schema_version','run','request','request_digest','state','data','institutional_current','authority_effect','continuity_ON']);demand(v.schema_version===B6&&same(v.request,request)&&v.request_digest===digest(request)&&v.institutional_current===false&&v.authority_effect==='NONE'&&v.continuity_ON===false,'B6_RUN_INVOCATION_DRIFT');return v;}

export class CanonicalPilotService {
 readonly repository:EnforcementRepository;
 constructor(repository:EnforcementRepository){demand(repository instanceof EnforcementRepository,'B6_CANONICAL_REPOSITORY_REQUIRED');this.repository=repository;}
 async project(input:unknown){
  const request=decodePilotRequest(input);let saved=await runRow(this.repository.canonical,request);
  if(saved.record){const prior=stored(saved.record,request);if(prior.state==='COMPLETE')return this.read(request);demand(prior.state==='CAPTURED','B6_RUN_STATE_HOLD');}
  else{
   // Preflight is disposable. Only the B4 pinned prefix is used for output.
   const preflight=await this.repository.recoverySnapshot(request.principal,request.as_of),wire=await this.repository.canonical.exportSnapshot(),local=new MemoryCanonicalRepository();await local.importSnapshot(wire);await compile(local,request,{output:preflight.recovery as RecoveryOutput,completeness:preflight.recovery.admission==='RECOVERY_EVIDENCE_PASS'?'COMPLETE_FOR_DECLARED_SCOPE':'INCOMPLETE'});
   try{await this.repository.canonical.append(runCommand(request,'CAPTURED',null,1));}catch(error){saved=await runRow(this.repository.canonical,request);if(!saved.record)throw error;stored(saved.record,request);}
  }
  let snapshot=await decodeEnforcementSnapshot(await this.repository.exportSnapshot());
  let event=snapshot.events.find(e=>{const c=e.command as {kind?:string;value?:{run?:Identity}};return c.kind==='VERIFY_PROJECTION'&&same(c.value?.run,request.run);});
  if(!event){try{await new RecoveryService(this.repository).project({schema_version:B4,principal:request.principal,run:request.run,scope_version:request.recovery_scope_version});}catch(error){snapshot=await decodeEnforcementSnapshot(await this.repository.exportSnapshot());event=snapshot.events.find(e=>{const c=e.command as {kind?:string;value?:{run?:Identity}};return c.kind==='VERIFY_PROJECTION'&&same(c.value?.run,request.run);});if(!event)throw error;}snapshot=await decodeEnforcementSnapshot(await this.repository.exportSnapshot());event=snapshot.events.find(e=>{const c=e.command as {kind?:string;value?:{run?:Identity}};return c.kind==='VERIFY_PROJECTION'&&same(c.value?.run,request.run);});}
  demand(event&&event.at===request.as_of,'B6_PROOF_CUT_MISMATCH');const command=event.command as {value:{principal:Identity;scope_version:number}},proof=(event.result as {proof:Record<string,unknown>}).proof;demand(same(command.value.principal,request.principal)&&command.value.scope_version===request.recovery_scope_version&&proof.identity===request.run.id&&proof.authority==='NONE','B6_PROOF_BINDING');
  const commands=snapshot.commands.slice(0,event.canonical_count);demand(digest(commands)===event.canonical_digest,'B6_PREFIX_DIGEST_DRIFT');const pinned=new MemoryCanonicalRepository();await pinned.importSnapshot(canonicalJSON({schema_version:SCHEMA_VERSION,commands,records:commands.map(c=>c.value)}));const captured=await runRow(pinned,request);demand(captured.record&&stored(captured.record,request).state==='CAPTURED','B6_CAPTURE_NOT_IN_PROOF_PREFIX');
  const data=await compile(pinned,request,{output:(proof.data as Foundation).output,completeness:(proof.data as Foundation).completeness}),audit={...data,proof:{run:request.run,canonical_count:event.canonical_count,canonical_digest:event.canonical_digest,enforcement_sequence:event.sequence,proof_digest:digest(proof)},qualification:'SOURCE_QUALIFIED_PINNED_AS_OF',current_at_delivery:false};
  try{await this.repository.canonical.append(runCommand(request,'COMPLETE',audit,2));}catch(error){const existing=await runRow(this.repository.canonical,request);if(!existing.record||stored(existing.record,request).state!=='COMPLETE'||!same(stored(existing.record,request).data,audit))throw error;}
  return this.read(request);
 }
 async read(input:unknown){
  const request=decodePilotRequest(input),snapshot=await decodeEnforcementSnapshot(await this.repository.exportSnapshot()),local=new MemoryCanonicalRepository();await local.importSnapshot(canonicalJSON(snapshot.canonical));const saved=await runRow(local,request);demand(saved.record,'B6_DURABLE_RUN_REQUIRED');const v=stored(saved.record,request);demand(v.state==='COMPLETE','B6_INCOMPLETE_RUN_HOLD');const audit=v.data as {public_output:unknown;content_hash:string;proof:{canonical_count:number;canonical_digest:string;enforcement_sequence:number;proof_digest:string};qualification:string;current_at_delivery:boolean};
  const e=snapshot.events.find(e=>e.sequence===audit.proof.enforcement_sequence);demand(e&&e.canonical_count===audit.proof.canonical_count&&e.canonical_digest===audit.proof.canonical_digest&&digest((e.result as {proof:unknown}).proof)===audit.proof.proof_digest,'B6_DURABLE_PROOF_DRIFT');
  const eventCommand=e.command as {kind:string;value:{principal:Identity;run:Identity;scope_version:number}};demand(eventCommand.kind==='VERIFY_PROJECTION'&&same(eventCommand.value.principal,request.principal)&&same(eventCommand.value.run,request.run)&&eventCommand.value.scope_version===request.recovery_scope_version&&e.at===request.as_of,'B6_DURABLE_PROOF_BINDING');
  const commands=snapshot.commands.slice(0,e.canonical_count),pinned=new MemoryCanonicalRepository();await pinned.importSnapshot(canonicalJSON({schema_version:SCHEMA_VERSION,commands,records:commands.map(c=>c.value)}));const captured=await runRow(pinned,request);demand(captured.record&&stored(captured.record,request).state==='CAPTURED','B6_CAPTURE_NOT_IN_PROOF_PREFIX');const proof=(e.result as {proof:{data:Foundation}}).proof,foundation={output:proof.data.output,completeness:proof.data.completeness},rebuilt=await compile(pinned,request,foundation),expected={...rebuilt,proof:{run:request.run,canonical_count:e.canonical_count,canonical_digest:e.canonical_digest,enforcement_sequence:e.sequence,proof_digest:digest((e.result as {proof:unknown}).proof)},qualification:'SOURCE_QUALIFIED_PINNED_AS_OF',current_at_delivery:false};demand(same(expected,audit),'B6_DURABLE_OUTPUT_DRIFT');
  return freeze({schema_version:B6,run:request.run,as_of:request.as_of,projection:rebuilt.public_output,content_hash:rebuilt.content_hash,proof:audit.proof,qualification:'SOURCE_QUALIFIED_PINNED_AS_OF',current_at_delivery:false,continuity_ON:false,authority_effect:'NONE',admission:'NOT_ADJUDICATED'});
 }
}
